### ISSUE TITLE
[BUG] DROP TENANT 'cnosdb'; should be prohibited from stopping

### ISSUE THREAD

**Issue by bfrgb** [cnosdb/cnosdb#1025]
![5D171E75-3E10-49B5-9EE4-6143DA39E78F](https://user-images.githubusercontent.com/119819515/225506980-492fa461-e80c-42df-ad72-78ae8caa0fd2.png)
![WX20230316-113328](https://user-images.githubusercontent.com/119819515/225507005-9a60e4ef-4749-49f7-85ab-381edce77f92.png)

**Comment by ZuoTiJia** [comment]
fixed in https://github.com/cnosdb/cnosdb/pull/1048
