### ISSUE TITLE
[Feature] Support Update Statement

### ISSUE THREAD

**Issue by ZuoTiJia** [cnosdb/cnosdb#1060]
Currently, CnosDB updates records only by writing the same time and tags to overwrite fields. Need to be able to update tags or time.

**Comment by muninshen** [comment]
I see we don't support Update tag yet according to the [doc](https://docs.cnosdb.com/en/reference/sql.html#alter-table).
To be exact, it would be great to have following update support on tag key and tag values:

- Update on tag key
```
 ALTER TABLE table_name RENAME COLUMN old_column_name TO new_column_name;

e.g.:
 ALTER TABLE air RENAME COLUMN station TO spot;
```
- Update on tag value
 ```
UPDATE
    table_name 
SET
    column_name = column_value2
WHERE column_name =  "column_value1";

e.g.:
UPDATE
    air 
SET
    station = "Shangdong-XiaoMaiDao",
WHERE station = "XiaoMaiDao";
```

If it is difficult to implement in SQL, you could try in command way:
Update on tag key: https://github.com/Abc-Arbitrage/infix#renametag-rule
Update on tag value: https://github.com/Abc-Arbitrage/infix#updatetagvaluerule

**Comment by IvanGao01** [comment]
I think some operations to delete data should also be added:
For example: 

[`DROP SERIES`](https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#drop-series-from-the-index-with-drop-series)
[`DELETE`](https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#delete-series-with-delete)

**Comment by yukkit** [comment]
The following is the behavior of update statement

# syntax
```sql
update clause :=
UPDATE <table name> SET <assignment clause> [, ...] [<where clause>]

assignment clause :=
<column name> = <column value>
```

# update tag value
1. The `set` only contains tags and can contain multiple tags.
2. The field column or time column cannot be included in the `where` condition.

# update field value
1. The `set` only contains field. 

------

# update tag value
1. `set` 中仅包含 tag，可包含多个
2.  `where` 条件中不能包含 field 列/time 列

# update field value
1. `set` 仅包含 field，可包含多个。

RFC @muninshen @IvanGao01 @roseboy-liu 
If the above behavior meets the requirements, I will open a new issue to start the update statement task.

**Comment by roseboy-liu** [comment]
LGTM

**Comment by yukkit** [comment]
# Design

## update tag value

增加算子 UpdateTagValue

### plan

- TagScan: 根据下推的过滤条件获取符合条件的所有 tag 值
- Aggregate: 对 tag 去重
- FilterExec: update 语句中的 where 条件会转换为此节点，负责过滤符合条件的所有 tag 值（注意返回结果中会包含所有 tag 列）
- UpdateTagValueExec：根据符合条件的 tag 值，修改对应值

```
┌───────────────────┐
│ UpdateTagValue    │
│  (set)            │
└──────▲────────────┘
       │
┌──────┴──────┐
│ Filter      │
│  (where)    │
└──────▲──────┘
       │
┌──────┴──────┐
│ Aggregate   │
│ (all tags)  │
└──────▲──────┘
       │
┌──────┴──────┐
│ TagScan     │
│  (where)    │
└─────────────┘
```

## update field value

query -> filter(where) -> project(set) -> insert => upsert

### plan

```
┌────────────┐
│ TableWrite │
│            │
└──────▲─────┘
       │
┌──────┴──────┐
│ Project     │
│  (set)      │
└──────▲──────┘
       │
┌──────┴──────┐
│ Filter      │
│ (where)     │
└──────▲──────┘
       │
┌──────┴──────┐
│ TableScan   │
│  (where)    │
└─────────────┘
```
