### ISSUE TITLE
[Feature]Data Replication in IoT

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#1073]
**Is your feature request related to a problem? Please describe.**
Data replication in IoT would help to improve fault-tolerance, reliability, and accessibility across the system.

**Describe the solution you'd like**
Computing tasks are performed on IoT gateways at the cloud edges to obtain a prompt response. At the same time, all the data from the edge are sent to the cloud for data visualization and modeling such as early detection or prediction works. Some factors need to be taken into consideration:

- Replication latency: Real time or not
- Network bandwidth consumption: If the amount of data to be replicated outpaces the available bandwidth, the replication is not going to be very successful at all. Sometimes, the bandwidth could be 20Mbps.
- Data integrity: having limited/unstable/no network bandwidth at certain times may lead to data loss or duplicate data.
- Data filtering

**Describe alternatives you've considered**
via telegraf

**Additional context**
Different mode could be  set up in the configuration file.

**Comment by roseboy-liu** [comment]
https://github.com/cnosdb/cnosdb/pull/1121

**Comment by roseboy-liu** [comment]
subscription support on enterprise edition
