### ISSUE TITLE
[Discussion]About the comparison of integer and floating point types

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1076]
**Describe the issue**
f1 is of BIGINT type. When f1 > -0.123 is judged, -0.123 will be converted to 0, resulting in the missing of the two lines with f1 0 in the result. However, if 0 > − 0.123 is used directly, the result is true, and the result of comparison by column name is different from that by direct numerical comparison
version: [cff2925cf0e3fb886be2680c2dd102f9617bcb19](https://github.com/cnosdb/cnosdb/tree/cff2925cf0e3fb886be2680c2dd102f9617bcb19)
![image](https://user-images.githubusercontent.com/50371898/229472923-012b0908-8e63-4f25-9189-b75ffc65699a.png)

**What you like us to do**
Regarding this issue, I believe that when precision loss occurs during the comparison process, users should be warned or the column name and value comparison handling should be made consistent with the handling of value-only comparisons.

**Additional context**
Add any other context about the issue here.

**Comment by yukkit** [comment]
Different databases have different behaviors for this, in my opinion, we should support it, so that it is more in line with user expectations
