### ISSUE TITLE
query bug with timestamp

### ISSUE THREAD

**Issue by xuegexi** [cnosdb/cnosdb#1082]
When I use sql-cmd "select * from user_queries where time <= to_timestamp_millis(1680856751413) limit 1;", I can't get a record; But i got a result with sql-cmd " select * from user_queries where time <= to_timestamp('2023-04-07T08:39:11') limit 1;".  I just convert the timestamp to datetime-string. It seems that there is a bug.

**Comment by yukkit** [comment]
Fixed in datafusion-21.0.0  https://github.com/apache/arrow-datafusion/issues/5507

**Comment by yukkit** [comment]
resolved,  closed by https://github.com/cnosdb/cnosdb/issues/1096
