### ISSUE TITLE
[BUG] Execute sql query SELECT SUM(1025561311408145024) FROM m3; , db returns error.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1085]
pre-requirements：
version: d5460e9deb14168cc02ffb08908dc2b06c110258
deploy:3meta 2data
testcase:
https://github.com/cnosdb/cnosdb/blob/main/query_server/test/cases/sqlancer/function.sql
Automated Execution Records：
https://github.com/Benxiaohai001/cnosdb/actions/runs/4627561115/jobs/8185615002
Manual test record：
<img width="975" alt="image" src="https://user-images.githubusercontent.com/40594937/230815964-14b3226a-34cf-4e4b-9771-29a5c534935a.png">
expected:
200 OK
SUM(Int64(1025561311408145024))
-6140008336811811328
actual output：
-- EXECUTE SQL: SELECT SUM(1025561311408145024) FROM m3; --
 -- AFTER_SORT --
 
-- ERROR:  --

**Comment by ZuoTiJia** [comment]
It seems that the Debug version of CnosDB is started in run_cluster.sh.
The Debug version adds overflow detection, which will cause the program to panic.
Use the Release version to solve it.
