### ISSUE TITLE
Loading line protocol data indicates insufficient memory

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1109]
Machine information：
IP：192.168.0.17
CPU：64 CPUs x Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
Memory：256 GB
Disk：SSD NVMe

code version：[06d730eaba2f0399010ff3598d1913095ff181f3](https://github.com/cnosdb/cnosdb/commit/06d730eaba2f0399010ff3598d1913095ff181f3)

start command：
cd meta
./singleton.sh -sc -sb --release
cd ..
./target/release/cnosdb run --cpu 64 --memory 200 --config ./config/config_8902.toml

Connect to the cnosdb and create the database：
create database test with TTL '10000' shard 6;

Load data command：
./load_cnosdb --do-abort-on-exist=false --do-create-db=false --gzip=false --file=/home/ivan/cnodb-iot-seed-123-scale-100-2021 --db-name="test" --urls="http://127.0.0.1:8902" --batch-size=20000 --workers=100

Step of reproduction：
In the first step, execute the load data command for 6 minutes,memory information at this time
<img width="722" alt="6min后的内存信息" src="https://user-images.githubusercontent.com/50371898/232372792-29135629-2f83-475d-8e56-3f02d270a33a.png">

After manually stopping the load data command, execute the load data command again,error information and memory information at this time
<img width="732" alt="报错后的内存信息" src="https://user-images.githubusercontent.com/50371898/232373126-e40de6b6-1659-4f3a-b17a-8f69f18077e0.png">
<img width="1633" alt="load_cnosdb的报错信息" src="https://user-images.githubusercontent.com/50371898/232373212-3f897aaf-4885-4f96-b1cf-04bfd326f3d0.png">
<img width="1643" alt="cnosdb报错信息" src="https://user-images.githubusercontent.com/50371898/232373280-8925c474-b8b5-4966-a76b-ef19e2f9f550.png">

**Comment by Subsegment** [comment]
free -g not very accurate. The reason for this problem is that we pass the cpu as memory to the memory pool, so the memory is full at 64g, and we can observe the log before memory exhaustion `INFO tskv::tseries_family: mut_cache is full, switch to immutable. current pool_size : 68490028680 at tskv/src/tseries_family.rs:818`. but free -g show used 48. I will submit a pr to fix this issue

**Comment by lutengda** [comment]
version: 8b251819e90ef3f595e5fb0ae98c1de11b1561d6
It has been verified that the error message does not appear according to the above reproduction steps, the bug is solved, and the issue is closed
