### ISSUE TITLE
[Test] Add more test case for jdbc through arrow flight sql

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#1122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Benxiaohai001** [comment]
Cnosdb cannot connect through odbc #1325  and jdbc #1324 ；

**Comment by Benxiaohai001** [comment]
#1334

**Comment by Benxiaohai001** [comment]
JDBC Done
