### ISSUE TITLE
A question about the create statement

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1126]
cnosdb version：[ef1b5d0dcc9d3db0858e8d850a89b07b3c839a5f](https://github.com/cnosdb/cnosdb/commit/ef1b5d0dcc9d3db0858e8d850a89b07b3c839a5f)
I find that this statement can be executed
> create table test(col bigint,);

But this statement is executing with an error
<img width="1274" alt="create语句问题" src="https://user-images.githubusercontent.com/50371898/233524521-674fbd9c-03c2-4420-8f8a-d38dc31941e2.png">

**Comment by yukkit** [comment]
syntax parsing error
