### ISSUE TITLE
[BUG]drop vnode causes write failure

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1152]
### Describe the bug

clusters: 2 data,3 meta
version: [ea47f4eb81cee966648f95d4ad34044e8a6f28d3](https://github.com/cnosdb/cnosdb/commit/ea47f4eb81cee966648f95d4ad34044e8a6f28d3)

The first time to write data succeeded, but after dropping the vnode, the second time to write data failed, and the vnode was not created

### To Reproduce

The first data write was successful
> curl -XPOST -u "root:" "http://127.0.0.1:8902/api/v1/write?db=public" -d "ma,ta=a fa=1"
> select * from ma;
> +----------------------------+----+-----+
> | time                       | ta | fa  |
> +----------------------------+----+-----+
> | 2023-04-27T10:14:25.373394 | a  | 1.0 |
> +----------------------------+----+-----+

Find and drop the unique vnode
> DROP VNODE 6;
> select * from ma;
> Query took 0.021 seconds.

The second attempt to write data failed,and vnode not be created
> curl -XPOST -u "root:" "http://127.0.0.1:8902/api/v1/write?db=public" -d "ma,ta=a fa=1"
> select * from ma;
> Query took 0.020 seconds.

Writing to another node 8912 also failed,and vnode not be created
> curl -XPOST -u "root:" "http://127.0.0.1:8912/api/v1/write?db=public" -d "ma,ta=a fa=1"
8902/8912
> select * from ma;
> Query took 0.020 seconds.

**Comment by roseboy-liu** [comment]
I wanted to reproduce this issue in single-player mode, but another error occurred. 
![image](https://user-images.githubusercontent.com/97928896/236174971-d3def715-c15a-4d87-8b2e-868f57db354b.png)
