### ISSUE TITLE
[Feature] Store data that dropped by DROP TABLE command 

### ISSUE THREAD

**Issue by zipper-meng** [cnosdb/cnosdb#1178]
**Is your feature request related to a problem? Please describe.**

Bug: Cache data removed by dropping the table recovered after restart.

This is because the `DROP TABLE` command deleted the cache but the data is still in WAL, so it caused.

**Describe the solution you'd like**

`DROP TABLE` execution will create WAL entries when deleting data in memory caches, after successfully wrote them to WAL, do the memory cache deletes.

**Describe alternatives you've considered**

**Additional context**

**Comment by roseboy-liu** [comment]
+  drop vnode

**Comment by zipper-meng** [comment]
A bug fix: #1363
