### ISSUE TITLE
[Feature] Support node offline and mark node status

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#1182]
**Is your feature request related to a problem? Please describe.**
Support node offline and mark node status

`SQL： removenode nodeid [force] ` 

1. Without the "force" option, this command only marks a state for the node. The node can only read the vnodes on the current node and is not allowed to create new vnodes. By using TTL expiration and data migration, the vnodes on the node will be gradually cleared. Finally, the information of the node will be deleted.

2. With the "force" option, the data on the node will be migrated. After the migration is completed, the information of the node will be deleted.

**Describe alternatives you've considered**

**Additional context**

**Comment by lutengda** [comment]
this feature has been implemented, this issue closed
