### ISSUE TITLE
[BUG]The compact vnode fails after manually deleting the tsm file

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1191]
### Describe the bug

version:
`cnosdb 2.3.0, revision f0cf70160e9eed8f49b00cc6e0c62b764796a78b`

cluster:
`3meta,2data`

1.Write a piece of data with the curl command:
`curl -XPOST -u "root:" "http://192.168.0.19:8902/api/v1/write?db=public" -d "ma,ta=a fa=1"`

2.Locate the vnode id according to the storage configuration entry in the configuration file

3.After connecting to cnosdb through cnosdb-cli, execute:
```
compact vnode <vnode_id>
select * from ma;
```

4.The tsm file is then deleted with the rm command
5.If you execute the compact vnode command again, you will see that no tsm files are generated

### Expected behavior

I think that if the tsm file is manually deleted, executing the compact vnode should produce the tsm file again

**Comment by zipper-meng** [comment]
It's too difficult to repair the deleted file.

I suggest marking the file broken to prevent file reader get unexpected data.

**Comment by bartliu827** [comment]
I thank this is not a problem. The data has been damaged. If there is a replica, it can be restored by the replica is ok.
If there is no replica, it will be permanently lost.

**Comment by roseboy-liu** [comment]
mark vnode broken，repair the replication set。

**Comment by lutengda** [comment]
In the case that replica is 1, after manually deleting tsm file through rm command, an error will be reported when select * from ma query again, which meets the expectation, and this issue will be closed
