### ISSUE TITLE
[BUG]The query result is unstable after the multi-copy file is damaged

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1192]
### Describe the bug

version:
`cnosdb 2.3.0, revision f0cf70160e9eed8f49b00cc6e0c62b764796a78b`

cluster:
`3meta 2data`

1.Create a two-copy database after you connect the database:
`create database db1 with replica 2;`

2.Write a piece of data with the curl command:
`curl -XPOST -u "root:" "http://127.0.0.1:8902/api/v1/write?db=db1" -d "ma,ta=a fa=1"`

3.At this point, you will find that there are vnodes on both data nodes, and then drop the two vnodes through compact vnode <vnode-id>:
`compact vnode <vnode-id>;`

4.Then modify and destroy the tsm file in one of the vnodes, and then query the table multiple times through sql, you will find that sometimes successful, sometimes failed:
`select * from ma;`

### Expected behavior

Because there are two backups, if one of the tsm files is corrupted, multiple select queries should yield the correct result

**Comment by lutengda** [comment]
I suggest that when you read the wrong tsm file, add a log of the read failure and then read another backup (if there is one)

**Comment by roseboy-liu** [comment]
**1. manage vnode status**
**2. vnode topology**
3. node status / metrics + vnode metric（cpu + memory）+ task

**Comment by lutengda** [comment]
I found that after corrupting a TSM file, when executing 'select * from ma' for the first time, it would throw an error, but it wouldn't throw an error for subsequent executions.
version: ad5725e028215fba9fa500938b8ce2ae2991d439
error info:
`422 Unprocessable Entity, details: {"error_code":"050019","error_message":"grpc client request error: grpc status: status: Internal, message: \"read tsm block file error: TSM file is invalid: TSM file (0) size less than index offset(11018)\", details: [], metadata: MetadataMap { headers: {} }"}`
![image](https://github.com/cnosdb/cnosdb/assets/50371898/44ac2aaa-135c-47e8-a598-f85b0435f708)

**Comment by bartliu827** [comment]
1. First. Change tokio::sync RwLock to parking_lot::RwLock in MetaAdmin.
2. Secondly, synchronously modify the local vnode status.
3. Asynchronously  persistence of vnode state to meta.
4. Determine whether to retry based on the error code.
5. The process of modifying the status of a vnode from VnodeStatusListener  to CheckedCoordinatorRecordBatchStream.

**Comment by lutengda** [comment]
After destroying a tsm file, multiple select will not report an error, this issue is closed

**Comment by lutengda** [comment]
version: 1e4945998f4158675f86ea8e7135f8b8f6cc12d2
3+2 mode
create database db1 with replica 2;
write one line protocal data, compact vnode, then rm a tsm file, multiple select report error
![image](https://github.com/cnosdb/cnosdb/assets/50371898/0724abcf-e310-4b18-a147-9058271f1c49)

**Comment by Subsegment** [comment]
finish
