### ISSUE TITLE
[Feature] cnosdb-cli need to support https request

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#1209]
**Is your feature request related to a problem? Please describe.**
cnosdb-cli currently uses http, so cnosdb-cli cannot be used after opening the security configuration

**Describe the solution you'd like**
cnosdb-cli support https request

**Comment by zipper-meng** [comment]
PR #1225.
You can use `cnosdb-cli --ssl [--unsafe-ssl]` to connect to server with https connection.

**Comment by lutengda** [comment]
Please add examples of how to use the --ssl and --unsafe-ssl parameters

**Comment by zipper-meng** [comment]
> Please add examples of how to use the --ssl and --unsafe-ssl parameters

user api changed in #1225 :

```sh
# connection to https://localhost:8902
cnosdb-cli --ssl

# connection to https://dev.cnosdb.na.:31001
cnosdb-cli --ssl --host dev.cnosdb.na --port 31001

# connection to https://dev.cnosdb.na.:31001 , without ssl check
cnosdb-cli --host dev.cnosdb.na --port 31001 --ssl --unsafe-ssl 

# connection to https://localhost:8902 with a certificate file.
cnosdb-cli --ssl --cacert ./tls/server.crt
```

**Comment by lutengda** [comment]
# connection to https://localhost:8902 with a certificate file.
both "cnosdb-cli --ssl --cacert ./tls/server.crt" and "cnosdb-cli --ssl --cacert ./tls/client.crt" do not work, please find the right way about how to use --ssl with certificate file.

**Comment by lutengda** [comment]
open this configuration:
![image](https://github.com/cnosdb/cnosdb/assets/50371898/9e43cbba-d554-44c6-93b1-381289d2782a)

connect command:
cnosdb-cli --ssl --cacert ./config/tls/ca.crt

version: b67a07241644be8ff36dede9f80425bc43f93328
this feature is implemented and this issue is closed
