### ISSUE TITLE
[BUG]Drop a not exist table will not meet a error.

### ISSUE THREAD

**Issue by Lunmer** [cnosdb/cnosdb#1218]
### Describe the bug

When I tried to drop a not exist table,It returns the result of Query took xxx seconds rather  returns the table is not found.
<img width="364" alt="bug" src="https://github.com/cnosdb/cnosdb/assets/46554365/633330e6-f67d-4dda-b12b-70d53bc30252">

**Comment by roseboy-liu** [comment]
Expected behavior ？
