### ISSUE TITLE
Implemention of flink-cdc-cnosdb and flink-connector-cnosdb

### ISSUE THREAD

**Issue by Lunmer** [cnosdb/cnosdb#1226]
The data sets from Telegraf often need to do complex caculation in Flink before write to CnosDB. So if your team could implement the plugins of flink-cdc-cnosdb and flink-connector-cnosdb, that's will be very helpful. By the way，the data sets write into flink-cdc-cnosdb and keep  copies locally is necessary, because the data sets may come from small cluster.

**Comment by ZuoTiJia** [comment]
https://github.com/cnosdb/cnosdb/issues/1411
