### ISSUE TITLE
CnosDB missing system table for obtaining meta information

### ISSUE THREAD

**Issue by bfrgb** [cnosdb/cnosdb#1239]
The current way to obtain VNode information is through the meta interface. However, some data can also be obtained through SQL queries, such as node information. Can we unify the way to obtain Node-related information so that all Node-related information can be obtained through system tables or SQL queries, making it easier to maintain?

Currently, CnosDB only has SQL for displaying nodes:
![image](https://github.com/cnosdb/cnosdb/assets/119819515/2860d6a9-a495-4399-8cb5-dce4453c6530)
I hope to add an information table for VNodes, which includes the following fields:

VNodeID, VNodeGroupID, Bucket, Database, NodeID, StartTime, EndTime.
Regarding the fields:
For the VNodeGroup field, I hope to have a separate table to record information about VNodeGroups;
For the Bucket field, I hope to have a separate table to record information about Buckets.

**Comment by Subsegment** [comment]
supported in enterprise edition💰
