### ISSUE TITLE
[BUG] A large number of file handles marked as deleted have appeared, resulting in sustained growth of disk space

### ISSUE THREAD

**Issue by IvanGao01** [cnosdb/cnosdb#1242]
### Describe the bug

When writing unordered data, it appears that a large number of file handles are marked as deleted, which causes the file space to continue to grow.

### To Reproduce

1. Show the disk space before
```
df -h
```
2. List all the deleted files which are still on disk due to the open file descriptors caused by CnosDB
```
lsof | grep deleted | wc -l
```
```
lsof | grep deleted | grep cnosdb | wc -l
```

```
lsof | grep deleted | grep cnosdb
```
3. Locate the process
```
ps -ef | grep $PID
```
4. Restart the process will release the space

**Comment by zipper-meng** [comment]
You can use this command to see that:

```
$ lsof | grep deleted | grep cnosdb
```

**Comment by Benxiaohai001** [comment]
version : 35d729cd399ba08174ca379b0cedab346aaaa919
single mode
![image](https://github.com/cnosdb/cnosdb/assets/40594937/9e08d2c1-739c-4fca-b6c3-3f632c0f8e06)
![image](https://github.com/cnosdb/cnosdb/assets/40594937/897aae5c-02f0-4bd0-a4fd-34be2e9250f5)
![image](https://github.com/cnosdb/cnosdb/assets/40594937/25519818-2fb5-4ef7-b843-2a1c4f308ba8)

**Comment by roseboy-liu** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/97928896/70c71a27-5795-4bf9-b938-89d28a9184a2)

**Comment by Benxiaohai001** [comment]
Write 100g of out-of-order line protocol data, write colleagues to execute lsof|grep delete|cnosdb, m query every five seconds.The problem of long-term handle not being released has not been found.
the issue was solved,so close the issue.
ce version: 240d84ed17e3bdc0dacf7876e90d46d618b3e08b
