### ISSUE TITLE
[BUG] When the cnosdb cluster is restarted on k8s, some tskv nodes cannot be started

### ISSUE THREAD

**Issue by xuegexi** [cnosdb/cnosdb#1246]
### Describe the bug

The reasons for the failure to restart include but are not limited to memory exhaustion and authentication errors caused by a tenant not existing.

**Comment by Benxiaohai001** [comment]
After communication and test steps, new tenants were created, data was written, and meta and tskv nodes were restarted continuously, no startup failure was found. Follow-up can be observed for a period of time, if similar problems do not occur, you can close the problem.

**Comment by zipper-meng** [comment]
Line 647 converts a meta query response `Result<Arc<TenantMeta>>` into an `Option<Arc<TenantMeta>>`, the error (connecting or others) was discarded.

https://github.com/cnosdb/cnosdb/blob/0b2404d8daa9f31770a68cb0d5c3bce16f327b73/meta/src/model/meta_admin.rs#L640-L651
