### ISSUE TITLE
[BUG] The query result missing some data

### ISSUE THREAD

**Issue by IvanGao01** [cnosdb/cnosdb#1247]
### Describe the bug

There is some confusion in the processing of the time zone when suspected, resulting in not getting the expected data when querying the data

**Comment by zipper-meng** [comment]
You mean that you want to customize the time zone in configuration?

**Comment by Benxiaohai001** [comment]
After communication, it is related to the monitoring environment, and the monitoring situation will be followed up. Check for similar issues

**Comment by IvanGao01** [comment]
This issue seems to have been fixed: #1283
