### ISSUE TITLE
[Feature] Set Resource Limits on Global and User levels

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#1286]
**Is your feature request related to a problem? Please describe.**
Whether in standalone instance or distributed model or even in cloud, restricting client use of CnosDB server resources is a must. There should be ways to set resource limits on global and user levels.

**Describe the solution you'd like**
These limits could be applies:
1. The number of queries an user can issue per hour
2. The number of updates an user can issue per hour
3. The number of deletes an user can issue per hour
4. The number of insert an user can issue per hour
5. The number of times an user can connect to the server per hour
6. The number of simultaneous connections to the server by an user 

The values should be non zero values and zero values means no limits.

These settings should be exposed in the global level via configuration files while user-level restrictions should managed in SQL statements (CREATE and ALTER). 

**Describe alternatives you've considered**

**Additional context**
Here is the [MySQL way](https://dev.mysql.com/doc/refman/8.0/en/user-resources.html), [InfluxDB way](https://docs.influxdata.com/influxdb/cloud/account-management/limits/#global-limits), and [VM way](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html).

**Comment by yukkit** [comment]
could you describe the purpose of your requirement or the problem you want to solve?

**Comment by muninshen** [comment]
Some of my end users are thinking to deploy the distributed version of CnosDB for their private cloud and allocate it to multiple departments and users internally. They want to deploy one cluster that imposes default basic restrictions on resource usage for different users, while also providing separate handling for users requiring special attention.

**Comment by roseboy-liu** [comment]
Cnosdb support resource limits on tenant.

**Comment by roseboy-liu** [comment]
@ZuoTiJia  docs & test

**Comment by ZuoTiJia** [comment]
Chinese doc: https://docs.cnosdb.com/zh/latest/manage/resource_limit.html

**Comment by Benxiaohai001** [comment]
```log
public ❯ create database db004;
422 Unprocessable Entity, details: {"error_code":"030000","error_message":"Create database failed, the maximum number of database is 3"}

public ❯ alter tenant test add user test_user02 as owner;
422 Unprocessable Entity, details: {"error_code":"030000","error_message":"users reached limit, max is 1"}
public ❯ create database db004  with shard 3;
422 Unprocessable Entity, details: {"error_code":"030000","error_message":"Create database failed, the maximum number of database's shards is 2"}
public ❯ create database db004  with replica  3;
422 Unprocessable Entity, details: {"error_code":"030000","error_message":"Create database failed, the maximum number of database's replica is 2"}

public ❯ create database db004  with ttl '60';
422 Unprocessable Entity, details: {"error_code":"030000","error_message":"TTL reached limit, max is 30 days"}

```

**Comment by Benxiaohai001** [comment]
```log
INSERT INTO air (TIME, station, visibility, temperature, presssure) VALUES (now(), 'XiaoMaiDao1', 56, 69, 411);
INSERT INTO air (TIME, station, visibility, temperature, presssure) VALUES (now(), 'XiaoMaiDao2', 56, 69, 411);
INSERT INTO air (TIME, station, visibility, temperature, presssure) VALUES (now(), 'XiaoMaiDao3', 56, 69, 411);
INSERT INTO air (TIME, station, visibility, temperature, presssure) VALUES (now(), 'XiaoMaiDao4', 56, 69, 411);
+------+
| rows |
+------+
| 1    |
+------+
Query took 0.017 seconds.
422 Unprocessable Entity, details: {"error_code":"050001","error_message":"Meta request error: DataIn reached limit"}
public ❯ select * from air;
422 Unprocessable Entity, details: {"error_code":"050001","error_message":"Meta request error: Queries reached limit"}


```

**Comment by Benxiaohai001** [comment]
1

**Comment by lutengda** [comment]
1
