### ISSUE TITLE
[BUG] The sample function returns null when the cpu numbers is smaller than the number of sample function random records

### ISSUE THREAD

**Issue by IvanGao01** [cnosdb/cnosdb#1294]
### Describe the bug

 
The sample function returns null when the cpu numbers is smaller than the number of sample function random records

### To Reproduce

First, follow the [quick start](https://docs.cnosdb.com/en/latest/start/quick_start.html) tutorial to import the sample data
Execute the following query, which will return null

```sql
public ❯ select sample(visibility, 5) from air;
+---------------------------------+
| sample(air.visibility,Int64(5)) |
+---------------------------------+
| []                              |
+---------------------------------+
Query took 0.178 seconds.
```
Since my cpu numbers is 8, it will only work if the value >= 8 is set for the sample function.
```
public ❯ select sample(visibility, 8) from air;
+--------------------------------------------------+
| sample(air.visibility,Int64(8))                  |
+--------------------------------------------------+
| [57.0, 76.0, 59.0, 53.0, 76.0, 66.0, 77.0, 52.0] |
+--------------------------------------------------+
Query took 0.187 seconds.
```

**Comment by lutengda** [comment]
After modification, the test shows that the number of samples has nothing to do with the number of cpu cores, and the bug has been fixed
