### ISSUE TITLE
[Feature] Integrate the OSIsoft PI System (including the ability to read and write Asset Framework data)

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#1295]
**Is your feature request related to a problem? Please describe.**
> One of the most frequently asked end user questions, particularly from Manufacturing and Energy customers, is "Can you connect to OSIsoft's PI System?".  There are many standard ways to do this using JDBC and ODBC drivers supplied by OSIsoft.  However, for the casual data discovery user, these require some extra configuration steps that can be challenging.

> The PI System collects, stores, and manages data from your plant or process. Your data sources connect to one or more PI Interface nodes. The PI Interface nodes collect data from your data sources and store into the PI Data Archive. Asset Framework (AF) organizes and enhances the data. Users consume the data by the use of a tool of the PI Visualization Suite (PVS) such as PI Vision.

> PI Interfaces collect data from external data sources, providing real-time, faulttolerant data to the PI System.

> The PI Data Archive is a component of the PI Server that provides efficient storage and archiving of time series data enabling high performance data retrieval by client software.

> PI Asset Framework (PI AF) is a single repository for asset-centric models, hierarchies, objects, and equipment. It integrates, contextualizes, refines, references, and further analyzes data from multiple sources, including one or more PI Data Archives and non-PI sources such as external relational databases.

**Describe the solution you'd like**
Some providers provides solution to allow:
- Reading of PI Tag data and metadata
- Reading of Asset Framework (AF) data and metadata
- Reading of Event Frame data

Here is the [Seeq way](https://support.seeq.com/space/KB/112822909/OSIsoft+Asset+Framework+(AF)+Connector), [TIBCO way](https://community.tibco.com/s/article/Getting-Data-into-TIBCO-Spotfire-from-OSIsoft-PI-Asset-Framework-and-Event-Frames). 

Here is the detailed official doc to show you "[Building PI System Assets and Analytics with PI AF](https://osicdn.blob.core.windows.net/learningcontent/pdfs/Building%20PI%20System%20Assets%20v2018%20SP2.pdf)".

**Describe alternatives you've considered**

**Additional context**

**Comment by roseboy-liu** [comment]
Supported in Enterprise Edition
