### ISSUE TITLE
[BUG]An error message was generated while deleting tenants

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1302]
### Describe the bug

version: 4b1693154029f577dc9f9b8a085f43e017bcf5ac
Single node startup
I created a tenant and a user, and gave the user the owner rights of the tenant. Here is my SQL statement:

> CREATE TENANT tenant_a;
> CREATE USER user_a;
> ALTER TENANT tenant_a ADD USER user_a AS owner;

Then I query this table and find that there is already a tenant that I created:
![image](https://github.com/cnosdb/cnosdb/assets/50371898/bc20150d-9dd8-46b6-af67-5950213bbfd2)
Then I try to delete this tenant, this is an error occurred, this is the SQL statement:

> DROP TENANT tenant_a;

An error occurred after executing the delete statement：

> 422 Unprocessable Entity, details: {"error_code":"030028","error_message":"Decode message error reason: invalid type: null, expected a boolean at line 1 column 10"}

At this point, I checked again and found that the tenant was no longer available：
![image](https://github.com/cnosdb/cnosdb/assets/50371898/c1d20f40-4c5e-4370-ad81-f208c5831138)

### Expected behavior

Although the tenant deletion was successful, the error message should not appear

**Comment by bartliu827** [comment]
WriteCommand::DropTenant： Encoding and decoding format mismatch

**Comment by roseboy-liu** [comment]
add to e2e testcase

**Comment by lutengda** [comment]
Delete tenant no error, this issue is closed
