### ISSUE TITLE
Loading historical data from MySQL to CnosDB

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#132]
**Is your feature request related to a problem? Please describe.**
Many existing IoT infrastructure use MySQL as their core database. Some are looking to use the CnosDB as the TSDB part. Should we provide an easy way to migrate those historical data?

**Describe the solution you'd like**
We could guide the users to migrate their time series data from MySQL to CnosDB via best practices.

**Describe alternatives you've considered**
Maybe some plugin or Python/PowerShell script could be implemented.

**Use case**
In an effort to garner meaning from rapidly growing data sources, an increasing amount of organizations find themselves having to move their data from a traditional relational database to a non-relational database. The scenario under consideration for this article is based on the need to analyze and visualize trends over large periods of time over large amounts of time series data.

**Comment by bartliu827** [comment]
just loading historical data? or real-time increment function.

**Comment by bartliu827** [comment]
使用说明
https://github.com/cnosdb/docs/blob/main/src/content/cnosdb/latest/managerment/export_import.md#pgsqlmysql%E6%95%B0%E6%8D%AE%E5%AF%BC%E5%85%A5
