### ISSUE TITLE
[BUG]In the deployment mode where storage and computing are separated, CI of some use cases cannot pass

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1335]
### Describe the bug

In the deployment mode where storage and computing are separated, CI of some use cases cannot pass.
Deployment form of separation of storage and calculation, execution of the use case, executed three times before and after, the abnormal use cases are 'select at /__w/cnosdb/cnosdb/query_server/test/cases/sqlancer'

### To Reproduce

log as fellow link:
https://github.com/Benxiaohai001/cnosdb/actions/runs/5483267329/jobs/9990987621

**Comment by yukkit** [comment]
same with #1303

**Comment by roseboy-liu** [comment]
Here is a key log
`
{"error_code":"050016","error_message":"Node failover: 2001, error: Status { code: ResourceExhausted, message: \"h2 protocol error: http2 error: connection error received: detected excessive load generating behavior\", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b\"\", ENHANCE_YOUR_CALM, Remote) }))) }"}
`

**Comment by roseboy-liu** [comment]
https://pipelines.actions.githubusercontent.com/serviceHosts/8fac4e01-af9b-445b-84f6-b8b95c1c3263/_apis/pipelines/1/runs/3115/signedlogcontent/10?urlExpires=2023-07-11T09%3A52%3A31.6427373Z&urlSigningMethod=HMACV1&urlSignature=3wZqLE6DacfxxwzHh1e3cb9rgNQkPBbtS9feJUmNwg4%3D

**Comment by roseboy-liu** [comment]
The tonic implementation of grpc uses h2, but does not expose all the parameters of the http/2 client Builder and uses some default values. These default values are useful for us under high load conditions:
reset_stream_max
reset_stream_duration
pending_accept_reset_stream_max

Some requests pile up when the cpu can't handle them.

**Comment by Benxiaohai001** [comment]
https://github.com/cnosdb/cnosdb/actions/runs/5584505420/jobs/10206014715?pr=1334
verify

**Comment by Benxiaohai001** [comment]
version: cnosdb 2.3.2, revision 28a61e9b41050375cc7e0dc1631d3f70ecccb7b8
```log
query error Arrow error: Io error: Status \{ code: Cancelled, message: "h2 protocol error: http2 error: stream error received: stream no longer needed", source: Some\(tonic::transport::Error\(Transport, hyper::Error\(Http2, Error \{ kind: Reset\(StreamId\(3\), CANCEL, Remote\) \}\)\)\) \}
select increase() from func_tb2;
```

**Comment by roseboy-liu** [comment]
> version: cnosdb 2.3.2, revision [28a61e9](https://github.com/cnosdb/cnosdb/commit/28a61e9b41050375cc7e0dc1631d3f70ecccb7b8)
> 
> ```
> query error Arrow error: Io error: Status \{ code: Cancelled, message: "h2 protocol error: http2 error: stream error received: stream no longer needed", source: Some\(tonic::transport::Error\(Transport, hyper::Error\(Http2, Error \{ kind: Reset\(StreamId\(3\), CANCEL, Remote\) \}\)\)\) \}
> select increase() from func_tb2;
> ```

linked https://github.com/cnosdb/cnosdb/issues/1591
