### ISSUE TITLE
[BUG]Data is continuously written and queried, and the memory usage rate continues to increase

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1338]
### Describe the bug

Data is continuously written and queried, and the memory usage rate continues to increase.
version: cnosdb 2.3.0, revision = f0cf70160e9eed8f49b00cc6e0c62b764796a78b

### Additional context

picture
![image](https://github.com/cnosdb/cnosdb/assets/40594937/679a319e-234b-459f-b630-756424cd94de)
![image](https://github.com/cnosdb/cnosdb/assets/40594937/7d27fda0-ee06-4eb4-b895-f05d68d189e7)

**Comment by roseboy-liu** [comment]
linked https://github.com/cnosdb/cnosdb/pull/1255
