### ISSUE TITLE
[DISCUSS]Whether to allow users to write data to ussage_schema?

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1345]
### Describe the bug

Whether to allow users to write data to ussage_schema?
If users can write data into this database, will it affect our monitoring?
The current situation is as follows:
```log
usage_schema ❯ CREATE TABLE air002 (visibility DOUBLE,temperature DOUBLE,presssure DOUBLE,TAGS(station));
Query took 0.023 seconds.
usage_schema ❯ select * from air002;
422 Unprocessable Entity, details: {"error_code":"030019","error_message":"Table not found: \"air002\""}
usage_schema ❯ INSERT INTO air002 (TIME, station, visibility, temperature, presssure) VALUES (1667456411000000000, 'XiaoMaiDao1', 56, 69, 411);
422 Unprocessable Entity, details: {"error_code":"030019","error_message":"Table not found: \"air002\""}
usage_schema ❯ \d
+--------------------+
| table_name         |
+--------------------+
| air                |
| air001             |
| air002             |
| coord_data_in      |
| coord_data_out     |
| http_data_out      |
| user_queries       |
| vnode_cache_size   |
| vnode_disk_storage |
+--------------------+
Query took 0.035 seconds.
```

**Comment by roseboy-liu** [comment]
This tenant is our default tenant so users can see what normal users who come in won't see. A new tenant should be created for reading and writing.

**Comment by Benxiaohai001** [comment]
The final result after discussion is: the default tenant allows reading and writing, and the new tenant can only read but not write.

**Comment by Benxiaohai001** [comment]
After testing, it has been modified according to the above expectations and the verified version：cnosdb 2.3.2, revision 9a4873ae9606cc243e2bc224c0b7d9739d3fc811
