### ISSUE TITLE
Meta cluster has errors in health status inspection of data nodes

### ISSUE THREAD

**Issue by bartliu827** [cnosdb/cnosdb#1348]
### Describe the bug

1. Meta's inspection of Data nodes is only conducted on the Leader
2. The inspection results should be distributed through the raft protocol, the Leader and Follower should be modified simultaneously
3. If only the Leader node is changed, it will cause data inconsistency
4. The error in function detect_node_heartbeat()

**Comment by lutengda** [comment]
Modify raft protocol to synchronize data, this issue is closed
