### ISSUE TITLE
[Improve] Query performance needs to be improved

### ISSUE THREAD

**Issue by Subsegment** [cnosdb/cnosdb#1351]
It uses tsdb-comparisons to generate data, imports it into CnosDB, executes SQL, and finds that query performance still has room for improvement
 tsdb-comparisons data:
`./generate_data --use-case="iot" --seed=123 --format="influx" \
    --timestamp-start="2022-01-01T00:00:00Z" \
    --timestamp-end="2023-01-01T00:00:00Z" \
    --file=~/data.txt --log-interval="5s" --scale=100
`
SQL:

- `select count (*) from readings` now 44 second, expected 2 second
- `select count(*), max(latitude), min(latitude), avg(latitude) from readings where time >= '2021-01-01 00:00:00.000000' and time <= '2022-01-01 00:00:00.000000';` now 27 second, expected 5 second
- `select count(*), max(latitude), min(latitude), avg(latitude) from readings where time >= '2021-01-01 00:00:00.000000' and time <= '2022-01-01 00:00:00.000000' and fleet = 'East';` now 10 sencond, expected 1 second

**Comment by roseboy-liu** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/97928896/5c29c36e-08ba-4c76-a2ff-0e6f3caa61f7)
