### ISSUE TITLE
[BUG]out of order data query error

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1356]
### Describe the bug

version: 8d511feea862d44ac071e9e0caac7d4e20626625

start mode:
`nohup ./target/release/cnosdb run --config ./config/config_8902.toml -M singleton > ./target/cnosdb_output.log 2>&1 &`

machine & user:
`192.168.0.58 gitlab-runner`

data:
`192.168.0.58:/home/cnosdb_dev/cnosdb_iot_123_2022_unorder.gz`

load_data:
`cat /home/cnosdb_dev/cnosdb_iot_123_2022_unorder.gz | gunzip | load_cnosdb --urls http://127.0.0.1:8902/ --workers 24 2>&1`

query:
`run_queries_cnosdb --db-name=benchmark --workers=123 --urls http://localhost:8902 --file /home/cnosdb_dev/queries/low-fuel.txt`

log path:
`192.168.0.58:/home/gitlab-runner/cnosdb/`

error info:
`ERROR cnosdb::http::http_service: Failed to handle http sql request, err: Query: Datafusion: External error: External error: External error: External error: TskvError: Unable to open file '/home/gitlab-runner/cnosdb/1001/db/data/cnosdb.benchmark/9/delta/_000174.delta': Too many open files (os error 24)`

delta file:
![image](https://github.com/cnosdb/cnosdb/assets/50371898/ec68e72f-12e8-4a4d-ad4f-234ad1c96aec)

### Expected behavior

query out-of-order data should not report error

**Comment by civi1007** [comment]
This issue has been resolved.
