### ISSUE TITLE
Docker image don't work on macos(apple silicon)

### ISSUE THREAD

**Issue by xmh1011** [cnosdb/cnosdb#1368]
### Describe the bug

Docker image don't work on macos(apple silicon).

### To Reproduce

Use the command in docs to start cnosdb container.
`docker run --name cnosdb -d cnosdb/cnosdb:community-latest cnosdb run -M singleton`
It doesn't work, the container log is:
` qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory`
<img width="1799" alt="image" src="https://github.com/cnosdb/cnosdb/assets/88817514/740bdbaf-ae0e-44c5-bf97-c6c46f0c305f">

**Comment by lutengda** [comment]
Building the arm64 image is temporarily problematic, so you can use this command to pull the amd64 image on Mac:
docker pull cnosdb/cnosdb:community-latest --platform linux/amd64

**Comment by lutengda** [comment]
Now, cnosdb image support amd64 and arm64, this issue close
