### ISSUE TITLE
[Feature] Support aggregate function max_n

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#1390]
**Is your feature request related to a problem? Please describe.**
Get the N largest values from the specified column.

**Describe the solution you'd like**

- Syntax
```sql
max_n(<column name>, <N>): <values>
```

- arguments
```
time colume: ......
colume name: The column whose max N values is to be obtained. Support BIGINT, BIGINT UNSIGNED, Double, TIMESTAMP data types.
N: The number of values to retain.
```

- returns
```
values: The array of max N values.
```

**Describe alternatives you've considered**

Add to the https://github.com/cnosdb/cnosdb/tree/main/query_server/query/src/extension/expr/aggregate_function

**Additional context**

The mainstream database supports max_n show below:

timescaledb
https://docs.timescale.com/api/latest/hyperfunctions/minimum-and-maximum/max_n/

**Comment by guojidan** [comment]
assign me :)

**Comment by yukkit** [comment]
use order by limit, close
