### ISSUE TITLE
negative ttl error message is not clear

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1399]
version: bae0cd09f1a0adf1849000d13909d296930ef379
sql: `alter database db set ttl '-365d';`
error:
`422 Unprocessable Entity, details: {"error_code":"010009","error_message":"sql parser error: -365d is not a valid precision, use like 'ms', 'us', 'ns'"}`
this error message ls not clear, i think the error message should tell user that why ttl can not be negative

**Comment by Subsegment** [comment]
https://github.com/cnosdb/cnosdb/pull/1595
