### ISSUE TITLE
[DISSCUSE] Configuration files and default items

### ISSUE THREAD

**Issue by IvanGao01** [cnosdb/cnosdb#1410]
### Catalog Usage Specification: 
| directory      |  description                                         |
| ---------------|  ----------------------------------------------------|
| /usr/bin       |  Application storage location                        |
| /etc/cnosdb    |  configuration file location                         |
| /usr/lib/cnosdb|  Library file location                               |
| /var/lib/cnosdb|  Location of data files generated by the application.|
| /var/log/cnosdb|  Log file storage location                           |
| /tmp/cnosdb    |  Temporary file storage location                     |
| /usr/share     |  Shared file storage location                        |

### default port number:

| port | description|
| -----| -----------|
| 8901  |  meta port|
| 8902  |  http port|
| 8903  |  grpc port|
| 8904  |  flight sql rpc port|
| 8905  |  tcp port|

###  Configure the rules in effect

The default configuration files (cnosdb.conf, cnosdb-meta.conf) work in conjunction with the environment variables; if you comment out the configuration options in the configuration files, the system will use their default settings

#### Configuration file priority:
1. environment variables(Environment variables will override uncommented configuration files)
2. Specify the file location
3. /etc/cnosdb/
4. $HOME/cnosdb/

**Comment by zipper-meng** [comment]
- Programs installed by user usually be placed at `/usr/local/bin/`
- `cnosdb` is also a binary program in the CnosDB package, could you make it easy to distinguish with the directory name such as:
   - `/usr/bin/cnosdb/`
   - `/usr/lib/cnosdb`

**Comment by IvanGao01** [comment]
目前二进制文件的安装位置为 `/usr/bin` 下

**Comment by IvanGao01** [comment]
The binaries are currently installed under `/usr/bin`.
`/usr/lib/cnosdb` is where the library files are installed.

**Comment by roseboy-liu** [comment]
> * /etc/cnosdb/
> * $HOME/cnosdb/

/etc/cnosdb/ is the default path.
$HOME/cnosdb/  What does this path do?

**Comment by bartliu827** [comment]
1. environment variables(Environment variables will override uncommented configuration files)
2. Specify the file location
3. /etc/cnosdb/

/etc/cnosdb/cnosdb.conf is the default config file.
If no configuration file is specified, the default configuration file will be used. If the configuration file does not exist, the startup will failed.

**Comment by Benxiaohai001** [comment]
done
