### ISSUE TITLE
[Featrue] Implement flink-connector-cnosdb

### ISSUE THREAD

**Issue by ZuoTiJia** [cnosdb/cnosdb#1411]
- [x] [Code](https://github.com/cnosdb/bahir-flink/tree/cnosdb/flink-connector-cnosdb)
- [x] Doc
- [x] Migrate rep from `cnosdb/flink-bahir` to `cnosdb/flink-connector-cnosdb`
- [x] Create Maven Issue https://issues.sonatype.org/browse/OSSRH-94041
- [x] publish at https://s01.oss.sonatype.org/content/repositories/snapshots/com/cnosdb/flink-connector-cnosdb/
- [ ] Publish

**Comment by roseboy-liu** [comment]
done

**Comment by ZuoTiJia** [comment]
https://mvnrepository.com/artifact/com.cnosdb/flink-connector-cnosdb
