### ISSUE TITLE
[Bug] User meta is inconsistent on multiple meta nodes

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#1416]
**Is your feature request related to a problem? Please describe.**

In a cluster of multiple meta nodes, after a user is created, the id of the same user recorded in each meta is inconsistent

**Describe the solution you'd like**

The user id is generated on the meta side, and each meta executes the logic of creating a user once, resulting in inconsistent idsof the same user on each meta.

Move the user id generation logic to the query side.

**Describe alternatives you've considered**

**Additional context**

**Comment by Benxiaohai001** [comment]
The issue was fixed;verify version:cnosdb 2.3.2, revision 9a4873ae9606cc243e2bc224c0b7d9739d3fc811
```log
create user test;
curl http://127.0.0.1:8901/debug
.../cluster_xxx/users/test: {"id":243883770867672158098990759895736010123,"name":"test","options":{"hash_password":null,"must_change_password":false,"granted_admin":false},"is_admin":false}...
curl http://127.0.0.1:8911/debug
.../cluster_xxx/users/test: {"id":243883770867672158098990759895736010123,"name":"test","options":{"hash_password":null,"must_change_password":false,"granted_admin":false},"is_admin":false}...
```
