### ISSUE TITLE
[Bug] Can not write when data node disk full

### ISSUE THREAD

**Issue by Kree0** [cnosdb/cnosdb#1433]
### Describe the bug

I use `run_cluster.sh` to start the cluster, and put two data nodes in separated disks. Then I make one node's disk full, and use REST API write data to another node, it failed. DB has two replica.

Error Code:
`{"error_code":"020000","error_message":"Unable to write file '/data/cnosdb/wal/_000001.wal': No space left on device (os error 28)"}`

### To Reproduce

Run `run_cluster.sh` to start the cluster(3meta + 2tskv) and make the two tskv nodes in separated disks.

Create DB:
`create database db1 with replica 2;`

Start writing data per 1s(to tskv0), writing data use below command:
`curl -s -XPOST -u 'root:' 'http://127.0.0.1:8902/api/v1/write?db=db1' -d 'ma,ta=a fa={count}'`

Wait 20s and then make tskv1's disk full:
`dd if=/dev/zero of=5G bs=1G count=5`

Subsequent data writes will fail,(the curl command return error).

### Additional context

Version:
cnosdb 2.3.2, revision 83cdc7207602b25f11d47bb5645832210f522cd7 (enterprise)

**Comment by bartliu827** [comment]
That's how the system design is. When the disk is full,return error to user.
