### ISSUE TITLE
storage and computation split cluster(in k8s), query error

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1444]
### Describe the bug

version: 023d539602b65e9c0346994a3d6b66860d95870b
model: 1meta+1query+1tskv
k8s namespace: [cnosdb-community-latest-1meta-1query-1tskv](https://kubesphere.teleport.cnosdb.com/clusters/default/projects/cnosdb-community-latest-1meta-1query-1tskv)
test command:

> cargo run --package test -- --thread 1 --query-url http://10.233.95.250:8902 --storage-url http://10.233.116.121:8902 --pattern between

sql:

> SELECT m2.f0 FROM m2 WHERE CAST(0 AS STRING) BETWEEN (CAST( starts_with(m2.t0, m2.t1) AS STRING)) AND (m2.t1);

error info:

> {"error_code":"010001","error_message":"Datafusion: External error: External error: kv instance not found: node_id:1000"}

**Comment by Subsegment** [comment]
config file node basic node id may same
