### ISSUE TITLE
Node failure causes write failure

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1449]
### Describe the bug

version: dea977068aa93b3bbf130ace7c4ebeaa484b8402
mode: 3+2(k8s)

> CREATE DATABASE db5 WITH replica 1;

Write one data per second to **tskv-0**:

> curl -s -XPOST -u 'root:' 'http://{tskv0_ip}:8902/api/v1/write?db=db5' -d 'ma,ta=a fa={count}'

After 10 seconds of writing, inject DISK-FULL or IO-ERROR fault into **tskv-1**
when inject DISK-FULL fault, error info:

> {"error_code":"020000","error_message":"Unable to write file '/data/cnosdb/wal/_000001.wal': No space left on device (os error 28)"}

when inject IO-ERROR fault, error info:

> {"error_code":"020000","error_message":"Unable to write file '/data/cnosdb/wal/_000001.wal': Input/output error (os error 5)"}

### Expected behavior

In my opinion, when the number of available nodes is greater than or equal to the number of replicas, the write should work fine

**Comment by bartliu827** [comment]
1. Disk capacity early warning
2. Provide a bucket failover mechanism

Temporarily unresolved

**Comment by bartliu827** [comment]
In the further in leader replication model, the hinted handoff mode will be removed.when write leader failed response user failed.
