### ISSUE TITLE
[Bug] fail to insert table

### ISSUE THREAD

**Issue by Kree0** [cnosdb/cnosdb#1459]
### Describe the bug

Version: cnosdb 2.3.2, revision ffeeadf37340d011eab8ecf5a8c1afbd54a98d48

### To Reproduce

cnosdb-cli
```
CREATE TENANT tenant_a;
CREATE USER user_a;
ALTER TENANT tenant_a ADD USER user_a AS owner;
```

cnosdb-cli -u user_a -t tenant_a:
```
CREATE DATABASE db_a;
\c db_a
CREATE TABLE air_a (visibility DOUBLE,temperature DOUBLE,pressure DOUBLE,TAGS(station));
INSERT INTO air_a (TIME, station, visibility, temperature, pressure) VALUES(1666165200290401000, 'XiaoMaiDao', 56, 69, 77);
```

cnosdb_cli:
```
DROP TENANT IF EXISTS tenant_a;
DROP USER IF EXISTS user_a;
CREATE TENANT tenant_a;
CREATE USER user_a;
ALTER TENANT tenant_a ADD USER user_a AS owner;
```

cnosdb-cli -u user_a -t tenant_a:
```
CREATE DATABASE db_a;
\c db_a
CREATE TABLE air_a (visibility DOUBLE,temperature DOUBLE,pressure DOUBLE,TAGS(station));
INSERT INTO air_a (TIME, station, visibility, temperature, pressure) VALUES(1666165200290401000, 'XiaoMaiDao', 56, 69, 77);
```

Show error:
```
422 Unprocessable Entity, details: {"error_code":"020004","error_message":"DataSchemaError: database 'db_a' not found"}
```

**Comment by Subsegment** [comment]
TenantMetaData version is 29 On 
https://github.com/cnosdb/cnosdb/blob/ec1e9a57bbb5a0657a0636fa06c60ba72f43e376/query_server/query/src/metadata/base_table.rs#L40-L44
but version is 16 On
https://github.com/cnosdb/cnosdb/blob/ec1e9a57bbb5a0657a0636fa06c60ba72f43e376/tskv/src/schema/schemas.rs#L53-L58

**Comment by Subsegment** [comment]
maybe meta watch latency issues

**Comment by bartliu827** [comment]
It should have been fixed, I cannot reproduce it.
