### ISSUE TITLE
[Bug] panic when restarting database

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#1462]
### Describe the bug

The application panicked (crashed) when restarting database

### To Reproduce

```
# start CnosDB
cargo run -- run --deployment-mode singleton --config ./config/config_8902.toml

# run test
cargo run --package test

# kill CnosDB after completing the test

# restart CnosDB
cargo run -- run --deployment-mode singleton --config ./config/config_8902.toml
```

**Exception**

```
2023-08-30T10:16:12.453348000+08:00  INFO tskv::kvcore: Recover: delete table, tenant: cnosdb, database: public, table: test
2023-08-30T10:16:12.453394000+08:00  INFO tskv::kvcore: Drop table: deleting 8 columns in table: cnosdb.public.test
2023-08-30T10:16:12.453726000+08:00  INFO tskv::kvcore: Drop table: vnode 24 deleting 40 fields in table: cnosdb.public.test
2023-08-30T10:16:12.453757000+08:00  INFO tskv::kvcore: Drop table: vnode 21 deleting 8 fields in table: cnosdb.public.test
2023-08-30T10:16:12.453905000+08:00 ERROR tskv::memcache: column fa not found in schema
2023-08-30T10:16:12.453919000+08:00 ERROR tskv::memcache: column fb not found in schema
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: InvalidPoint
Location: /Users/yukkit/VCWorkspace/cnosdb/tskv/src/kvcore.rs:230

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### Additional context

branch: cnosdb/main
commit id: 4c654f60

**Comment by Subsegment** [comment]
same as #1400

**Comment by Subsegment** [comment]
> I meet the same problem in test case e2e_test/restart_tests.rs:
> 
> ```
> # start CnosDB
> cargo run -- run -M singleton --config ./config/config_8902.toml
> 
> # run
> curl -f -u 'root:' -XPOST 'http://127.0.0.1:8902/api/v1/sql?db=public' -d "CREATE TABLE air (visibility DOUBLE, temperature DOUBLE, pressure DOUBLE, TAGS(station))"
> 
> # kill CnosDB
> 
> # restart CnosDB
> cargo run -- run -M singleton --config ./config/config_8902.toml
> ```
> 
> Show error:
> 
> ```
> The application panicked (crashed).
> Message:  called `Result::unwrap()` on an `Err` value: MetaClientErr { msg: "NetworkError: reqwest::error::Error: error sending request for url (http://127.0.0.1:8901/read): error trying to connect: tcp connect error: Connection refused (os error 61) source: error trying to connect: tcp connect error: Connection refused (os error 61) source: tcp connect error: Connection refused (os error 61) source: Connection refused (os error 61)" }
> Location: /Users/kree/Code/Rust/cnosdb-enterprise/meta/src/model/meta_admin.rs:113
> ```

These two are not the same issue, we can open a new issue

**Comment by Subsegment** [comment]
https://github.com/cnosdb/cnosdb/pull/1570

**Comment by Benxiaohai001** [comment]
env：
OS：Darwin xxx-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64
version：cnosdb 2.3.2, revision a93a6aec0c4b5fd4a315252fc2fc32527e55a0ce
mode：singleton
the bug was fixed,close the issue.
