### ISSUE TITLE
Support canceling query tasks on tskv

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#1486]
**Is your feature request related to a problem? Please describe.**

Currently, in the storage and calculation separation mode, the query node obtains a stream through gRPC call to read the data on tskv [query_record_batch](https://github.com/cnosdb/cnosdb/blob/414a49e10569adc5a6de13bce27ecb0c14e00cc0/common/protos/src/generated/protobuf_generated/kv_service.rs#L424)

When the stream is canceled, the server cannot perceive it, resulting in the task on tskv still existing and occupying resources

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yukkit** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/28214641/d86e69a7-f09e-474b-9408-641c8bfce5b4)

According to the above figure, a limit sql is executed. When `RowIterator` dropped, `SeriesGroupRowIterator` is still executing. This needs to be solved.

**Comment by Benxiaohai001** [comment]
version : cnosdb 2.3.2, revision 98531cafd1e8fd13f53f4f93050f9b9960e9fe05
the issue was verify, the bug was fixed.
