### ISSUE TITLE
[Bug] drop column delete wrong data

### ISSUE THREAD

**Issue by Subsegment** [cnosdb/cnosdb#1490]
### Describe the bug

https://github.com/cnosdb/cnosdb/blob/414a49e10569adc5a6de13bce27ecb0c14e00cc0/tskv/src/kvcore.rs#L572-L575

This part of the code doesn't taste good，we can delete it

**Comment by Benxiaohai001** [comment]
#1538
version ec1e9a57bbb5a0657a0636fa06c60ba72f43e376
