### ISSUE TITLE
[Bug] e2e_test/flight_sql.rs failed

### ISSUE THREAD

**Issue by Kree0** [cnosdb/cnosdb#1495]
### Describe the bug

When running the entire file test(`cargo test --package e2e_test --lib -- flight_sql`), flight_sql has a probability of failure(change statements are not detected by subsequent query statements), but running one test case in the file alone will not fail.

CnosDB Version: cnosdb 2.3.2, revision 4e6bbdcc9144d4a69884cccdae197f2544d4fcc7
Mode: singleton

**Comment by ZuoTiJia** [comment]
This seems to be due to the delay of the watch mechanism. The data node does not seem to be processing the watch log from itself.

**Comment by ZuoTiJia** [comment]
mybe similar with https://github.com/cnosdb/cnosdb/issues/1401

**Comment by ZuoTiJia** [comment]
because of #1530

**Comment by bartliu827** [comment]
Single instance services, meta services do not follow the raft protocol, and concurrent writes result in duplicate version numbers, resulting in data synchronization issues

**Comment by civi1007** [comment]
This issue has been resolved.
