### ISSUE TITLE
[Feature] Add config for error handle

### ISSUE THREAD

**Issue by Subsegment** [cnosdb/cnosdb#1499]
### Describe the bug

https://github.com/cnosdb/cnosdb/blob/38f0f7adb14c44405b3a09119089076dd2b78ee6/tskv/src/index/ts_index.rs#L726-L735

When some errors occur in our background thread, which obviously cannot be handled, we can consider adding a configuration. There are two cases
1. When an error occurs, log it and ignore it
2. When an error occurs, log the error and send an interrupt signal to stop the process

**Comment by roseboy-liu** [comment]
https://github.com/rust-lang/book/blob/main/src/ch09-00-error-handling.md
