### ISSUE TITLE
[Bug] Invalid password setting

### ISSUE THREAD

**Issue by Kree0** [cnosdb/cnosdb#1501]
### Describe the bug

CnosDB version: cnosdb 2.3.2, revision 4e6bbdcc9144d4a69884cccdae197f2544d4fcc7
Mode: singleton

### To Reproduce

1. Set config file `auth_enabled = false` and start cnosdb

2. Login consdb-cli as root, change password:
```
ALTER USER root SET PASSWORD = 'aaa';
```
3. Restart cnosdb, with config file setting `auth_enabled = true`

4. Login consdb-cli as root without password, it still managed to log in.

**Comment by yukkit** [comment]
similar with #1401

**Comment by Benxiaohai001** [comment]
the bug was fixed,close the issue.
```log
➜  cnosdb git:(main) ✗ cnosdb-cli
CnosDB CLI v2.2.0
Input arguments: Args { host: "localhost", port: 8902, user: "root", password: None, database: "public", tenant: "cnosdb", target_partitions: None, stream_trigger_interval: None, data_path: None, file: [], rc: None, format: Table, quiet: false, write_line_protocol: None, precision: None }
public ❯ show databases;
422 Unprocessable Entity, details: {"error_code":"010016","error_message":"Auth error: Access denied for user 'root' (using password) incorrect password attempt."}
public ❯ 
```
env：
OS：Darwin xxx-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64
version：cnosdb 2.3.2, revision a93a6aec0c4b5fd4a315252fc2fc32527e55a0ce
mode：singleton
