### ISSUE TITLE
[Bug] tiered storage not work

### ISSUE THREAD

**Issue by Kree0** [cnosdb/cnosdb#1526]
### Describe the bug

Version: cnosdb 2.3.2, revision 23edba56b477053a079a00c362c76c582b13d7e4
Mode: 3meta + 2data

### To Reproduce

1. Change 3 meta's config file: set `auto_migrate_vnodes_duration = 60`

2. Start the cluster by running `run_cluster.sh`.

3. Cnosdb-cli:
```
public ❯ ALTER NODE 1001 ATTRIBUTE COLD;
Query took 0.024 seconds.
public ❯ CREATE DATABASE db1 WITH VNODE_DURATION '1m' COOLING_DURATION '1m';
Query took 0.021 seconds.
```

4. run `curl -u 'root:' -XPOST 'http://127.0.0.1:8902/api/v1/write?db=db1' -d 'ma,ta=a fa=1'`

### Expected behavior

After step 4, I can find vnode in `/tmp/cnosdb/2001/db/data/cnosdb.db1`.
After waiting for a while, it should be able to see the vnode migrated to 1001, but the vnode is still at 2001.

**Comment by lutengda** [comment]
this problem be solved, this issue close
