### ISSUE TITLE
[Bug] database attribute invalid

### ISSUE THREAD

**Issue by Kree0** [cnosdb/cnosdb#1532]
### Describe the bug

Cnosdb version: `enterprise LTS/2.3 branch` cnosdb 2.3.2, revision 6b8e41a902186e26846bf37d1d52f66ff5acd2bc
Mode: 3meta + 2data
```
{"error_code":"050001","error_message":"Meta request error: database public attribute invalid!"}
```

### To Reproduce

Run cnosdb cluster by `run_cluster.sh`.

Command Line:
```
curl -f -u 'root:' -XPOST 'http://127.0.0.1:8902/api/v1/sql?db=public' -d 'CREATE TABLE air (visibility DOUBLE, temperature DOUBLE, pressure DOUBLE, TAGS(station))'

curl -f -u 'root:' -XPOST 'http://127.0.0.1:8902/api/v1/sql?db=public' -d "INSERT INTO air (time, station, visibility, temperature, pressure) VALUES ('2023-01-01 01:10:00', 'XiaoMaiDao', 79, 80, 63)"
```

The second curl command has a probability of producing the above error.

**Comment by yukkit** [comment]
This is because the data node has not been started and has not yet been registered to the meta node, resulting in an error when checking the number of vnode replicas.

**Comment by yukkit** [comment]
@Benxiaohai001 @lutengda I remember that this problem occurred before, and adjusted the startup script to ensure that the data node started completely.

**Comment by Benxiaohai001** [comment]
There seems to have been a similar problem before. You can add some waiting time and observe later.

**Comment by yukkit** [comment]
@Kree0  You can check whether the data node node is registered to meta through `curl http://{host}:{port}/debug`

**Comment by ZuoTiJia** [comment]
It seems that the status of the node is not reported immediately when adding the node, causing meta to think that the node is invalid.

https://github.com/cnosdb/cnosdb/blob/8385020cb747a29772d422ff1d9e764f90c3278c/main/src/server.rs#L119-L129


change to 
```
async fn regular_report_node_metrics(meta: MetaRef, heartbeat_interval: u64) { 
     let mut interval = time::interval(Duration::from_secs(heartbeat_interval)); 
     if let Err(e) = meta.report_node_metrics().await { 
             error!("{}", e); 
     } 
     loop { 
         interval.tick().await; 
  
         if let Err(e) = meta.report_node_metrics().await { 
             error!("{}", e); 
         } 
     } 
 } 
```
