### ISSUE TITLE
[Improve] Optimize wal content

### ISSUE THREAD

**Issue by Subsegment** [cnosdb/cnosdb#1566]
**Is your feature request related to a problem? Please describe.**
When wal is not divided according to vnode, we do not know which tenant, db, and vnode a piece of wal data belongs to, but after splitting wal, we can remove the database name and tenant name recorded in wal for each piece of data

https://github.com/cnosdb/cnosdb/blob/ec1e9a57bbb5a0657a0636fa06c60ba72f43e376/tskv/src/kvcore.rs#L590-L597

we can remove tenant and db_name

**Comment by zipper-meng** [comment]
In the latest version v2.4.1, these fields are contained in write request, the method to write WAL data is very simple.

And in the LTS version v2.3, WAL only stores flatbuffers_data so the method has a lot of arguments, this improve may be moved to milestone of 2.3.
