### ISSUE TITLE
[Bug] e2e_test/chaos_tests.rs failed

### ISSUE THREAD

**Issue by Kree0** [cnosdb/cnosdb#1603]
### Describe the bug

Test case description:

Start 3data+2meta by running `run_cluster.sh`.
Start 1 thread write 1 line data per 10 milliseconds.
Randomly choose several ops from `move_vnode, alter_replica, alter_shard, alter_vnode_duration` to perform per 1s, and combine with restart 1 data node per 5s.
After 120s, check whether the number of written data is consistent.

To enable this test case, comment `#[cfg(feature = "not_passed")]` on e2e_test/src/independent/mod.rs: `mod chaos_tests;`.

**Comment by bartliu827** [comment]
测试用例本身在统计条数时有问题，有可能响应失败也计算在内；
如果把不断重启部分逻辑注释掉，则正常。
