### ISSUE TITLE
数据库当中最少需要保留一个保留策略

### ISSUE THREAD

**Issue by IvanGao01** [cnosdb/cnosdb#163]

**Comment by bartliu827** [comment]
autogen policy not permit to delete?

**Comment by QuenKar** [comment]
But data bind with retention policy，so if the last rp can't be removed that the data in this retention policy can't be deleted,.If we want to delete it, we must create a new retention policy  instead(this rp is unused,just for delete the old one).I think this operation is redundant.

**Comment by bartliu827** [comment]
Don't permit  to delete  default retention policy, if you want to delete a default RP.first please create or modify a PR to default
