### ISSUE TITLE
[Feature] Detect unused WALs in singleton Vnodes then delete them

### ISSUE THREAD

**Issue by zipper-meng** [cnosdb/cnosdb#1645]
**Is your feature request related to a problem? Please describe.**

Yes, now if a Vnode not runs in RAFT mode (not in replication group), unused WAL files (seq_no less than version.last_seq) has no trigger to delete.

**Describe the solution you'd like**

Add the way in Vnode to get whether it is in a replication group, if not, delete unused WALs when it triggered to roll.

**Comment by bartliu827** [comment]
https://github.com/cnosdb/cnosdb/pull/1771

**Comment by bartliu827** [comment]
done
