### ISSUE TITLE
[BUG]After disk space is released, disk_free cannot provide timely feedback on the latest remaining space.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1681]
### Describe the bug

After disk space is released, disk_free cannot provide timely feedback on the latest remaining space.
```log
[root@meta3 distributed-sandbox]# cnosdb-cli -P 11102
CnosDB CLI v2.3.0
Input arguments: Args { host: "localhost", port: 11102, user: "root", password: None, private_key_path: None, database: "public", tenant: "cnosdb", target_partitions: None, stream_trigger_interval: None, data_path: None, file: [], rc: None, format: Table, quiet: false, write_line_protocol: None, precision: None }
public ❯ show databases;
+--------------------+
| database_name      |
+--------------------+
| benchmark          |
| cnosdb_admin_stats |
| public             |
| usage_schema       |
+--------------------+
Query took 0.005 seconds.
public ❯ show datanodes;
+---------+--------------------------------+-----------+-------------+-----------+---------------------+
| NODE_ID | HOST                           | ATTRIBUTE | STATUS      | DISK_FREE | LAST_UPDATED_TIME   |
+---------+--------------------------------+-----------+-------------+-----------+---------------------+
| 4       | dfentds.query_tskv1.cnosdb.com | HOT       | UNREACHABLE | 774.76 GB | 2023-10-23 02:16:39 |
| 5       | dfentds.query_tskv2.cnosdb.com | HOT       | NODISKSPACE | 20.48 KB  | 2023-10-30 04:17:45 |
| 6       | dfentds.query_tskv3.cnosdb.com | HOT       | NODISKSPACE | 20.48 KB  | 2023-10-30 04:17:45 |
+---------+--------------------------------+-----------+-------------+-----------+---------------------+
Query took 0.004 seconds.
public ❯ 

```
```log
df -h
/dev/xxxx             894G  301G  594G   34% /data1
```
version: cnosdb 2.3.2, revision = 21fc5424dc953e839195b1770ad20ef606970f6b

**Comment by bartliu827** [comment]
[heartbeat]
report_time_interval_secs = 30

**Comment by Benxiaohai001** [comment]
> [heartbeat] report_time_interval_secs = 30
> 
> The default report interval is 30 seconds.

We talked about the check time issue, but after releasing the space for a long time, it still doesn’t work.

**Comment by Benxiaohai001** [comment]
https://github.com/cnosdb/distributed-sandbox

**Comment by lutengda** [comment]
cnosdb 2.3.3, revision ab65765e6851e941f3ff34cbedd4f58f535a76c8
3+2 model
meta config

> snapshot_path
> journal_path

data config

> [storage]
> path

set 3meta and 2data these config in same disk
and then fill up the hard disk space, show datanodes can check 
and then free up hard disk space, but show datanodes check disk still full and meta log can not see heartbeat report

**Comment by bartliu827** [comment]
If the disk is full and the sled cannot function properly after being released, it must be restarted. After 2.4, the meta storage engine was replaced with lmdb.
