### ISSUE TITLE
`make build` failed on macos

### ISSUE THREAD

**Issue by xmh1011** [cnosdb/cnosdb#1682]
### Describe the bug

<img width="1700" alt="image" src="https://github.com/cnosdb/cnosdb/assets/88817514/28e40570-563f-49d0-858b-ec648d5cc4bd">

the file `common/protos/src/generated/mod.rs` has been changed automaticlly since running the command `make build`.
<img width="549" alt="image" src="https://github.com/cnosdb/cnosdb/assets/88817514/f33bb357-e68a-43d5-be65-005da12b0c01">

**Comment by xmh1011** [comment]
手动执行 `brew install protobuf`后成功，所以是否应在文档中加上`brew install protobuf`这一步？

**Comment by yukkit** [comment]
@xmh1011 Thanks a ton for your suggestion, I think it is much needed, it would be better if you could provide a pr for this

**Comment by xmh1011** [comment]
> @xmh1011 Thanks a ton for your suggestion, I think it is much needed, it would be better if you could provide a pr for this

ok, I have provided a pr for this.
