### ISSUE TITLE
It is expected that the backup and recovery function can keep metadata and table data together

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1701]
**Is your feature request related to a problem? Please describe.**
It is expected that the backup and recovery function can keep metadata and table data together.
The current way of storing the two separately is not user-friendly
https://docs.cnosdb.com/zh/latest/manage/backup_restore.html#%E6%A6%82%E8%BF%B0
![image](https://github.com/cnosdb/cnosdb/assets/40594937/75cc5439-d8da-47dc-b0d4-abe7a2ff7685)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bartliu827** [comment]
no longer support
