### ISSUE TITLE
Data types in table structures are expected to be optimized

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1712]
**Is your feature request related to a problem? Please describe.**
Data types in table structures are expected to be optimized
```log
oceanic_station ❯ CREATE STREAM TABLE air_stream(time TIMESTAMP, station STRING, pressure DOUBLE, temperature DOUBLE, visibility DOUBLE) 
    WITH (db = 'oceanic_station', table = 'air', event_time_column = 'time')
    engine = tskv;
Query took 0.005 seconds.
oceanic_station ❯ \d
+-------------------------+
| table_name              |
+-------------------------+
| air                     |
| air_down_sampling_1hour |
| air_stream              |
+-------------------------+
Query took 0.004 seconds.
oceanic_station ❯ describe table air_stream;
+-------------+-----------------------------+-------------+-------------------+
| column_name | data_type                   | column_type | compression_codec |
+-------------+-----------------------------+-------------+-------------------+
| time        | Timestamp(Nanosecond, None) | FIELD       |                   |
| station     | Utf8                        | FIELD       |                   |
| pressure    | Float64                     | FIELD       |                   |
| temperature | Float64                     | FIELD       |                   |
| visibility  | Float64                     | FIELD       |                   |
+-------------+-----------------------------+-------------+-------------------+
Query took 0.002 seconds.
```
As above, we expect the data types in the table structure to be displayed as the several types we specified: BIGINT, BIGINT UNSIGNED, BOOLEAN, TIMESTAMP, STRING, DOUBLE

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yukkit** [comment]
The printing of data types can be modified through https://github.com/cnosdb/cnosdb/blob/a60ca635b35b752d0554465c6c00f1f25869a035/query_server/query/src/metadata/information_schema_provider/factory/columns.rs#L192, but I have not found a more elegant way to implement it.

**Comment by civi1007** [comment]
This issue has been resolved.

public ❯ describe table air_stream;
+-------------+-----------------------+-------------+-------------------+
| column_name | data_type             | column_type | compression_codec |
+-------------+-----------------------+-------------+-------------------+
| time        | TIMESTAMP(NANOSECOND) | TIME        | DEFAULT           |
| station     | STRING                | FIELD       | DEFAULT           |
| pressure    | DOUBLE                | FIELD       | DEFAULT           |
| temperature | DOUBLE                | FIELD       | DEFAULT           |
| visibility  | DOUBLE                | FIELD       | DEFAULT           |
+-------------+-----------------------+-------------+-------------------+
Query took 0.027 seconds.
