### ISSUE TITLE
[BUG]Documentation is inconsistent with implementation

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1713]
### Describe the bug

Documentation is inconsistent with implementation
version:cnosdb 2.4.0, revision c50e379ba32d8f9af380836b2778f85aafde5dbb
1. 
![image](https://github.com/cnosdb/cnosdb/assets/40594937/9fc0cd12-d7fb-4897-ae7e-78d517c7492d)

https://docs.cnosdb.com/zh/latest/reference/sql.html#%E6%B5%81
```log
oceanic_station ❯ CREATE TABLE air (visibility DOUBLE,temperature DOUBLE,pressure DOUBLE,TAGS(station));
Query took 0.006 seconds.
oceanic_station ❯ CREATE STREAM TABLE air_stream(time double, station double, pressure bigint, temperature bigint unsigned, visibility boolean) 
    WITH (db = 'oceanic_station', table = 'air', event_time_column = 'time')
    engine = tskv;

Query took 0.004 seconds.
```
2. 
![image](https://github.com/cnosdb/cnosdb/assets/40594937/c8f9ccb1-00e6-4616-a713-00d636a51551)
```log
oceanic_station ❯ CREATE STREAM TABLE air_stream 
    WITH (db = 'oceanic_station', table = 'air', event_time_column = 'time')
    engine = tskv;
Query took 0.006 seconds.
```

**Comment by civi1007** [comment]
![image](https://github.com/user-attachments/assets/044682cb-00be-4ea7-8674-4096f0c3756f)
The document has been modified
