### ISSUE TITLE
【Feature】Considering routing both write requests and SQL requests to query server.

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#1720]
**Is your feature request related to a problem? Please describe.**
In the current mode of storing and computing separation, all write requests are directly routed to tskv nodes, and SQL requests are routed to query nodes. This approach can be cumbersome for users because it requires configuring two load balancers, one for tskv and one for query, to achieve load balancing.

**Describe the solution you'd like**
Considering routing both write requests and SQL requests to query nodes, and then having the query nodes route the requests to tskv nodes.

**Describe alternatives you've considered**

**Additional context**

**Comment by Benxiaohai001** [comment]
https://github.com/cnosdb/cnosdb/pull/1792
