### ISSUE TITLE
Standardize InformationSchema.queries and show queries

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#1729]
**Is your feature request related to a problem? Please describe.**

Inspired by #1728

**Describe the solution you'd like**

1. Standardize visibility of InformationSchema.queries:
- Then user with admin permissions: can see all queries in the cluster（**New Addition**）
- The tenant owner: see all queries under the current tenant
- Common user: see the SQL executed by themselves under the current tenant

2. Refactor `show queries` into querying system tables
```
query_id, user, query, state, duration
```
->
```
query_id, query_type, query_text, user_name, tenant_name, state, duration
```

**Describe alternatives you've considered**

**Additional context**

**Comment by yukkit** [comment]
Please help evaluate the potential impact of this modification @IvanGao01 @xuegexi

**Comment by xuegexi** [comment]
The admin service uses show queries in one place, so the modification pressure is not high. @yukkit

**Comment by yukkit** [comment]
> The admin service uses show queries in one place, so the modification pressure is not high. @yukkit

This modification takes effect from version 2.4.1

**Comment by Benxiaohai001** [comment]
Issue #1728 related issues have been fixed,close;
version:cnosdb 2.4.2, revision 0ccc869d90e34b39782067dd160f7877e07caebf
