### ISSUE TITLE
Suggested submission go.sum

### ISSUE THREAD

**Issue by kklinan** [cnosdb/cnosdb#173]
**Is your feature request related to a problem? Please describe.**
I see that go.sum is ignored to commit the repository, and the vendor directory does not commit the repository, nor is it ignored to submit the repository. 
May I ask why you decided to do this?

**Describe the solution you'd like**
For the go.sum file Go official recommends submitting it to the repository, please see the official wiki .
[Should I commit my 'go.sum' file as well as my 'go.mod' file?](https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file).

I personally recommend submitting vendor to the repository at the same time to improve the security and stability of the repository code.

**Describe alternatives you've considered**

**Use case**

**Comment by IvanGao01** [comment]
Thank you for telling us the importance of submitting the "go.sum" file, I've seen what this file does, It should be submitted to the repository.
