### ISSUE TITLE
[BUG]There is a problem with creating the tenant syntax description

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1730]
### Describe the bug

https://docs.cnosdb.com/zh/latest/manage/tenant.html#%E5%88%9B%E5%BB%BA%E7%A7%9F%E6%88%B7
```sql
CREATE
TENANT [IF NOT EXISTS] tenant_name WITH [comment = ''/drop_after = '7d'];
```
may be replace as follow:
```sql
CREATE
TENANT [IF NOT EXISTS] tenant_name [WITH comment = ''/drop_after = '7d'];
```

**Comment by Benxiaohai001** [comment]
When creating a tenant, you can directly add the resource restriction part;
modify the doc, please;
```log
public ❯ create tenant test_tenant002 with _limiter = '{
  "object_config": {
    "max_users_number": 1,
    "max_databases": 3,
    "max_shard_number": 2,
    "max_replicate_number": 2,
    "max_retention_time": 30
  },
  "request_config": {
    "data_in": {
      "remote_bucket": {
        "max": 10000,
        "initial": 0,
        "refill": 10000,
        "interval": 100
      },
      "local_bucket": {
        "max": 10000,
        "initial": 0
     }
    },
     "data_out": {
       "remote_bucket": {
       "max": 100,
       "initial": 0,
        "refill": 100,
        "interval": 100
  },
  "local_bucket": {
    "max": 100,
    "initial": 0
  }
  },
  "queries": null,
  "writes": null
  }
}';
```

**Comment by Benxiaohai001** [comment]
There is a problem with the syntax tree   @lutengda
```log
public ❯ create tenant test_tenant002 with drop_after = '7m';
Query took 0.003 seconds.
public ❯ create tenant test_tenant003 with comment = 'test', drop_after = '7m';
Query took 0.003 seconds.
public ❯ 
```

**Comment by Benxiaohai001** [comment]
https://docs.cnosdb.com/zh/latest/manage/tenant.html#%E4%BF%AE%E6%94%B9%E7%A7%9F%E6%88%B7
The alter tenant syntax should add the _limiter part @ZuoTiJia

**Comment by ZuoTiJia** [comment]
https://github.com/cnosdb/docs/pull/215

**Comment by Benxiaohai001** [comment]
drop_after begin 2.4.0
_limiter begin 2.3.4
@IvanGao01 sync docs, please.

**Comment by IvanGao01** [comment]
the `_limiter ` Scope of influence:

| Community| Enterprise |
| --- |--- |
| v2.3.2 |v2.3.2 |
| v2.3.4 |v2.3.4 |
| v2.3.4.1 |skip|
| v2.3.4.2 |skip|
| v2.3.4.3 |skip|
| v2.4.0 |v2.4.0 |

**Comment by lutengda** [comment]
> the `_limiter ` Scope of influence:
> 
> Community	Enterprise
> v2.3.2	v2.3.2
> v2.3.4	v2.3.4
> v2.3.4.1	skip
> v2.3.4.2	skip
> v2.3.4.3	skip
> v2.3.4.4	skip
> v2.4.0	v2.4.0
> `drop_after` does not exist in the known version, waiting for a new release version @lutengda The `drop_after` syntax is not found in version 2.3.4, in which future versions will it be supported?

the 'after' feature not support in 2.3 @IvanGao01

**Comment by IvanGao01** [comment]
@lutengda Please don't close this Issue and let me know when the first Release version supporting this feature is released!

**Comment by paradox0503** [comment]
> @lutengda Please don't close this Issue and let me know when the first Release version supporting this feature is released!

Version 2.4.2 now supports drop_after and _limiter.
