### ISSUE TITLE
WAL files not being deleted

### ISSUE THREAD

**Issue by fredrikIOT** [cnosdb/cnosdb#1738]
### Describe the bug

The Write-Ahead Logging (WAL) files are not being purged as expected within the CnosDB database. These WAL files are consuming a significant amount of disk space. It's anticipated that these files should be unnecessary and safe to delete after a certain period when the logs have been committed to TSM files.

### To Reproduce

1. Run the database in standalone mode using the command `cnosdb run -M singleton`.
2. Ensure the configuration is set to its default parameters.
3. Perform data insertion operations continuously.
4. Observe the WAL directory size over a period of 7 days.
5. Note that disk space used by WAL files increases linearly and files are not being deleted automatically.

### Expected behavior

The WAL files should be automatically purged after their data has been written to the TSM files to prevent uncontrolled disk space usage. There should be a mechanism, such as a scheduled task or a threshold-based trigger, that ensures WAL files are deleted after they are no longer necessary.

### Additional context

I am running docker with this image: **cnosdb/cnosdb:community-2023-11-09**

**Comment by yukkit** [comment]
Thank you @fredrikIOT for a nice reproducer and your suggestion.

**Comment by fredrikIOT** [comment]
This seems to be fixed by [this](https://github.com/cnosdb/cnosdb/pull/1771) pull request
