### ISSUE TITLE
[Test] Migrate tests to sqllogicaltest

### ISSUE THREAD

**Issue by ZuoTiJia** [cnosdb/cnosdb#1746]
**Is your feature request related to a problem? Please describe.**
Now we have two sets of test frameworks, one located at `query_server/test` and one located at `query_server/sqllogicaltest`. The test cases of sqlogicaltest are easier to change and read, so they can be migrated to sqllogicaltest.

**Describe the solution you'd like**
- [ ] extend sqllogicaltest function
- [ ] migrate tests

**Comment by Benxiaohai001** [comment]
Done
