### ISSUE TITLE
[BUG]Node 2001 failover during data import

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1758]
### Describe the bug

env：64 cpu， 256 mem
mode: 3meta+ 2tskv
version:cnosdb 2.3.0, revision 03599af024591a192b61128835996307cfbd4e99
tenant 1 db 1 ,shard 48
cat cnodb-iot-seed-123-scale-100-2016.gz|gunzip | load_cnosdb --urls='http://127.0.0.1:8902' --workers 100 --batch-size 20000
about 4-5 minutes later,
```log
Error writing: [DebugInfo: worker #86, dest url: http://127.0.0.1:8902] Invalid write response (status 422): {"error_code":"050016","error_message":"Node failover: 2001, error: Status { code: Unknown, message: \"request timed out\", source: Some(Elapsed(())) }"}
```
monitor:    https://xxx/d/rYdddlPWk1/node-exporter-full?orgId=1&var-DS_PROMETHEUS=Prometheus-192.168.0.24-docker&var-job=192.168.0.23&var-node=192.168.0.23:9100&var-diskdevices=%5Ba-z%5D%2B%7Cnvme%5B0-9%5D%2Bn%5B0-9%5D%2B%7Cmmcblk%5B0-9%5D%2B&from=1700017200000&to=1700017560000
<img width="1366" alt="image" src="https://github.com/cnosdb/cnosdb/assets/40594937/a06dbed2-f8e9-4542-a20a-68c95bc3e90a">

**Comment by bartliu827** [comment]
Forwarding failure due to exceeding network bandwidth

**Comment by Benxiaohai001** [comment]
After many tests, I found that this situation occurs under high pressure situations. As mentioned above, it is a network and bandwidth problem. Therefore, no repair is made and the issue is closed.
