### ISSUE TITLE
Tables named with uppercase letters cannot be queried.

### ISSUE THREAD

**Issue by IvanGao01** [cnosdb/cnosdb#1763]
### Describe the bug

Tables named with uppercase letters cannot be queried.

### To Reproduce

1. Write to TEST table
```shell
curl -i -u "root:" -H "Accept: application/json" \
-XPOST "http://127.0.0.1:8902/api/v1/write?db=public" \
-d "TEST,station=XiaoMaiDao visibility=50,temperature=63,pressure=52 1642176000000000000"
```
2. Query TEST table
```
curl -i -u "root:" -H "Accept: application/json" \
-XPOST "http://127.0.0.1:8902/api/v1/sql?db=public" \
-d "SELECT * FROM TEST"
```
result：
```
{"error_code":"010001","error_message":"Datafusion: Error during planning: Table not found, tenant: cnosdb db: public, table: test"}%
```

### Additional context

cnosdb 2.4.0, revision 38427b2a1559de04db87bc5f6cb7af54371c62b5

**Comment by yukkit** [comment]
**The current behavior is as expected.**

**In standard SQL**
Database object names are uniformly converted to (lowercase/uppercase) when not enclosed in quotes（aka case-insensitive). To achieve case sensitivity, quotes must be used.

**lineprotocol**
The measurement name. InfluxDB accepts one measurement per point. Measurement names are **case-sensitive** and subject to naming restrictions.

See https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/

**Comment by roseboy-liu** [comment]
done
