### ISSUE TITLE
[BUG]After the role is deleted, the binding relationship with the user is not deleted.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1767]
### Describe the bug

After the role is deleted, the binding relationship with the user is not deleted.

### To Reproduce

```log
# u001
t001rootdb001 ❯ create role rm001 inherit member;
Query took 0.004 seconds.
t001rootdb001 ❯ select * from information_schema.roles;
+-----------+-----------+--------------+
| role_name | role_type | inherit_role |
+-----------+-----------+--------------+
| owner     | system    |              |
| member    | system    |              |
| rm001     | custom    | member       |
+-----------+-----------+--------------+
Query took 0.002 seconds.
# root
public ❯ alter tenant t001 add user u002 as rm001;
Query took 0.003 seconds.
# u002
public ❯ select * from information_schema.enabled_roles;
+-----------+
| role_name |
+-----------+
| rm001     |
+-----------+
Query took 0.007 seconds.
# u001
t001rootdb001 ❯ drop role rm001;
Query took 0.004 seconds.
# u002
public ❯ select * from information_schema.enabled_roles;
422 Unprocessable Entity, details: {"error_code":"010004","error_message":"Insufficient privileges, expected [Read on database information_schema of tenant 51313256736898270412450157318782159305]"}
# u001
t001rootdb001 ❯ create role rm001 inherit member;
Query took 0.008 seconds.
# u002
public ❯ \d
Query took 0.027 seconds.
public ❯ select * from information_schema.enabled_roles;
+-----------+
| role_name |
+-----------+
| rm001     |
+-----------+
Query took 0.012 seconds.
```

### Expected behavior

After deleting the role, the corresponding relationships will be deleted together.Is it bound by role name in our system? I think it would be better to use ID for binding?

**Comment by yukkit** [comment]
在CnosDB中：

1. 在将用户添加到指定租户下时，需要同时分配特定角色。这些角色包括系统角色和用户自定义角色。

2. 租户成员和其角色之间的关系是通过名称进行维护。

3. 当删除角色时，对应角色的租户成员的权限会被同时撤销。然而，租户成员和其角色之间的绑定关系不会同步删除（即仅角色会失效）。

不使用ID进行绑定的考虑是基于以下情景：小组成员拥有相同的角色。当小组内部职能发生变动，需要修改权限时，只需修改角色或者删除重建角色，而不必对所有成员进行修改。

**需要同步到Cnosdb文档 https://docs.cnosdb.com/**

**Comment by ZuoTiJia** [comment]
https://github.com/cnosdb/docs/pull/216

**Comment by Benxiaohai001** [comment]
https://docs.cnosdb.com/zh/latest/manage/tenant.html#%E5%88%A0%E9%99%A4%E8%A7%92%E8%89%B2
as the lastest version office docs, Remarks are made to address the above problems
![image](https://github.com/cnosdb/cnosdb/assets/40594937/810f2c88-553f-47de-83ea-e6e4a4f25a2a)
