### ISSUE TITLE
[DOISSCUSS]“key=value” or “key value” or both of them？

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1775]
**Describe the issue**
A clear and concise description of issue.
In the current environment, we set an attribute in two ways: key value or key=value. But you can only use one of them.
as follow:
```log
public ❯ create database db002 with ttl '2d';
Query took 0.003 seconds.
public ❯ alter tenant t_002 drop_after '2d';
422 Unprocessable Entity, details: {"error_code":"010009","error_message":"sql parser error: Expected ADD, REMOVE, SET, UNSET, found: drop_after"}
public ❯ alter tenant t_002 set drop_after '2d';
422 Unprocessable Entity, details: {"error_code":"010009","error_message":"sql parser error: Expected =, found: '2d'"}
public ❯ alter tenant t_002 set drop_after='2d';
Query took 0.004 seconds.
public ❯ create tenant t_004 with drop_after '2d';
422 Unprocessable Entity, details: {"error_code":"010009","error_message":"sql parser error: Expected =, found: '2d'"}
public ❯ create tenant t_004 with drop_after='2d';
Query took 0.003 seconds.
public ❯ create database db003 with ttl='2d';
422 Unprocessable Entity, details: {"error_code":"010009","error_message":"sql parser error: Expected a value, found: ="}
public ❯ 
```
Are there any special considerations for this different setup? If there are no special requirements, it is recommended that we support both settings at the same time, which will make it more convenient to use. What do you think?

**What you like us to do**
Please give us some advices

**Additional context**
Add any other context about the issue here.

**Comment by lutengda** [comment]
Do we need to think about colons?

**Comment by lutengda** [comment]
mysql: support space and equal, no colon 
pg: support space and equal, no colon

**Comment by roseboy-liu** [comment]
> mysql: support space and equal, no colon pg: support space and equal, no colon

This is a standard practice.

**Comment by Benxiaohai001** [comment]
The modification covers a wide range of areas, and subsequent automated use cases will be carried out to take care of relevant functions.
