### ISSUE TITLE
implement conv

### ISSUE THREAD

**Issue by wildZooZebra** [cnosdb/cnosdb#1778]
**Describe the issue**
Implement the function conv:

Function name: conv

Input Sequence: only two input sequences are supported, both of type INT32 / INT64 / FLOAT / DOUBLE

Output Sequence: outputs a single sequence, of type DOUBLE, which is the result of the convolution of two sequences. The timestamps of the sequences start at 0 and are only used to indicate order.

Hint: NaN in the input sequence will be ignored.

**Comment by yukkit** [comment]
Thank you @wildZooZebra for your interest in CnosDB and for raising this feature.

To better understand your request, could you provide more details about the "conv" function you mentioned? This will help all of us grasp the issue more accurately and find the best solution. For instance, does the "conv" refer to a convolution operation? If so, what specific functionality are you expecting? Any particular parameters, input/output formats, or additional context you could provide would greatly assist us in comprehending and addressing the issue.
