### ISSUE TITLE
Upgrade q_compress -> pco

### ISSUE THREAD

**Issue by mwlon** [cnosdb/cnosdb#1805]
Hi, I'm the main author of q_compress, and I think cnosdb would benefit from upgrading to my new library, [pco](https://crates.io/crates/pco). Across [various real-world datasets](https://github.com/mwlon/pcodec/tree/4ca9841c9e614659f02e9961fcc81e90894a473b/bench#real-world), it has
* 2-100% higher compression ratio
* 20-50% faster compression
* 300-400% faster decompression

Plus, pco will continue to improve. q_compress will still work, and I'll still maintain it for bug fixes, but limitations in its format prevent it from achieving extremely fast decompression.

Q: If the qco format had limitations that forced you to release a new format after 2 years, how do we know the new format will last?
A: I don't profess to know the future, but I expect pco's format to be state of the art for many years. I consulted an expert in performant compression to help vet the format. I've iterated based on assembly code to make sure pco can use SIMD where possible. And I've carefully made the format extensible to more types of data for future adaptation.

Q: What does the upgrade look like?
A: I see you're using `auto_[de]compress`, and pco has those too! API-wise, the upgrade is trivial. [We have docs if you need them though](https://docs.rs/pco/latest/pco/). And of course, if you have existing .qco data, you'll need to keep using q_compress for decompression until it's ported over. If necessary, you can distinguish standalone .qco data from .pco data by the magic 4 bytes in the header.

**Comment by Subsegment** [comment]
Thank you very much for your issue, it was really helpful and we will apply pco in future updates.

**Comment by roseboy-liu** [comment]
done
