### ISSUE TITLE
[Bug] Try to read freed memory

### ISSUE THREAD

**Issue by zipper-meng** [cnosdb/cnosdb#1819]
### Describe the bug

There is a risk in code here that will try to read freed pointer `Arc<TsmReader>`.

https://github.com/cnosdb/cnosdb/blob/7bc871486f9549bd44f04d2f2493051190b10cd5/tskv/src/tseries_family.rs#L514-L526

### To Reproduce

It already caused some issues: #1561, #1742

### Expected behavior

No panics and never visit already freed memory.

**Comment by Benxiaohai001** [comment]
add auto testcase https://github.com/cnosdb/cnosdb/pull/1820/files#diff-f6e1a03994875e2c3219b680ed0d19f8587a4d06bdb540b69403d9d474d54851
