### ISSUE TITLE
[Feature] Add an API that can judge whether there is permission to write

### ISSUE THREAD

**Issue by Kree0** [cnosdb/cnosdb#1821]
`api/v1/write` write data directly if there is permission to write, for example:
```
curl -f -u 'u1:abc' -XPOST 'http://127.0.0.1:8902/api/v1/write?db=db1&tenant=t1' -d 't1,foo=a,bar=b v=1'
```
If user `u1` with password `abc` has permission to write to database `db1` in tenant `t1`, the above command would write directly.

I hope there is an API that can judge whether there is permission to write, rather than writing directly.

**Comment by lutengda** [comment]
After discussion, it is not necessary to add this feature for now
