### ISSUE TITLE
[optimization][subscription management] ‘any’ in subscription management, it is expected that each request will be sent to a different host.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1838]
### Describe the bug

‘any’ in subscription management, it is expected that each request will be sent to a different host.
The current processing method is to select a host and all subsequent requests will be sent to this node.

**Comment by Benxiaohai001** [comment]
After testing, when each request writes a statement, the data will select a subscription node and keep writing data; when each request writes a lot of data, the data of each request will be sent to other nodes separately due to load balancing. Subscribe to the node.Is this solution acceptable?

**Comment by zipper-meng** [comment]
> After testing, when each request writes a statement, the data will select a subscription node and keep writing data; when each request writes a lot of data, the data of each request will be sent to other nodes separately due to load balancing. Subscribe to the node.Is this solution acceptable?

Like this?
```
                req1───────────────────────┐                req1┐
Node1 ─────────>req2───────────────────────┼───┐         ┌─>req3┼──>Node1
                req3───────────────────────┘   │         │  req5┘
Load balance  =>───────────────────────────────┼─────────┤
                req4───────────────────────┐   │         │  req2┐
Node2 ─────────>req5───────────────────────┼───┘         └─>req4┼──>Node2
                req6───────────────────────┘                req6┘
```

**Comment by Benxiaohai001** [comment]
> > After testing, when each request writes a statement, the data will select a subscription node and keep writing data; when each request writes a lot of data, the data of each request will be sent to other nodes separately due to load balancing. Subscribe to the node.Is this solution acceptable?
> 
> Like this?
> 
> ```
>                 req1───────────────────────┐                req1┐
> Node1 ─────────>req2───────────────────────┼───┐         ┌─>req3┼──>Node1
>                 req3───────────────────────┘   │         │  req5┘
> Load balance  =>───────────────────────────────┼─────────┤
>                 req4───────────────────────┐   │         │  req2┐
> Node2 ─────────>req5───────────────────────┼───┘         └─>req4┼──>Node2
>                 req6───────────────────────┘                req6┘
> ```

@Subsegment Please explain the load balancing strategy.

**Comment by Subsegment** [comment]
I just tried to start three single nodes, subscribed to any, and manually wrote some data, which basically guaranteed an even distribution, I suspect there is a problem with the testing method
