### ISSUE TITLE
[BUG][subscription]There is no subscription information in the prompt information in the show syntax

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1841]
### Describe the bug

There is no subscription information in the prompt information in the show syntax
```log
db001 ❯ show subscriptions on db001;
422 Unprocessable Entity, details: {"error_code":"010009","error_message":"sql parser error: Expected TABLES or DATABASES or SERIES or TAG or QUERIES or STREAMS or DATANODES, found: subscriptions"}
```
version:cnosdb 2.4.0, revision 842fc0e37a28327f14805f7ebe7ca1a85fca721c

**Comment by roseboy-liu** [comment]
`Show subscriptions`  only supported on enterprise edition.

**Comment by Benxiaohai001** [comment]
> `Show subscriptions` only supported on enterprise edition.

I am using the enterprise version. What I am referring to here is: there is no subscription information in the show syntax error return.
The info only contain as follow:
```log
Expected TABLES or DATABASES or SERIES or TAG or QUERIES or STREAMS or DATANODES
```
Addition, It seems that there are no vnode and datanode here either. Make modifications here too.

**Comment by lutengda** [comment]
As the current error message needs to be changed with the feature, I suggest it can be modified to ‘Field not supported: ...’

**Comment by Benxiaohai001** [comment]
```log
public ❯ show des;
422 Unprocessable Entity, details: {"error_code":"010009","error_message":"sql parser error: nonsupport: des"}
```
cnosdb 2.4.0, revision db434d4696e0c58e6881cc89e49cabece0316bff

**Comment by Benxiaohai001** [comment]
waitting sync LTS/2.3, Enterprise Edition 2.4, Enterprise Edition LTS/2.3.

**Comment by roseboy-liu** [comment]
https://github.com/cnosdb/cnosdb-enterprise/pull/211  https://github.com/cnosdb/cnosdb-enterprise/pull/212
