### ISSUE TITLE
[BUG]Non-cnosdb tenants cannot subscribe

### ISSUE THREAD

**Issue by xuegexi** [cnosdb/cnosdb#1854]
### Describe the bug

version 2.3.4/2.3.2
Using the cnosdb tenant, the subscription function can be implemented. However, when using non-cnosdb tenants, such as test, the same configuration cannot implement the subscription function.

**Comment by Subsegment** [comment]
https://github.com/cnosdb/cnosdb-enterprise/pull/171

**Comment by Benxiaohai001** [comment]
As above, the automation use cases have been integrated into the main branch and LTS/2.3.
