### ISSUE TITLE
[bug][backup_restore]The tool cnosdb-imexport enhancement

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1862]
### Describe the bug

The tool cnosdb-imexport lacks help description information
version:cnosdb 2.4.0, revision 842fc0e37a28327f14805f7ebe7ca1a85fca721c

### To Reproduce

<img width="833" alt="image" src="https://github.com/cnosdb/cnosdb/assets/40594937/ddb93cb1-a7f3-4ac8-abf8-03d865816610">

**Comment by bartliu827** [comment]
There is a problem with the return information. When the backup fails, the final result is success.
 cnosdb-enterprise git:(main) ✗ ./target/release/cnosdb-imexport export -s root:@127.0.0.1:8912 --path /xxx/backup/
# Input args: Cli { subcmd: Export(ExportArgs { src: "root:@127.0.0.1:8912", path: "/Users/bichaoxue/Documents/github.com/cnosdb/cnosdb-enterprise/backup/", conn: None }) }
# Begin  export table(cnosdb.public.air)  [Now: 18:37:12]
# Export table(cnosdb.public.air) data: {"error_code":"010001","error_message":"Datafusion: IO error: No such file or directory (os error 2)"}
..............
# Begin  export table(cnosdb.usage_schema.vnode_disk_storage)  [Now: 18:37:12]
# Export table(cnosdb.usage_schema.vnode_disk_storage) data: {"error_code":"010001","error_message":"Datafusion: IO error: No such file or directory (os error 2)"}

# Export  Data: Ok(())

**Comment by Benxiaohai001** [comment]
> Member

import also has same problem:
```log
/target/release/cnosdb-imexport import -d notexist:@127.0.0.1:8912 -p file:///Users/bichaoxue/Documents/github.com/cnosdb/cnosdb-enterprise/backup
# Input args: Cli { subcmd: Import(ImportArgs { path: "file:///Users/bichaoxue/Documents/github.com/cnosdb/cnosdb-enterprise/backup", dst: "notexist:@127.0.0.1:8912", conn: None }) }
# Import meta data success, total: 36

# Begin import table(cnosdb.public.air)  [Now: 14:48:36]
# Import table(cnosdb.public.air) data: {"error_code":"010016","error_message":"Auth error: The user notexist not found"}
...
# Begin import table(t001.db002.wind)  [Now: 14:48:36]
# Import table(t001.db002.wind) data: {"error_code":"010016","error_message":"Auth error: The user notexist not found"}

# Import  Data: Ok(())
```

**Comment by bartliu827** [comment]
no longer support
