### ISSUE TITLE
[BUG][backup_restore][doc]cnosdb-imexport export syntax error

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1864]
### Describe the bug

cnosdb-imexport export syntax error

### To Reproduce

https://docs.cnosdb.com/zh/latest/manage/backup_restore.html#export
latest version:
<img width="1440" alt="image" src="https://github.com/cnosdb/cnosdb/assets/40594937/7c173784-ec3e-4e70-a76b-aaac4cb43584">
```sql
cnosdb-imexport export --src <user>:<password>@<ip>:<port> --path ./backup
```
should replease with :
```sql
cnosdb-imexport export --src <user>:<password>@<ip>:<port> --path file:///backup

```
https://github.com/cnosdb/cnosdb/issues/1862

**Comment by Benxiaohai001** [comment]
<img width="1440" alt="image" src="https://github.com/cnosdb/cnosdb/assets/40594937/e94cb31b-ceb9-4e6c-bb64-49154f791b1e">
How to use the -c option, there is no explanation in the document

**Comment by Benxiaohai001** [comment]
<img width="1440" alt="image" src="https://github.com/cnosdb/cnosdb/assets/40594937/0b643016-5c4c-48ba-8a87-cff1611fcbd2">
import has same problem;

**Comment by Benxiaohai001** [comment]
<img width="1440" alt="image" src="https://github.com/cnosdb/cnosdb/assets/40594937/c007c10b-9e63-468d-b887-ef54aa576ed7">
migrate  has same problem

**Comment by IvanGao01** [comment]
@bartliu827  please help supplement the spelling of 'conn'

**Comment by bartliu827** [comment]
no longer support
