### ISSUE TITLE
[BUG][backup_restore]The current meta data recovery method is unreasonable

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1869]
### Describe the bug

The current meta data recovery method is unreasonable
version:cnosdb 2.4.0, revision 842fc0e37a28327f14805f7ebe7ca1a85fca721c

### To Reproduce

Currently, meta data is restored directly by writing the exported meta data. However, if the name of the cluster is modified, it cannot be written. Moreover, in the actual production environment, it is normal for our different clusters to have different names.
When the cluster names are different, direct migration of data from different clusters will cause the following problems:
```log
➜  cnosdb-enterprise git:(main) ✗ ./target/release/cnosdb-imexport migrate -s root:@127.0.0.1:8902 -d root:@127.0.0.1:8912 -p file:///Users/bichaoxue/Documents/github.com/cnosdb/cnosdb-enterprise/backup
# Input args: Cli { subcmd: Migrate(MigrateArgs { src: "root:@127.0.0.1:8902", dst: "root:@127.0.0.1:8912", path: "file:///Users/bichaoxue/Documents/github.com/cnosdb/cnosdb-enterprise/backup", conn: None }) }
# Migrate meta data success, total: 28

# Begin  export table(cnosdb.public.air); (1.1.1 --> 2.2.3) [Now: 16:31:44]
# Export table(cnosdb.public.air) data: [{"rows":56642}]
# Import table(cnosdb.public.air) data: {"error_code":"010001","error_message":"Datafusion: Error during planning: Table not found, tenant: cnosdb db: public, table: air"}

# Migrate Data: Err("copy table(air) not pass!")
```
It can also be seen from the above error report that the chema data is not written to the new cluster, resulting in the error: Table not found

**Comment by bartliu827** [comment]
no longer support
