### ISSUE TITLE
[BUG][table][alter][doc]Modify table to add field, syntax tree lacks data type

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1878]
### Describe the bug

Modify table to add field, syntax tree lacks data type

### To Reproduce

https://docs.cnosdb.com/zh/latest/reference/sql.html#%E4%BF%AE%E6%94%B9%E8%A1%A8
![image](https://github.com/cnosdb/cnosdb/assets/40594937/d0f473e1-76d2-4845-955d-fefb460e6007)
```log
public ❯ alter table air add FIELD  f001 double;
Query took 0.005 seconds.
```

**Comment by IvanGao01** [comment]
Modified：https://github.com/cnosdb/docs/commit/a7bedbfe769301434bdebc980c204de8c55c00c9
