### ISSUE TITLE
[BUG][doc][copy into]copy into syntax incorrect

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1906]
### Describe the bug

copy into syntax incorrect
https://beta.docs.cnosdb.com/docs/manage/import_export/#%E5%AF%BC%E5%85%A5%E6%95%B0%E6%8D%AE
![image](https://github.com/cnosdb/cnosdb/assets/40594937/92210e21-3238-4060-a3cb-be51752b4b0f)

### To Reproduce

as follow:
```log
public ❯ COPY INTO inner_csv_v2(time, tag1, tag2, bigint_c, string_c, ubigint_c, boolean_c, double_c) FROM 'query_server/test/resource/data_type/csv/full_data_type.csv' file_format = (type = 'csv');
+------+
| rows |
+------+
| 1    |
+------+
Query took 0.008 seconds.
```

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/40594937/50f09787-ab0a-4ed6-a732-e3259e5a7912)

```log
public ❯ copy into 'test' from air file_format = (type = 'ndjson', delimiter = '@', with_header = true);
422 Unprocessable Entity, details: {"error_code":"010003","error_message":"Semantic error: Unknown FileType: NDJSON, only support AVRO | PARQUET | CSV | JSON"}
```

**Comment by Benxiaohai001** [comment]
https://docs.cnosdb.com/zh/latest/manage/alarm_manage.html#%E5%9C%A8slack%E6%9F%A5%E7%9C%8B%E6%8E%A5%E5%8F%97%E5%88%B0%E7%9A%84%E9%80%9A%E7%9F%A5
![image](https://github.com/cnosdb/cnosdb/assets/40594937/a5ec477c-908b-4287-9fab-ce2a48b23091)
Duplicate interface

**Comment by Benxiaohai001** [comment]
https://docs.cnosdb.com/zh/latest/manage/alarm_manage.html#api-%E6%8E%A5%E5%8F%A3%E6%8F%8F%E8%BF%B0
It is recommended that the alarm rule persistence configuration file be added to the document

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/40594937/58f420d5-9ce6-464d-ace5-6e9c811c2c2d)
https://beta.docs.cnosdb.com/docs/manage/alarm_manage
Supplementary explanation of sqltype parameters

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/40594937/04406a71-05fc-4374-83e4-cbcd2bea7a63)
https://beta.docs.cnosdb.com/docs/manage/alarm_manage#apiv1alertconfigruletenanttenantidid-1
delete rule

**Comment by IvanGao01** [comment]
Regarding whether it supports `ndjson `, earlier versions may have supported it, but I am not sure when the changes began. This requires checking the version:

| Community| Enterprise |
| --- |--- |
| v2.3.2 |v2.3.2 |
| v2.3.4 |v2.3.4 |
| v2.3.4.1 ||
| v2.3.4.2 ||
| v2.3.4.3 ||
| v2.4.0 |v2.4.0 |

**Comment by IvanGao01** [comment]
@Kree0 needs help confirming which file formats are supported by `COPY INTO` and in which versions!

**Comment by Benxiaohai001** [comment]
> https://docs.cnosdb.com/zh/latest/manage/alarm_manage.html#%E5%9C%A8slack%E6%9F%A5%E7%9C%8B%E6%8E%A5%E5%8F%97%E5%88%B0%E7%9A%84%E9%80%9A%E7%9F%A5 ![image](https://private-user-images.githubusercontent.com/40594937/296148154-a5ec477c-908b-4287-9fab-ce2a48b23091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzA0MjYsIm5iZiI6MTcxOTgzMDEyNiwicGF0aCI6Ii80MDU5NDkzNy8yOTYxNDgxNTQtYTVlYzQ3N2MtOTA4Yi00Mjg3LTlmYWItY2UyYTQ4YjIzMDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEwMzUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMGUzMmVhNTY5NTM3MTBkMWY5ZGEwMmZhNGI2MDNhZDlkYTM3MWJlMDBhNzFhOGIyMmI4ODRlYmE2YzEzOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_d7txnfBnGwAtcIhfUMx-V4hTVEx-qT7Qv9vOeWdXE) Duplicate interface

![image](https://github.com/cnosdb/cnosdb/assets/40594937/6c6b36da-25e8-42a5-a3f3-3162131944ca)
No modifications here

**Comment by Benxiaohai001** [comment]
> ![image](https://private-user-images.githubusercontent.com/40594937/294883550-50f09787-ab0a-4ed6-a732-e3259e5a7912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzA0MjYsIm5iZiI6MTcxOTgzMDEyNiwicGF0aCI6Ii80MDU5NDkzNy8yOTQ4ODM1NTAtNTBmMDk3ODctYWIwYS00ZWQ2LWE3MzItZTMyNTllNWE3OTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEwMzUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMTFiYjQwNTBlYmQ0ZmQ3MTI5MDFiM2M0ZGJmZjVjZDQ2NmU3NTk5MDM3OThiYTIwZGJhNGI3MmE2NmEwMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6aKTZn0UP_61aRXOE_6vrSEpufy2dPEc4-qtz4hxCQ)
> 
> ```
> public ❯ copy into 'test' from air file_format = (type = 'ndjson', delimiter = '@', with_header = true);
> 422 Unprocessable Entity, details: {"error_code":"010003","error_message":"Semantic error: Unknown FileType: NDJSON, only support AVRO | PARQUET | CSV | JSON"}
> ```
This should support ndjson. There was a problem with the previous issue and it needs to be modified.

**Comment by Benxiaohai001** [comment]
> https://docs.cnosdb.com/zh/latest/manage/alarm_manage.html#api-%E6%8E%A5%E5%8F%A3%E6%8F%8F%E8%BF%B0 It is recommended that the alarm rule persistence configuration file be added to the document

Configuration file is not added

**Comment by Benxiaohai001** [comment]
> ![image](https://private-user-images.githubusercontent.com/40594937/296438323-04406a71-05fc-4374-83e4-cbcd2bea7a63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzA0MjYsIm5iZiI6MTcxOTgzMDEyNiwicGF0aCI6Ii80MDU5NDkzNy8yOTY0MzgzMjMtMDQ0MDZhNzEtMDVmYy00Mzc0LTgzZTQtY2JjZDJiZWE3YTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEwMzUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNmRmODc0MzhjNGRiNzE2MmFjZDMyMTY0ZGVmOWZkMjY4NzhjYzA0ZDFjYmE3ZWZkMmNiOWUwYmZkZDg3MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VyWZo9y4GmwcGcClRJw-_9wVG9-RD3nBrDz-3KLZNNs) https://beta.docs.cnosdb.com/docs/manage/alarm_manage#apiv1alertconfigruletenanttenantidid-1 delete rule

no modify

**Comment by paradox0503** [comment]
> > @Kree0 needs help confirming which file formats are supported by `COPY INTO` and in which versions!
> 
> In fact, `COPY INTO` in all versions only support these four types: `AVRO | PARQUET | CSV | JSON`.

![ebd1a280ca94c795e43696a0a62ee4bb](https://github.com/user-attachments/assets/df89d139-5dd6-4b01-92f4-3a934ab63729)
@IvanGao01  Should the documentation include the AVRO type? It seems that other documentation hasn’t been updated either.

**Comment by IvanGao01** [comment]
> https://docs.cnosdb.com/zh/latest/manage/alarm_manage.html#%E5%9C%A8slack%E6%9F%A5%E7%9C%8B%E6%8E%A5%E5%8F%97%E5%88%B0%E7%9A%84%E9%80%9A%E7%9F%A5 接口重复 ![图像](https://private-user-images.githubusercontent.com/40594937/296148154-a5ec477c-908b-4287-9fab-ce2a48b23091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDU0NDgsIm5iZiI6MTcyNDMwNTE0OCwicGF0aCI6Ii80MDU5NDkzNy8yOTYxNDgxNTQtYTVlYzQ3N2MtOTA4Yi00Mjg3LTlmYWItY2UyYTQ4YjIzMDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA1MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMDk3YTU3ZTBlMDI1MTA1YTNhNTNjYzQ3ODQzYzkyYmVmOWI3Mjc4MmE4MWZkOWZhZTY2MjllOTFjNjhkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sc2-BEET0LNWCukyPFGFj5HigDm_Iupts_FY1SuiWbI)

@xuegexi Please check and update

**Comment by xuegexi** [comment]
> > https://docs.cnosdb.com/zh/latest/manage/alarm_manage.html#%E5%9C%A8slack%E6%9F%A5%E7%9C%8B%E6%8E%A5%E5%8F%97%E5%88%B0%E7%9A%84%E9%80%9A%E7%9F%A5 接口重复 ![图像](https://private-user-images.githubusercontent.com/40594937/296148154-a5ec477c-908b-4287-9fab-ce2a48b23091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDU0NDgsIm5iZiI6MTcyNDMwNTE0OCwicGF0aCI6Ii80MDU5NDkzNy8yOTYxNDgxNTQtYTVlYzQ3N2MtOTA4Yi00Mjg3LTlmYWItY2UyYTQ4YjIzMDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA1MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMDk3YTU3ZTBlMDI1MTA1YTNhNTNjYzQ3ODQzYzkyYmVmOWI3Mjc4MmE4MWZkOWZhZTY2MjllOTFjNjhkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sc2-BEET0LNWCukyPFGFj5HigDm_Iupts_FY1SuiWbI)
> 
> @xuegexi Please check and update

The same URL with different HTTP methods.

**Comment by IvanGao01** [comment]
> > @Kree0`COPY INTO`需要帮助确认哪些文件格式以及哪些版本支持！
> 
> 事实上，`COPY INTO`各个版本都只支持这四种类型：`AVRO | PARQUET | CSV | JSON`。

I've tested all four, but when I specify AVRO as the TYPE, the server says `This feature is not implemented: Only support ParquetFormat | CsvFormat | JsonFormat.` So I think AVRO is not implemented!

**Comment by roseboy-liu** [comment]
done
