### ISSUE TITLE
[optimization][copy into]It is recommended that the export file size can be configured

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1914]
**Is your feature request related to a problem? Please describe.**
It is recommended that the export file size can be configured
In our current environment, the size of a single exported file is about 4MB, and when exporting, the number of files is related to the number of CPUs.Exporting 40g of data, the number of files is about 10,000, making it inconvenient to manage the machine.In an environment with a large number of CPUs, there will be more export files. This part of the logic is also expected to be optimized.
**Describe the solution you'd like**
It is recommended that the export file size can be configured

**Describe alternatives you've considered**

**Additional context**

**Comment by lutengda** [comment]
https://github.com/cnosdb/cnosdb/commit/b007cd482719d8d4061670fe726fa28bc8ef74b4

**Comment by Benxiaohai001** [comment]
version:cnosdb 2.3.4, revision ba5935faa7b03cfa3b2a170110b44e7c18514dcf
config: copyinto_trigger_flush_size = "128M" # 134217728
```log
public ❯ copy into 'file:///home/bca/code/cnosdb/data/test' from readings FILE_FORMAT = (
    TYPE = 'CSV',
    DELIMITER=',',
    WITH_HEADER=false
);
+----------+
| rows     |
+----------+
| 56348326 |
+----------+
Query took 545.097 seconds.
```

**Comment by Benxiaohai001** [comment]
the PR need sync 2.4. @lutengda

**Comment by roseboy-liu** [comment]
https://github.com/cnosdb/cnosdb/pull/1959

**Comment by Benxiaohai001** [comment]
```log
public ❯ copy into 'file:///home/bca/code/cnosdb/data/test' from readings FILE_FORMAT = (
    TYPE = 'CSV',
    DELIMITER=',',
    WITH_HEADER=false
);
+----------+
| rows     |
+----------+
| 56348326 |
+----------+
Query took 18.407 seconds.
```
version:cnosdb 2.4.0, revision ee241ec73f2e2c9a8cdd9cee7789f7665efc8a72
