### ISSUE TITLE
The system database is displayed in the desired location

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1917]
### Describe the bug

cluster_schema(invisible in tenant cnosdb)
information_schema(invisible in each cnosdb)
usage_schema(only visible in tenant cnosdb)

### Expected behavior

cluster_schema (visible only in tenant cnosdb)
information_schema (visible in each tenant)
usage_schema (visible in each tenant)

**Comment by h4ofanya** [comment]
It is not necessary, we describe these database in the doc
