### ISSUE TITLE
[BUG] The Grafana plugin `prometheus-data-source` cannot read cnosdb data by prometheus remote-read

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1922]
### Describe the bug

promtheus failed to remotely read cnosdb data

### To Reproduce

![image](https://github.com/cnosdb/cnosdb/assets/40594937/571d9c91-6cb0-495e-8e8b-1e1a5e0d415e)

**Comment by lutengda** [comment]
We need a value column in the table, and we need to be aware of the time interval when querying data that is too early, so we need to adjust our Query options
