### ISSUE TITLE
[BUG]copyinto wide table import failed

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#1929]
### Describe the bug

version: 6765f19dcc86f9df02c225c139912d50769457ac
In the case of a wide table and a certain amount of data, copyinto export fails with the following error
![image](https://github.com/cnosdb/cnosdb/assets/50371898/e5d5ed76-9b4b-4d59-ba15-f711c007d58a)

### To Reproduce

Single node start, one tag, 200 double columns, write 5000 rows of data, then copyinto export operation will give this error

### Additional context

this pr fix this issue
https://github.com/cnosdb/cnosdb/pull/1924

**Comment by h4ofanya** [comment]
the bug has been tested
