### ISSUE TITLE
[cluster manager][doc]docs optimization

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1930]
### Describe the bug
https://beta.docs.cnosdb.com/docs/manage/node_manage
1. add node 
What needs to be modified is not only the meta information and name information, but also other configurations such as hostname, id etc.
2. removenode
Add relevant instructions for the force parameter. This information cannot be obtained from the information in the current document.

**Comment by paradox0503** [comment]
This still seems not changed. @IvanGao01

**Comment by IvanGao01** [comment]
@paradox0503 A description of the `force` in the removenode already exists, and you can access it at the link [remote-node](https://docs.cnosdb.com/en/docs/manage/cluster_manage/#remove-node).
Example document titled ‘Force remove node’.

Regarding add node in cluster management, please ask @bartliu827 to help add a more complete description.

**Comment by paradox0503** [comment]
It seems that the documentation for adding nodes has not yet been updated. @bartliu827
