### ISSUE TITLE
[BUG][node offline]After the node goes offline, data is still being written to the offline node.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1932]
### Describe the bug

After the node goes offline, data is still being written to the offline node.
version:cnosdb 2.4.0, revision cca656f386e10a1e9cb59d6c360a7f67af99d791
mode: 3m2d

### To Reproduce

1. start cluster 3m2d;
2. wait a minute ,check usage_schema data which node stored the vnode;
3. removenode the nodeid;
4. wait a minute;Check whether the usage_schema data has increased, and check whether another node has a new vnode.

**Comment by Benxiaohai001** [comment]
tskv table has the same problem.

**Comment by lutengda** [comment]
If the data belongs to an already created bucket, the writing continues. But no more buckets will be created. After discussion, it is not modified here. If users have questions, explain again

**Comment by Benxiaohai001** [comment]
As explained above, the original processing method is maintained here.
