### ISSUE TITLE
[doc]It is recommended to add relevant instructions for the ttl parameter

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1933]
**Describe the issue**
A clear and concise description of issue.
![image](https://github.com/cnosdb/cnosdb/assets/40594937/f3b24e4f-540c-44d6-a0e5-a98e92e017d2)

**What you like us to do**
Please give us some advices
It is recommended to add relevant instructions for the ttl parameter.
Explain the relationship with the vnode_duration parameter; add links related to principle articles.

**Additional context**
Add any other context about the issue here.

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/40594937/42758d77-068c-4a55-be89-dfacdbb0f9b4)
![image](https://github.com/cnosdb/cnosdb/assets/40594937/37c91b8b-1ee6-4c06-ba0e-2202abef485d)

start cmd:
```bash 
cnosdb --config ./cnosdb.conf
```
should replace with 
```bash 
cnosdb  run --config ./cnosdb.conf
```

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/40594937/4f2e6307-6149-45bb-99c4-3ad1007a92a7)
Many environment variables are not written in the configuration file introduction.

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/40594937/cd5e7d1e-b9dc-4b56-9d58-e8ded41e71c2)
Some parameter descriptions are missing

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/40594937/0fee6274-2b92-48b7-b3e7-d88fa40acdf7)
It is recommended to add units

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/40594937/656af5d8-4fae-4879-80c1-255287db10e5)
![image](https://github.com/cnosdb/cnosdb/assets/40594937/bf6ff00f-2801-4b9f-b887-a3fc1f121c5f)

empty link

**Comment by IvanGao01** [comment]
https://github.com/cnosdb/docs/commit/a5b84e30882b968184ec4e0802bbfba1fed7ceb8
