### ISSUE TITLE
[discuss][node offline]The process still exists after the node goes offline. Is there a waste of resources and ports?

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1934]
**Describe the issue**
A clear and concise description of issue.
The process still exists after the node goes offline. Is there a waste of resources and ports?

**What you like us to do**
Please give us some advices

**Additional context**
Add any other context about the issue here.

**Comment by roseboy-liu** [comment]
The process should be stopped by DB admin. should not be automatic
