### ISSUE TITLE
[BUG][COPY INTO] "Too many open files" occasionally appears when exporting

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#1958]
### Describe the bug

"Too many open files" occasionally appears when exporting
version:cnosdb 2.3.4, revision ba5935faa7b03cfa3b2a170110b44e7c18514dcf
mode: singleton
config: copyinto_trigger_flush_size = "2048M"

### To Reproduce

1. import data line protocol 26G;
`load_cnosdb --db-name "public" --file ./cnodb-iot-seed-123-scale-100-2021_000_shufed --urls "http://192.168.0.23:8902" --workers 20`
2. export  readings table 
```
copy into 'file:///home/bca/code/cnosdb/data/test' from readings FILE_FORMAT = (
    TYPE = 'CSV',
    DELIMITER=',',
    WITH_HEADER=false
);
```
result:
`422 Unprocessable Entity, details: {"error_code":"010001","error_message":"Datafusion: External error: External error: TskvError: Unable to open file '/home/bca/code/cnosdb/data/cnosdb/1001/db/data/cnosdb.public/6/delta/_000016.delta': Too many open files (os error 24)"}`
check the open files:
```log
[root@cicd_ujv23 cnosdb]# lsof -p 16634| wc -l
100
[root@cicd_ujv23 cnosdb]# lsof -p 16634| wc -l
23312
[root@cicd_ujv23 cnosdb]# lsof -p 16634| wc -l
38778
[root@cicd_ujv23 cnosdb]# lsof -p 16634| wc -l
58376
[root@cicd_ujv23 cnosdb]# lsof -p 16634| wc -l
25278
```

**Comment by zipper-meng** [comment]
Cache Breakdown Error caused by too many read requests to TsKv.

Before(31566a)

https://github.com/cnosdb/cnosdb/blob/31566a50bf35cb6cdd9bafc95917b38ea57f75e5/tskv/src/tseries_family.rs#L514-L524

After(ba5935)

https://github.com/cnosdb/cnosdb/blob/ba5935faa7b03cfa3b2a170110b44e7c18514dcf/tskv/src/tseries_family.rs#L514-L524

**Comment by lutengda** [comment]
I recommend testing it in an environment without other cnosdb processes and seeing if it opens a large number of files; 
the larger the max_cached_readers configuration, the smaller the number of open files

**Comment by Benxiaohai001** [comment]
version:ba5935faa7b03cfa3b2a170110b44e7c18514dcf
Test in two environments respectively, follow the above steps, one environment handle can reach up to 70,000, and one environment can reach up to 13,000

**Comment by lutengda** [comment]
Increasing the 'max_cached_readers' parameter to 1024 reduces the number of open files to just over 400

**Comment by Benxiaohai001** [comment]
After communication and confirmation, it can be handled according to the above method.
