### ISSUE TITLE
[BUG]Computing and storage separate deployment "show datanodes" don't show query node.

### ISSUE THREAD

**Issue by liikeuforever** [cnosdb/cnosdb#1966]
### Describe the bug

Computing and storage separate deployment client ping query node ,and"show datanodes" don't show query node.
version: https://github.com/cnosdb/cnosdb-enterprise/commit/cca656f386e10a1e9cb59d6c360a7f67af99d791

### To Reproduce

1 meta 2data
modify run_cluster.sh
```
"echo "*** start CnosDB server 8902......"
nohup ./target/debug/cnosdb run -M tskv --config ./config/config_8902.toml 
echo "*** start CnosDB server 8912......"
nohup ./target/debug/cnosdb run -M query --config ./config/config_8912.toml
"
```

`./run_cluster.sh`
`cargo run --package client --bin cnosdb-cli -- -P 8912`

```
public ❯ show datanodes;
+---------+-----------+-----------+---------+-----------+------------+------------+---------------------+
| node_id | host      | attribute | status  | disk_free | disk_total | location   | last_updated_time   |
+---------+-----------+-----------+---------+-----------+------------+------------+---------------------+
| 1001    | localhost | hot       | healthy | 93.84 GB  | 245.11 GB  | /dc1/rack1 | 2024-01-27 02:15:02 |
+---------+-----------+-----------+---------+-----------+------------+------------+---------------------+
Query took 0.025 seconds.
```

**Comment by liikeuforever** [comment]
"show datanodes" should only return tskv & storage nodes.
but we should make sense that we can see the query nodes in a way, such as show nodes.

**Comment by liikeuforever** [comment]
this is not a bug, so please close it, and add_query_node We'll flesh out the implementation later.

**Comment by Benxiaohai001** [comment]
Waiting for community version 2.3, 2.4 and enterprise version 2.4 to be synchronized

**Comment by roseboy-liu** [comment]
Indeed, in the storage-compute separation mode, it is necessary to keep track of the status of query nodes. Upon the startup of a query node, it needs to register with the metadata service. By using the "show node" command, you can query both the storage nodes and the query nodes.

**Comment by Benxiaohai001** [comment]
Comply with design close the issue
