### ISSUE TITLE
[Doc][Bug]  inconsistencies between the cluster in the configuration file and the actual community edition configuration

### ISSUE THREAD

**Issue by liikeuforever** [cnosdb/cnosdb#2005]
### Describe the bug

There are inconsistencies between the cluster in the configuration file and the actual community edition configuration
![image](https://github.com/cnosdb/cnosdb/assets/156390964/55d7e4d7-9586-41b9-bf77-c88f71e97ada)
![image](https://github.com/cnosdb/cnosdb/assets/156390964/8e15ca82-651b-4366-9909-f66a071f9e7f)

**Comment by Benxiaohai001** [comment]
Done
