### ISSUE TITLE
[BUG] A role can be assigned read and write permissions to a non-existent db.

### ISSUE THREAD

**Issue by h4ofanya** [cnosdb/cnosdb#2012]
### Describe the bug

role can be assigned read and write permissions to a non-existent db.

### To Reproduce

information_schema ❯ show databases;
+---------------+
| database_name |
+---------------+
| public        |
| usage_schema  |
+---------------+
Query took 0.012 seconds.
information_schema ❯ grant read on database air to role mem
;
Query took 0.007 seconds.
information_schema ❯ SELECT *
FROM DATABASE_PRIVILEGES;
+-------------+---------------+----------------+-----------+
| tenant_name | database_name | privilege_type | role_name |
+-------------+---------------+----------------+-----------+
| cnosdb      | air           | Read           | mem       |
+-------------+---------------+----------------+-----------+

### Expected behavior

report an error: database not found

**Comment by Benxiaohai001** [comment]
This is a feature before 2.3. To fix the problem, you need to synchronize it with 2.3.
