### ISSUE TITLE
change del_tsf/add_tsf to enum in VersionEdit

### ISSUE THREAD

**Issue by bartliu827** [cnosdb/cnosdb#2017]
**Describe the issue**

pub struct VersionEdit {
    pub seq_no: u64,
    pub file_id: u64,
    pub max_level_ts: Timestamp,
    pub add_files: Vec<CompactMeta>,
    pub del_files: Vec<CompactMeta>,
    pub del_tsf: bool,
    pub add_tsf: bool,
    pub tsf_id: TseriesFamilyId,
    pub tsf_name: String,
}

change del_tsf/add_tsf to enum

**What you like us to do**
pub enum VnodeAction{
Add,
Delete,
Update,
}

**Additional context**
Add any other context about the issue here.

**Comment by Benxiaohai001** [comment]
Requires sync 2.3

**Comment by roseboy-liu** [comment]
> Requires sync 2.3

not needed to sync 2.3
