### ISSUE TITLE
[optimize] batch_size is MIN(default_value, limit) when select data from table

### ISSUE THREAD

**Issue by bartliu827** [cnosdb/cnosdb#2033]
**Describe the issue**
batch_size default value is 8192,when select data limit 10 maybe consume more resources.

**What you like us to do**
batch_size = MIN(default_value, limit)

**Additional context**
Add any other context about the issue here.

**Comment by lutengda** [comment]
Optimized:38dd7f74fff23c33d134af7f70f99214cbde8179, this issue is closed
