### ISSUE TITLE
[BUG]Meta data synchronization to data is not timely in windows.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#2064]
### Describe the bug

version: 2.4 b8587739
![image](https://github.com/cnosdb/cnosdb/assets/40594937/060cb477-e0da-42ec-8126-2dacdef2564f)

**Comment by bartliu827** [comment]
write data not found replication set. maybe meta sync to data node not timely

**Comment by gcnote** [comment]
您好，您发的邮件我已收到，谢谢！！！
