### ISSUE TITLE
remove some config items in meta config file

### ISSUE THREAD

**Issue by bartliu827** [cnosdb/cnosdb#2082]
**Describe the issue**
system_tenant = "cnosdb"
This config item not allowed to be modified，which will result in inconsistency with the data node.

**What you like us to do**
<img width="419" alt="image" src="https://github.com/cnosdb/cnosdb/assets/104353559/f95a5554-540d-4fd0-93cd-ba664dbddd72">
remove all of them?just remain cluster_name

**Additional context**
Add any other context about the issue here.

**Comment by Benxiaohai001** [comment]
Bug was fixed, close the issue.
