### ISSUE TITLE
remove data block type in wal file

### ISSUE THREAD

**Issue by bartliu827** [cnosdb/cnosdb#2083]
**Describe the issue**
There is only on block type in wal data block,Do we need to keep it?

**What you like us to do**
![image](https://github.com/cnosdb/cnosdb/assets/104353559/52856643-4ee1-461b-aeb7-2c01e0298f23)

**Additional context**
Add any other context about the issue here.

**Comment by zipper-meng** [comment]
Removed type `wal::Block` and adjusted dependents.

```rust
/// Before
pub struct WalRecordData {
     pub typ: WalType,
     pub seq: u64,
     pub block: Block,
 }
/// After
pub struct WalRecordData {
     pub typ: WalType,
     pub seq: u64,
     pub block: Option<wal_store::RaftEntry>,
 }
```
