### ISSUE TITLE
[expect]It is recommended that configuration information can be printed in the meta log.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#2105]
**Describe the issue**
A clear and concise description of issue.
It is recommended that configuration information can be printed in the meta log.
**What you like us to do**
Please give us some advices
It is recommended that configuration information can be printed in the meta log,Just like the querytskv log.When we modify the meta configuration and start it, there is no way to check whether the configuration we modified takes effect.
**Additional context**
Add any other context about the issue here.

**Comment by paradox0503** [comment]
![5e3d9b5a2d8a9cb083b8b819802e140f](https://github.com/user-attachments/assets/9d5d1ed5-e5ca-4924-bda4-b1e549ccb741)
Do you mean that the Meta node’s logs need configuration content? It seems that the current version can already output logs.

**Comment by zipper-meng** [comment]
The configuration was printed to STDOUT, not the logging output, I think Mr.Ben meant to put the configuration text in the logging output.

**Comment by Benxiaohai001** [comment]
When I was using the enterprise version of 2.4.2.1, I found that the configuration file information was not recorded in the meta and querytskv logs.It is expected that the configuration information of query, tskv, querytskv, meta (separation of storage and calculation, integration of storage and calculation, single-node deployment) can be recorded in the log.
version:cnosdb-meta 2.4.2, revision 92f8fc972cb45b190056a4c9beb44b3ec8b69b5b
