### ISSUE TITLE
[BUG]The memory continues to grow during data writing and OOM occurs.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#2129]
### Describe the bug

The memory continues to grow during data writing and OOM occurs.
version:cnosdb 2.4.1, revision 4a1035f5f35e426c27169eb517c213a2aa707c07
deploy: 3+2

### To Reproduce

db
```
create database benchmark with replica 2;
```
load data
```
load_cnosdb --batch-size 1000 --file ./line_protocol_20180101_20190101.txt --workers 10 --urls "http://xxxxx:9902/"
```

monitor:
![Uploading image.png…]()

**Comment by Benxiaohai001** [comment]
![image](https://github.com/cnosdb/cnosdb/assets/40594937/70bf6603-ac08-44f0-a7b3-78fa91de04e3)

**Comment by zipper-meng** [comment]
#2174 
#2178

**Comment by Benxiaohai001** [comment]
Done
