### ISSUE TITLE
[discuss][node offline]Remove nodes in batches

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#2139]
**Describe the issue**
A clear and concise description of issue.
When there are many nodes, it is cumbersome to remove nodes one by one. Is it possible to support batch removal of nodes?

**What you like us to do**
Please give us some advices

**Additional context**
Add any other context about the issue here.

**Comment by roseboy-liu** [comment]
I think this is a very dangerous command.
