### ISSUE TITLE
[BUG] join returned a field error

### ISSUE THREAD

**Issue by h4ofanya** [cnosdb/cnosdb#2212]
### Describe the bug

when you join table, you will get a no field error even if the field exists

### To Reproduce

```
1. create table first
public ❯ create table test1(d1 double, d2 double);
Query took 0.029 seconds.
public ❯ create table test2(d3 double, d4 double);
Query took 0.020 seconds.


2. join table with different order
public ❯ select * from test1
test1 join test2 on test1.d1 = test2.d3;
Query took 0.025 seconds.
public ❯ select * from test1
test2 join test1 on test1.d1 = test2.d3;
422 Unprocessable Entity, details: {"error_code":"010001","error_message":"Datafusion: Schema error: No field named test2.d3. Valid fields are test2.time, test2.d1, test2.d2, test1.time, test1.d1, test1.d2."}
```

**Comment by lutengda** [comment]
**This is a SQL usage problem**
this SQL
"_select * from test1 test2 join test1 on test1.d1 = test2.d3;_"
Equivalent to
"_select * from test1 as test2 join test1 on test1.d1 = test2.d3;_" .
The left child of join in this usage is test1 as test2, and it is clear that no d3 column exists in test1
So, close this issue
