### ISSUE TITLE
can not run on windows

### ISSUE THREAD

**Issue by asyura** [cnosdb/cnosdb#2226]
**Describe the issue**
How to run on windows. when i run the server with cnosdb.exe run. it do's not success. the error message is below
`2024-07-06T11:46:58.803494400+08:00  INFO meta::model::meta_admin: watch meta node change wrong Err(MetaClientErr { msg: "httpcode: 500 Internal Server Error, response:has to forward request to: None, None" })
thread 'main' panicked at main\src\server.rs:198:36:
called `Result::unwrap()` on an `Err` value: MetaClientErr { msg: "httpcode: 500 Internal Server Error, response:has to forward request to: None, None" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**What you like us to do**
Could you provide som samples can run on windows

**Comment by Benxiaohai001** [comment]
> **Describe the issue** How to run on windows. when i run the server with cnosdb.exe run. it do's not success. the error message is below `2024-07-06T11:46:58.803494400+08:00 INFO meta::model::meta_admin: watch meta node change wrong Err(MetaClientErr { msg: "httpcode: 500 Internal Server Error, response:has to forward request to: None, None" }) thread 'main' panicked at main\src\server.rs:198:36: called `Result::unwrap()`on an`Err`value: MetaClientErr { msg: "httpcode: 500 Internal Server Error, response:has to forward request to: None, None" } note: run with`RUST_BACKTRACE=1` environment variable to display a backtrace`
> 
> **What you like us to do** Could you provide som samples can run on windows

@asyura Please help provide more information, such as deployment method, version, startup command, configuration parameters, etc.

**Comment by zipper-meng** [comment]
Thanks for trying our one-meta and one-data mode.

You should manually init the meta server after you start `cnosdb-meta.exe`  and before run `cnosdb.exe`. If you're using powershell, the command is:

```powershell
Invoke-WebRequest -Method POST -ContentType application/json -Uri http://127.0.0.1:8901/init -Body {}
```

Then start `cnosdb.exe`

```powershell
cargo run --package main --bin cnosdb -- run --config .\config\config_8902.toml
```

**Comment by roseboy-liu** [comment]
close it
