### ISSUE TITLE
[Typo] collection of typos

### ISSUE THREAD

**Issue by zipper-meng** [cnosdb/cnosdb#2247]
- [ ] `generate pprof files:`
https://github.com/cnosdb/cnosdb/blob/3ee65a7f193dde1000af3a56669af2c6cbd15ab0/main/src/http/mod.rs#L73-L77
- [ ] `Failed to do decode`
https://github.com/cnosdb/cnosdb/blob/3ee65a7f193dde1000af3a56669af2c6cbd15ab0/tskv/src/error.rs#L293-L299
- [ ] `TenantMetaData`
https://github.com/cnosdb/cnosdb/blob/3ee65a7f193dde1000af3a56669af2c6cbd15ab0/meta/src/store/command.rs#L156-L160

**Comment by paradox0503** [comment]
pull requests#2283
