### ISSUE TITLE
connection closed when running "SELECT approx_percentile_cont(temperature, 0.1, 100) FROM air;"

### ISSUE THREAD

**Issue by civi1007** [cnosdb/cnosdb#2259]
Starting a CnosDB client service on Darwin abo0214deMacBook-Pro.local (22.6.0 Darwin Kernel Version 22.6.0) will result in an error. However, it executes correctly in the GitHub CI tests.

base ❯ cnosdb-cli
CnosDB CLI v2.4.2
Input arguments: CliArgs { subcommand: None, host: "localhost", port: 8902, user: "root", password: false, private_key_path: None, database: "public", tenant: "cnosdb", precision: None, target_partitions: None, stream_trigger_interval: None, data_path: None, receive_data_encoding: None, send_data_encoding: None, file: [], rc: None, format: Table, quiet: false, write_line_protocol: None, use_ssl: false, use_unsafe_ssl: false, cacert: [], proxy_url: None, chunked: false, error_stop: false, process_cli_command: false }
public ❯ DROP TABLE IF EXISTS air;
Query took 0.480 seconds.
public ❯ CREATE TABLE air (
    id bigint,
    temperature double
);
Query took 0.084 seconds.
public ❯ INSERT INTO air (TIME, id, temperature) VALUES
('1999-12-31 00:00:00.000', 1, 65.0),
('1999-12-31 00:00:00.001', 2, 64.5),
('1999-12-31 00:00:00.002', 3, 64.9),
('1999-12-31 00:00:00.003', 4, 65.1),
('1999-12-31 00:00:00.004', 5, 64.7);
+------+
| rows |
+------+
| 5    |
+------+
Query took 0.018 seconds.
public ❯ SELECT approx_percentile_cont(temperature, 0.9, 100) AS approx_90th_percentile FROM air;
+------------------------+
| approx_90th_percentile |
+------------------------+
| 65.1                   |
+------------------------+
Query took 0.120 seconds.
public ❯ INSERT INTO air (TIME, id, temperature) VALUES
('1999-12-31 00:00:00.005', 6, NULL),
('1999-12-31 00:00:00.006', 7, -5.0),
('1999-12-31 00:00:00.007', 8, -10.0),
('1999-12-31 00:00:00.008', 9, -2.5);

+------+
| rows |
+------+
| 4    |
+------+
Query took 0.007 seconds.
public ❯ SELECT approx_percentile_cont(temperature, 0.1, 100) AS approx_10th_percentile FROM air;

error sending request for url (http://localhost:8902/api/v1/sql?tenant=cnosdb&db=public&chunked=false): connection closed before message completed

Caused by:
    connection closed before message completed

The same error occurs when the date_bin function, power function and factorial function is run

**Comment by roseboy-liu** [comment]
I reproduce this issue on my mac， thread panic。 
thread stack backtrace ：  
```thread 'tokio-runtime-worker' panicked at .cargo/git/checkouts/arrow-datafusion-b823e336e4415a05/5367e31/datafusion/physical-expr/src/aggregate/tdigest.rs:238:9:
unsorted input to TDigest
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: datafusion_physical_expr::aggregate::tdigest::TDigest::merge_sorted_f64
             at .cargo/git/checkouts/arrow-datafusion-b823e336e4415a05/5367e31/datafusion/physical-expr/src/aggregate/tdigest.rs:238:9
   3: <datafusion_physical_expr::aggregate::approx_percentile_cont::ApproxPercentileAccumulator as datafusion_expr::accumulator::Accumulator>::update_batch
             at .cargo/git/checkouts/arrow-datafusion-b823e336e4415a05/5367e31/datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs:390:23
.....
```

**Comment by civi1007** [comment]
This error may be caused by DataFusion due to unsorted input to TDigest. For more details, see https://github.com/apache/datafusion/issues/12058.

**Comment by civi1007** [comment]
Bug was fixed, close the issue.
