### ISSUE TITLE
Can you give some performance reports for cnosdb?

### ISSUE THREAD

**Issue by faceair** [cnosdb/cnosdb#228]
Hi, I know there are these tools to compare the performance of different tsdb.
1. https://github.com/influxdata/influxdb-comparisons
2. https://github.com/timescale/tsbs

Can you compare the performance of cnosdb with these tools?

**Comment by IvanGao01** [comment]
Thank you for your suggestions.

We are actively developing performance comparison benchmark based on timescale tsbs.

You can follow our community wechat for the latest consultation and participate in in-depth discussions.
