### ISSUE TITLE
[BUG]When the table name contains "\", the table can be created successfully, but show table will not be displayed.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#2285]
### Describe the bug

When the table name contains "\", the table can be created successfully, but show table will not be displayed.
version:cnosdb 2.4.1, revision 9d1e4afd1ffc581364cf16d353421bb385c6a1f2

### To Reproduce

```
public ❯ \d
Query took 0.007 seconds.
public ❯ create table "tb/001"(f1 bigint, tags(t1));
Query took 0.005 seconds.
public ❯ \d
Query took 0.006 seconds.
public ❯ show tables;
Query took 0.006 seconds.
```

**Comment by zipper-meng** [comment]
No, not the backslash `\`, it's the slash character `/` made the bug.

**Comment by civi1007** [comment]
keyword is forbidden to contain slashes #2314, https://github.com/cnosdb/cnosdb/pull/2314
