### ISSUE TITLE
[Perf] The complexity of this function “read_data_and_build_array” can be reduced

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#2312]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/a42d2eee-6378-49e9-8901-ca75278e947d)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by paradox0503** [comment]
I submitted the improved code in this pull request.：https://github.com/cnosdb/cnosdb/pull/2327
