### ISSUE TITLE
[BUG]prom remote read api unable to query upper case table name problem

### ISSUE THREAD

**Issue by lutengda** [cnosdb/cnosdb#2340]
### Describe the bug

When the table name is uppercase, if you want to pass the uppercase to cnosdb, you need to use quotes. If you do not use quotes, uppercase is automatically converted to lowercase .When prometheus initiated the prom remote read request to cnosdb, no quotes were added, resulting in a lowercase case and a table not find error
![image](https://github.com/user-attachments/assets/4ad4fd97-e6a6-4ceb-a11b-2df680efc277)

I suspect other apis have this issue as well and can be handled uniformly

**Comment by paradox0503** [comment]
https://github.com/cnosdb/cnosdb/pull/2342
fixed this bug in pull request 2342
