### ISSUE TITLE
sqllogictest(dcl_tenant.slt) DROP TENANT if exists t6 and CREATE TENANT t6 WITH drop_after='1y' error

### ISSUE THREAD

**Issue by loloxwg** [cnosdb/cnosdb#2379]
### Describe the bug

![CleanShot 2024-11-12 at 11 13 56](https://github.com/user-attachments/assets/d93b942c-5691-41bf-880d-a55ec97c52c5)

### To Reproduce

sudo ./target/debug/cnosdb run -M singleton --config ./config/config.toml
run sqllogictest

### Expected behavior

CREATE TENANT t6 WITH drop_after='1y'  success

**Comment by loloxwg** [comment]
![CleanShot 2024-11-12 at 11 32 01](https://github.com/user-attachments/assets/a2b1a597-8343-4f1e-89f3-fc5bb6cc49c5)

**Comment by Subsegment** [comment]
<img width="762" alt="image" src="https://github.com/user-attachments/assets/79bce596-e44c-4622-8e98-d4a6178fda9b">

When there is a `drop_after`, cnosdb does not immediately remove the tenant

**Comment by loloxwg** [comment]
![CleanShot 2024-11-12 at 14 50 48@2x](https://github.com/user-attachments/assets/8c3f3da1-8768-40f7-9d2d-42921cc9212b)
If i create a tenant with drop_after(1y), then i explicitly drop it, the result return OK, but In fact, it is not deleted.
maybe should return other result eg. if you want to drop a tenant with drop_after, RECOVER it and unset drop_after

**Comment by lutengda** [comment]
I understand what you mean and thank you for raising the issue. We will discuss the issue of return information in this case
