### ISSUE TITLE
Add PromQL compatibility

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#3]
See PromQL  spec here: https://prometheus.io/docs/prometheus/latest/querying/basics/

**Comment by IvanGao01** [comment]
**Prometheus http write endpoint usage:**

1. you need to create a database in cnosdb in advance

2. Add content to "Prometheus. Yaml":
```
...
remote_write:
  - url: "http://localhost:8086/api/v1/prom/write?db=prometheus"
```
3. Start Prometheus to write the content scrape by Prometheus to cnosdb

**Comment by IvanGao01** [comment]
**Prometheus http write endpoint usage:**

1. you need to create a database in cnosdb in advance

2. Add content to "prometheus.yaml":
```
...
remote_write:
  - url: "http://localhost:8086/api/v1/prom/read?db=prometheus"
```
3. Start Prometheus to write the content scrape by Prometheus to cnosdb

**Comment by GaoXinzhi** [comment]
您的来信我已收到，将尽快查阅，谢谢！
