### ISSUE TITLE
Build Docker Image(meta) workflow run failed email 

### ISSUE THREAD

**Issue by cnoshb** [cnosdb/cnosdb#341]
**Describe the bug**
Every night I got email of "Build Docker Image(meta) workflow run" and it's quite annoying.
How can I fix it?

**Comment by oyzg** [comment]
you can set it at Settings-Actions-general-Actions permissions in your repositories

**Comment by IvanGao01** [comment]
Please update your code. Now you won't receive annoying emails again.
