### ISSUE TITLE
cnosdb_tools import

### ISSUE THREAD

**Issue by bartliu827** [cnosdb/cnosdb#353]
**Describe the bug**
使用cobra创建命令行  实现cnosdb_tools import 命令
**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Actual behavior**
Describe What actually happened.

**System information**

Run `uname -a` and copy the output here.

**CnosDB information**

Run `cnosdb version` and copy the output here.

**Other relevant environment details:**
Container runtime, disk info, etc.

**Config:** Copy any non-default config values here or attach the full config as a gist or file.

**Logs:** Include snippet of errors in log.

**Additional context:**

**Comment by xmh1011** [comment]
#259
