### ISSUE TITLE
Tag needs to support more data types

### ISSUE THREAD

**Issue by yuandongs** [cnosdb/cnosdb#366]
Now only String type is supported, it is really inconvenient to use. 

If there are as many types supported as Field, we can perform the comparison operation between Tag and Field, instead of storing some data that should be stored in Tag, into Field.

**Comment by muninshen** [comment]
Exactly, field values can be floats, integers, strings, or Booleans. But tag values can ONLY be strings. This make us not be able to perform math on tag values except "=" operator.
