### ISSUE TITLE
Single quote and double quote on fields won't fail the INSERT statement

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#414]
**Describe the bug**
According to [the doc](https://cnosdb.github.io/docs/content/cnosdb/latest/protocol/line_protocol.html#%E5%BC%95%E5%8F%B7),  single quote and double quote on fields on INSERT statements won't work in CnosDB and there will be an error message similar to below:
```
ERR: {"error":"unable to parse 'air,station=LianYunGang temperature='72'': invalid boolean"} 
```

However, it DOESN'T return ANYTHING, no error message, no successful message.

**To Reproduce**
1. open a CnosDB connection
2. run this statement `INSERT air,station=LianYunGang temperature='72' 1642176180000000000`

**Expected behavior**
Following error message should be returned:
```
ERR: {"error":"unable to parse 'air,station=LianYunGang temperature='72'': invalid boolean"} 
```

**Actual behavior**
Nothing returned from the command line.

**System information**

Windows 10

**CnosDB information**

v1.0.3

**Other relevant environment details:**
Running in .exe

**Comment by pppy2012** [comment]
This issue has been solved in #417
