### ISSUE TITLE
Build failed cause type task_t is unavailable on Linux

### ISSUE THREAD

**Issue by oyzg** [cnosdb/cnosdb#435]
Describe the bug

Can not build it under linux with the following error message:

```
error[E0432]: unresolved import `libc::task_t`
 --> tskv/src/version_set.rs:8:23
  |
8 | use libc::{backtrace, task_t};
  |                       ^^^^^^
  |                       |
  |                       no `task_t` in the root
  |                       help: a similar name exists in the module: `stack_t`
```

[link to this line of code](https://github.com/cnosdb/cnosdb-isipho/blob/main/tskv/src/version_set.rs#L8)
I searched task_t in the document of libc finding this type is exclusive to macOS. Then I found this task_t is unused, so I delete it from the source code and it was built successfully.

I don't know the usage of it, but if this is useful under macOS, maybe we can use conditional compilation to handle it.

To reproduce

1. Set up the environment
2. Clone the repo
3. `cd cnosdb-isipho && cargo build`

Expected behavior

Build successfully without error.

Actual behavior

Could not build it due to that missing type

System info

```
$ uname -a
Linux pop-os 5.17.15-76051715-generic #202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux

$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35
```

**Comment by Subsegment** [comment]
fixed
