### ISSUE TITLE
[Feature]Some works lacking in db-file reading/writing

### ISSUE THREAD

**Issue by oyzg** [cnosdb/cnosdb#440]
Still some works lacking:

1. A file-based index reader, for reading huge db-file index.
2. An other db-file writer for writing huge streaming write requests.
3. Writing db-file should be atomic, db-file writer should write to tmp file first, when write successes,move them to db-file.

Originally posted by @zipper-meng in [#76](https://github.com/cnosdb/cnosdb-isipho/pull/76#issuecomment-1178882497)

**Comment by cnoshb** [comment]
宕机删除在生成tsm文件过程中的临时数据, 删除compact之后的数据,以及不在levelinfo中的数据.
