### ISSUE TITLE
[Bug]parallel kvcore test will panic 

### ISSUE THREAD

**Issue by oyzg** [cnosdb/cnosdb#441]
**Describe the bug**
parallel kvcore test will panic，we add serial for each test，the test will pass

**To Reproduce**
cargo test --package tskv --lib kvcore::test

**Expected behavior**
should parallel

**Additional context**
none

**Comment by zipper-meng** [comment]
Maybe a directory conflict caused that, and it will make some impossible to pass test case passed.

**Comment by roseboy-liu** [comment]
Is there any describtion about this bug report？ @Subsegment

**Comment by Subsegment** [comment]
done @roseboy-liu
