### ISSUE TITLE
[Bug]Recover from wal will miss data in memcache

### ISSUE THREAD

**Issue by Subsegment** [cnosdb/cnosdb#458]
When the first half points of a batch are written to the memcache causing the memcache to be full, it happens that after this memcache is converted to imut-memcache, the imut-memcache is full, thus starting to flush, and since flush will record the current maximum seq into summary, if At this time, if we stop, when we recover, wal sees that the largest seq in gloable-context is the previous batch, and wal starts recovering from seq+1 of gloable-context, which leads to the loss of points in the second half of this batch

At present, the wal is temporarily changed to recover from the seq of gloable-context, which will not lose data, but will lead to redundant data and needs to be optimized.

Chinese original:
当一个batch的前半段points写入memcache时导致memcache满了，恰好这个memcache转为imut-memcache后，imut-memcache满了，从而开始进行flush，由于flush会将当前最大的seq记录到summary中，假如此时停机，恢复时，wal看到gloable-context中最大的seq为之前的那个batch，而wal又是从gloable-context的seq+1开始恢复，从而导致这个batch的后半段的points丢失

目前暂时将wal改为从从gloable-context的seq开始恢复，这样虽然不会丢失数据，但会导致冗余数据，需要进行优化。

**Comment by roseboy-liu** [comment]
https://github.com/cnosdb/cnosdb/pull/562
