### ISSUE TITLE
[Feature] Support time series file export to parquet file 

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#467]
**Is your feature request related to a problem? Please describe.**
Support time series file export to parquet file  

**Describe the solution you'd like**
time series file export to parquet file  
https://parquet.apache.org/docs/
**Describe alternatives you've considered**
nothing
**Additional context**
nothing

**Comment by cnoshb** [comment]
interface and query support.

**Comment by cnoshb** [comment]
interface and query support.
