### ISSUE TITLE
[User]Compile issue need help

### ISSUE THREAD

**Issue by xin321** [cnosdb/cnosdb#475]
Hello, in docs/get-started.md document in the last step git clone https://github.com/cnosdb/cnosdb-isipho.git && cd cnosdb-isipho following address I can not pull, and then I pulled https://github. com/cnosdb/cnosdb.git, cargo build and then run the error as follows
![image](https://user-images.githubusercontent.com/39756791/179779372-a3a08b3c-5f2d-46fa-baaf-da68b25a0e5c.png)
Can you tell me what the cause is?

Chinese original:
您好，在docs/get-started.md文档中最后一步git clone https://github.com/cnosdb/cnosdb-isipho.git && cd cnosdb-isipho如下地址我无法拉取，而后我拉取了https://github.com/cnosdb/cnosdb.git，cargo build后运行报错如下
方便问一下大概是什么原因嘛

**Comment by roseboy-liu** [comment]
Thank you for your report, as it mentioned "not yet implemented"

**Comment by cnoshb** [comment]
The whole project is still in progressing, we will post when it's ready :) thanks! @xin321

**Comment by roseboy-liu** [comment]
done
