### ISSUE TITLE
ROADMAP 2022

### ISSUE THREAD

**Issue by yuandongs** [cnosdb/cnosdb#483]
# Main Tasks

Status:

* TODO
* DESIGN
* DOING
* DONE

##  Storage

|Task |SubTask|Status| Comments|
|-|-|-|-|
|WAL||DONE|#458 #450 |
|MemTable|Mutable|DONE|#446 #496 #497 #499|
|MemTable|Immutable|DONE|#499|
|MemTable|Flush|DONE|||
|TSM|||#453 #440 |
|TSM|Summary|DONE|#495|
|TSM|Tsfamily|DONE|||
|TSM|Compression|DONE|||
|TSM|Compaction|DONE|#464 #433 |
|VersionSet|||||
|Interface|Write|DONE|||
|Interface|Read|DONE|||
|Interface|Delete(Points)|DONE|||
|Interface|Drop(DB/Measurement/Shard)|TODO||
|Index|forward Index|DOING|||
|Index|Inverted Index|DESIGN|||
|Index|Custom Index|TODO|||
|Config Manager||DONE|||

## Query

|Task |SubTask|Status| Comments|
|-|-|-|-|
|Arrow|Catalog Provider|DOING|#445|
|Arrow|Recordbatch|DOING|#443|
|Arrow|Schema Storage|DONE|||
|DML|Insert Support|DOING|#538|
|Executor|Table Scan|DESIGN||
|Optimizer|Statistics|DESIGN||

## Metadata Manager

|Task |SubTask|Status| Comments|
|-|-|-|-|
|Schema||DESIGN||

## Basic Lib

|Task |SubTask|Status| Comments|
|-|-|-|-|
|fs||TODO||
|Run-to-Completion Model||TODO||
|Trace Module||DOING|||

## Distributed

|Task |SubTask|Status| Comments|
|-|-|-|-|
|Design|Distributed architecture|TODO|||
|Design|computational-storage separation|TODO|||
|Sharding|Consistent Hashing|TODO|#498|
|Scale Out|Data Migration|TODO||
|Replica|Eventual Consistency|TODO||
|Replica|Fail Over|TODO||

# Backup

|Task |SubTask|Status| Comments|
|-|-|-|-|
|Single Instance||TODO||
|Cluster||TODO||
|Check Point||TODO||
|Incremental Backup||TODO||
|Full Backup|Logical|TODO||
|Full Backup|Physical|TODO||

## Eco

|Task |SubTask|Status| Comments|
|-|-|-|-|
|Line Protocol|Export|TODO||
|Line Protocol|Import|DESIGN|#466|
|Parquet|Export|DESIGN|#467|
|Data Interface|Telegraf|TODO||
|Data Interface|Influx|TODO||
|Data Interface|Prometheus|TODO||
|Data Interface|Timescales|TODO||
|Data Interface|Kafka/Pulsar|TODO||
|Data Interface|MySQL/PostgreSQL|TODO||
|Disk files analysis tools||TODO||

## Testing

|Task |SubTask|Status| Comments|
|-|-|-|-|
|Unit Test||DOING||
|Intergration Test/System Test||DOING|#425|
|Stress Test||DOING||
|Benchmark||TODO||
|Chaos Engineer||DESIGN||

**Comment by yuandongs** [comment]
1. Only issues that are currently open are filled in.
2. The Issue tagged with "Optimization" is basically not filled in.
3. @roseboy-liu  is required to fill in the status of each item

**Comment by roseboy-liu** [comment]
> 1. Only issues that are currently open are filled in.
> 2. The Issue tagged with "Optimization" is basically not filled in.
> 3. @roseboy-liu  is required to fill in the status of each item
updated
