### ISSUE TITLE
[Feature] Refector 'TimeRange' struct 

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#490]
**Is your feature request related to a problem? Please describe.**
some code use（min max）as timerange， some use ’timerange' directly

**Describe the solution you'd like**
Unified time range operation 
**Describe alternatives you've considered**
Unified time range operation 
**Additional context**
no

**Comment by zipper-meng** [comment]
All those fields (not function arguments or variables) who is a `TimeRange`, a better way is to name them 'time_range'.

**Comment by roseboy-liu** [comment]
done
