### ISSUE TITLE
[Feature]Add the Pre-write mechanism to the write time and add batch logic

### ISSUE THREAD

**Issue by cnoshb** [cnosdb/cnosdb#497]
**Is your feature request related to a problem? Please describe.**
At this stage, the pre-write in memory is not the logic of batch, and the write speed in the system will be affected.

**Describe the solution you'd like**
Add the logic of batch in the in-memory pre-write to improve the write speed.

**Describe alternatives you've considered**
Keep the status quo, but not a best practice.

**Additional context**
N.A

**Comment by bartliu827** [comment]
done
