### ISSUE TITLE
[Feature][Design]tskv coordinator 

### ISSUE THREAD

**Issue by cnoshb** [cnosdb/cnosdb#498]
Things need to design at this time:

**Shad management strategy**
How shad information is maintained.
What shad information contains.   

**Management process**
The process of writing and reading data.

**Interaction with meta nodes**
How to to obtain shad information

**Comment by roseboy-liu** [comment]
https://alidocs.dingtalk.com/i/team/1pMzNxqv8lLdDmBn/docs/1pMzNRByDpZJezBn
