### ISSUE TITLE
[Feature] version need improvement 

### ISSUE THREAD

**Issue by cnoshb** [cnosdb/cnosdb#499]
related #446 
**Is your feature request related to a problem? Please describe.**
At this stage, when version management is performed, the system utilizes the existing version, and this receives read and write locks globally, which is affecting the overall efficiency.

**Describe the solution you'd like**
Change to super version, version needs to go to the hierarchy.

**Describe alternatives you've considered**
Keep the status quo, but not a best practice.

**Additional context**
N.A

**Comment by zipper-meng** [comment]
Removed RwLock for version: https://github.com/cnosdb/cnosdb/pull/524

**Comment by zipper-meng** [comment]
For these reasons, I will close this PR.
