### ISSUE TITLE
[Feature]Manual Compaction in CnosDB

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#530]
**Is your feature request related to a problem? Please describe.**
Use Case:
I am dumping large number of data into the database just for once and there won't be any new write. I would like to see the compaction will be kicked off.

**Describe the solution you'd like**
Similar to [Caddsandra's compact tool](https://cassandra.apache.org/doc/latest/cassandra/tools/nodetool/compact.html), could we have the manual compaction tool in CnosDB?

**Describe alternatives you've considered**
Not sure about the default compaction strategy? 
Is it size tiered compaction, where you need to have at least some number of file or of similar size to trigger the compaction?
Or is it write-time based compaction, where if there is no new write for a certain of time, the compaction process will be kicked off?

**Additional context**
In the tool, could I also specify the database, compaction level as the arguments?

**Comment by cnoshb** [comment]
This is a nice feature that makes it easy for administrators to compress files manually. We can also add policies, such as making a compression of the whole shard after a period of no writes.

**Comment by yuandongs** [comment]
A case from NetEase：https://zhuanlan.zhihu.com/p/70132319

![image](https://user-images.githubusercontent.com/105193556/183621419-fa276d27-f163-4a10-ba28-3a1d5dae00bb.png)
![image](https://user-images.githubusercontent.com/105193556/183621668-24b5f911-a0bf-4a5c-a7c0-1cb0f8c39fd5.png)

By adjusting the parameters of RocksDB, they limit the frequency of Compaction during the peak business period in the daytime and concentrate Compaction in the low business period at night, so as to ensure the business processing capacity in the daytime.

**Comment by cnoshb** [comment]
Add cmd. @zipper-meng
