### ISSUE TITLE
[Feature] Support aggregate function MODE

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#553]
**Is your feature request related to a problem? Please describe.**
returns the non-null value or values that occur most often in a specified expression

**Describe the solution you'd like**

- Syntax
```sql
MODE( expr ) -> int64
```

- Arguments
expr: This expression produces the values that are searched to find the most frequent value. 

- sql implemention
```
select count(time) as mode
 from tbl
 group by tenant
 order by mode desc
 limit 1;
```

**Describe alternatives you've considered**

**Additional context**

Notes
> support window
> support any data type

The mainstream database supports MODE show below:

InfluxDB
https://docs.influxdata.com/flux/v0.x/stdlib/universe/mode/

Snowflake
https://docs.snowflake.com/en/sql-reference/functions/mode.html

PostgreSQL
https://www.postgresql.org/docs/14/functions-aggregate.html

H2
http://www.h2database.com/html/functions-aggregate.html#mode

InfluxDB
https://docs.influxdata.com/flux/v0.x/stdlib/universe/mode/

**Comment by yukkit** [comment]
> /assignme

Thanks,https://github.com/cnosdb/cnosdb/blob/main/query_server/query/src/extension/expr/aggregate_function/README.md may be useful to you

**Comment by g302ge** [comment]
I am read some doucuments of Datafusion. Besides, this issue I think I can write a simple guide document for developer to work with aggrate operaters

**Comment by yukkit** [comment]
This PR has not been processed for a long time, assign it to me
