### ISSUE TITLE
[Feature] Support bulk load

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#593]
**Is your feature request related to a problem? Please describe.**
We might need to load big chunk of historical data into a database once in a while. Sources of bulk load could rang from tons of CSV files to TB-size MySQL instance to other databases. Bulk inserting via traditional RESTful API might not be in its best performance.

**Describe the solution you'd like**
Having a **bulk load** in several ways should do the work:

1. SQL: LOAD DATA statement, similar to [MySQL style](https://dev.mysql.com/doc/refman/8.0/en/load-data.html)
2. CMD: loaddata command line, similar to [mysqlimport](https://dev.mysql.com/doc/refman/8.0/en/mysqlimport.html)
3. SDK: provides support in several popular languages including Java, .NET

The feature should have such capabilities:

1. Write data via gRPC instead of RESTful
2. Write data to single instance or cluster at their best performance, meaning fully utilizing their resources. Concurrency should be supported and configurable.

**Describe alternatives you've considered**
Write bulk data in individual INSERT statements. But this is slow. 

**Additional context**
There are several pros for gRPC over REST: 

> Protocol buffers, which gRPC comes out of the box with, support more data types than JSON, and it’s significantly faster, thanks to its optimized binary format. gRPC serializes data in binary format (protocol buffers), which is much faster than REST’s JSON, giving gRPC a greater performance advantage.

> gRPC performs load balancing so that client requests are evenly distributed across servers to avoid overloading a particular server. This improves the overall performance of your application. The load balancing feature, as well as the fact that gRPC uses HTTP2 by default, makes latency in gRPC much lower than in REST APIs.

**Comment by cnoshb** [comment]
Yes, I agree gRPC is better than RESTful in several aspects. 
I'd like to add this feature into October or November Millstone. 
We can first start with cmd and sql, because we will support "insert" in SQL few moment later, and we can figure out SDK later with Cnos eco built. 
Thanks @muninshen

**Comment by muninshen** [comment]
QuestDB has similar but simpler (still under development) statement called [COPY ](https://questdb.io/docs/guides/importing-data/#import-csv)and it has a nice [status tracking](https://questdb.io/docs/guides/importing-data/#track-import-progress) feature.

**Comment by yukkit** [comment]
## copy into table
```
COPY INTO [<database>.]<table_name> [ ( <target_col_name> [ , ... ] ) ]
FROM externalLocation
[ CONNECTION = ( connection_options ) ]
[ FILE_FORMAT = ( TYPE = { 'CSV' | 'NDJSON' | 'PARQUET' | 'AVRO' } [, formatTypeOptions ] ) ]
[ COPY_OPTIONS = copyOptions ]
```

### externalLocation (for Amazon S3)
```
externalLocation (for Amazon S3) ::=
  's3://<bucket>[/<path>]'
connection_options ::=
  [ endpoint_url = '<string>' ]
  [, region = '<string>' ]
  [, access_key_id = '<string>' ]
  [, secret_key = '<string>' ]
  [, token = '<string>' ]
  [, virtual_hosted_style = true | false ]
```

### externalLocation (for Google Cloud Storage)
```
externalLocation (for Google Cloud Storage) ::=
  'gcs://<bucket>[/<path>]'
connection_options ::=
  [ gcs_base_url = '<string>' ]
  [, disable_oauth = true | false ]
  [, client_email = '<string>' ]
  [, private_key = '<string>' ]
```

### externalLocation (for Microsoft Azure)
```
externalLocation (for Microsoft Azure) ::=
  'azblob://<container>[/<path>]'
connection_options ::=
  [ account = '<string>' ]
  [, access_key = '<string>' ]
  [, bearer_token = '<string>' ]
```

### formatTypeOptions
```
formatTypeOptions ::=
   -- all
   FILE_COMPRESSION_TYPE = '<compression>'
   -- csv
   DELIMITER = '<character>'
   WITH_HEADER = true | false
```

## e.g.

- /tmp/tests/data/csv/full_data_type.csv
```
time,tag1,tag2,bigint_c,string_c,ubigint_c,boolean_c,double_c
2022-12-22 09:26:56,tt1,tt2,-512512,hello word,512,true,1.11
```

- create inner table
```
CREATE TABLE inner_csv(
    bigint_c BIGINT,
    string_c STRING,
    ubigint_c BIGINT UNSIGNED,
    boolean_c BOOLEAN,
    double_c DOUBLE,
    TAGS(tag1, tag2)
    );
```

- copy into table
```
COPY INTO inner_csv
FROM '/tmp/tests/data/csv/full_data_type.csv'
file_format = (type = 'csv');
```
### from s3

#### required

- There is an '/data/csv/full_data_type.csv' file in the 'cnosdb-query-test' bucket in the 'us-west-2' region on s3

```
copy into inner_csv
from 's3://cnosdb-query-test/data/csv/full_data_type.csv'
connection = (
  access_key_id = 'ABCDEFG',
  secret_key = 'BNMLKJ/LKJHG',
  region = 'us-west-2'
)
```

## Notice

- The schema of the external file is automatically inferred
- You can choose which columns to insert by specifying the column names after table name
- The task will be interrupted when there is an illegal record
