### ISSUE TITLE
[Refactor] Modify fieldid typename from u32 to FieldId 

### ISSUE THREAD

**Issue by ZuoTiJia** [cnosdb/cnosdb#613]
**Describe the issue**
The u32 and u64 types on the kv interface are confusing and require easy to understand naming

**Comment by ZuoTiJia** [comment]
There are also some unclear u32, u64, String, need to add comments, or use type syntax.

<img width="692" alt="Screen Shot 2022-10-21 at 13 29 01" src="https://user-images.githubusercontent.com/49109132/197120023-c5895f77-8783-483b-9272-2d70d0114ae3.png">
<img width="688" alt="Screen Shot 2022-10-21 at 13 29 23" src="https://user-images.githubusercontent.com/49109132/197120118-8d84c4bf-d82e-41e6-a19e-c8110b733657.png">
<img width="690" alt="Screen Shot 2022-10-21 at 13 29 52" src="https://user-images.githubusercontent.com/49109132/197120128-14b08145-0088-47d3-9185-1cf53cc9fb4b.png">

**Comment by roseboy-liu** [comment]
@ZuoTiJia   check it
