### ISSUE TITLE
[Feature]Configurable Data Compaction Algorithm

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#616]
**Is your feature request related to a problem? Please describe.**
**Compaction Algorithm** in CnosDB is like a box of chocolates. You never know what you're gonna get... kidding
Nevertheless, **Compaction Algorithm** is still a black box to us and we would like to configure it based on our own understanding of dataset.

**Describe the solution you'd like**
Similar to commercial version of Cassandra [here](https://docs.datastax.com/eol/en/dse/6.0/dse-admin/datastax_enterprise/operations/opsConfigCompress.html), we could have **WITH compaction** keyword: 

1. Disable compaction via CREATE SQL: `CREATE TABLE DEMO(...) WITH compaction= { 'enabled' : false }; `
2. Enable compaction via CREATE SQL: `CREATE TABLE DEMO(...) WITH compaction= { 'class' : 'LZ4Compressor' }; `
3. Disable compaction via ALTER TABLE SQL: `ALTER TABLE DEMO WITH compaction= { 'enabled' : false }; `
4. Enable compaction via ALTER TABLE SQL: 
`ALTER TABLE DEMO WITH compaction ={ 'class' : 'LZ4Compressor' };  `
`ALTER TABLE DEMO WITH compaction ={ 'class' : 'DeflateCompressor', 'chunk_length_in_kb' : 64 };  `

Or you could try MariaDB way, using **COMMENT** keyword [here](https://mariadb.com/docs/service-management/operations/storage-management/enterprise-columnstore/configure-compression/):
1. Set Global Compaction Type in configuration file: `columnstore_compression_type=LZ4`
2. Set Table Compaction Type in SQL's COMMENT: `CREATE TABLE DEMO(...) COMMENT 'compression=3';`
3. Set Column Compaction Type in SQL's COMMENT: 
```
CREATE TABLE DEMO(
    invoice_id BIGINT UNSIGNED NOT NULL,
    invoice_total DECIMAL(13, 2) COMMENT 'compression=3',
);
```

**Describe alternatives you've considered**
We could disable compaction once for all in the configuration instead of DDL but DDL provides more granular way.

**Additional context**
More granularity should be provided as well: 
1. Global
2. Database
5. Table

This feature should be integrated in the cloud version as well.

Other alternatives:
1. TecentCloud's COMPRESSED keyword: https://www.tencentcloud.com/document/product/236/43480
2. ClickHouse's CODEC keyword: https://clickhouse.com/docs/en/sql-reference/statements/create/table#column-compression-codecs

**Comment by roseboy-liu** [comment]
Good issue，we will support configurable data compression algorithm by create table stmt。

**Comment by cnoshb** [comment]
Link to #620 
check this out.

**Comment by cnoshb** [comment]
#619 #620

**Comment by Subsegment** [comment]
```
CREATE TABLE IF NOT EXISTS test(
            column1 BIGINT CODEC(DELTA),
            column2 STRING CODEC(GZIP),
            column3 BIGINT UNSIGNED CODEC(NULL),
            column4 BOOLEAN,
            column5 DOUBLE CODEC(GORILLA),
            TAGS(column6, column7))
```

**Comment by roseboy-liu** [comment]
done
