### ISSUE TITLE
[Feature]Support Swinging Door Algorithm in Lossy Compression

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#637]
**Is your feature request related to a problem? Please describe.**
Many traditional Historians products such as OSISoft's PI, Honeywell's PHD, GE's Proficy support  Swinging Door Algorithm in Lossy Compression so as to reduce data.
Modern TSDB aiming for IoT use case should support this algorithm as well.

**Describe the solution you'd like**

> The Swing Door Trending (SDT) is an online and lossy data compression algorithm traditionally used in Supervisory Control and Data Acquisition (SCADA) systems aiming to store historical data from process information systems (PIMs). SDT has low computational complexity and uses a linear trend to represent a quantity of data. Its most important parameter is the compression deviation (CD) that represents the maximum difference between the current sample and the current linear trend used to represent the data previously collected.

Swinging Door Algorithm is explained [here](https://docs.osisoft.com/bundle/pi-server/page/compression-testing.html) and [here](https://www.alibabacloud.com/blog/using-the-swinging-door-trending-algorithm-in-postgresql_595129).

Four parameters might need to be configurable for the algorithm:

1. **T min** in Nanoseconds: Minimum interval between two archived values, positive integer
2. **T max** in Nanoseconds: Maximum interval between two archived values, positive integer
3. **Deviation** in Process value unit:  Absolute or relative value of the deviation that is permitted when calculating the gradient using the algorithm; base value is the last process value saved, positive floating point number
4. **Value range** in Process value unit: Specified by the high and low limit of compression distribution; relevant only with relative (percentile) deviation. The input of limit values is deactivated in the case of absolute deviation. Consistent positive or negative integer

See more details [here](https://support.industry.siemens.com/cs/mdm/73506085?c=46159586187&lc=en-IE).

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ZhenChen008** [comment]
Does CnosDB now support lossy compression algorithms, and if not, what is the maximum compression ratio?
“请问CnosDB现在支持有损压缩算法了吗，如果没有的话目前压缩比最大是多少呢？”

**Comment by Benxiaohai001** [comment]
https://github.com/cnosdb/cnosdb-enterprise/pull/89

**Comment by Subsegment** [comment]
done
