### ISSUE TITLE
[Feature]Support Deadband Compression in Lossy Compression

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#638]
**Is your feature request related to a problem? Please describe.**
Deadband Compression is widely used in Lossy Compression due to its easy implementation and low system overhead. It's faster than Swinging Door but consums more storage space than the latter.

**Describe the solution you'd like**
The algorithm is straightforward: "If a point’s value exceeds the configured deadband range, it will be discarded". See more details [here ](https://softwaredocs.weatherford.com/cygnet/94/Content/Topics/History/History%20Deadband%20Compression.htm)and [there](https://www.ge.com/digital/documentation/historian/version71/INDI3MGU4YjEtMDhlZC00YzA0LThhOWQtYjViODM5NDhlZTI2.html).

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Benxiaohai001** [comment]
https://github.com/cnosdb/cnosdb-enterprise/pull/89

**Comment by Subsegment** [comment]
done
