### ISSUE TITLE
[Feature] Implement Information_Schema

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#642]
**Is your feature request related to a problem? Please describe.**

- docs: Investigate the system tables required by the time series database
- Store information through read-only memory tables
- Information_Schema is at the same level as database
- Each user has their own Information_Schema

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cnoshb** [comment]
Consider about the requirement from cloud side, thx.

**Comment by yukkit** [comment]
already merge, close
