### ISSUE TITLE
[Feature]Report the total duration for a given state

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#649]
**Is your feature request related to a problem? Please describe.**

For any sensor data with multiple states, it's common to ask how long does the sensor spent on each state. It's informative to tell when a system went into alert state, for how long it was in alert, and how many times there were new alerts coming up in a certain period.

e.g.:

DevOps: 

1. How much time the CPU spent on READY/WAITING/RUNNING state?
2. How much time the database instance spent on READING/INSERTING state?

IoT: OEE calculations, machine protection, maintenance, etc.

1. How much time a heat pump spent heating water/warming/cooling the house?
2. How much time I spent at home/away?
3. How long was the TV on?
4. how much time my solar charge controller has been in any state?

**Describe the solution you'd like**
Let's reuse [this example](https://docs.timescale.com/api/latest/hyperfunctions/frequency-analysis/duration_in/).

Sample data (timestamp and state):

```
1/1/2020 10:00   starting
1/1/2020 10:30   running
1/3/2020 16:00   error
1/3/2020 18:30   starting
1/3/2020 19:30   running
1/5/2020 12:00   stopping
```

If we would like to know how much time the IoT device spent on each state on **1/1/2020**, the result would be:

```
starting    30m      (from 1/1/2020 10:00 to 10:30)
running     809m     (from 1/1/2020 10:30 to 23:59)
```

If we would like to know how much time the IoT device spent on each state btw **1/1/2020** and **1/3/2020**, the result would be:

```
starting    90m      (from 1/1/2020 10:00 to 10:30 and from 1/3/2020 18:30 to 19:30)
running     1078m    (from 1/1/2020 10:30 to 23:59 and from 1/3/2020 19:30 to 23:59)
error       150m     (from 1/3/2020 16:00 to 18:30)
```

If we would like to know how much time the IoT device spent on each state btw **1/1/2020** and **1/5/2020**, the result would be:

```
starting    90m      (from 1/1/2020 10:00 to 10:30 and from 1/3/2020 18:30 to 19:30)
running     3238m    (from 1/1/2020 10:30 to 23:59 and from 1/3/2020 19:30 to 23:59 and from 1/4/2020 00:00 to 23:59 and from 1/5/2020 00:00 to 12:00)
error       150m     (from 1/3/2020 16:00 to 18:30)
stopping    719m     (from 1/5/2020 12:00 to 23:59)
```

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by roseboy-liu** [comment]
Good issue
