### ISSUE TITLE
[Feature]Have a function to report storage size of each database objects

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#665]
**Is your feature request related to a problem? Please describe.**
It's easy to find out the size on disk of ALL data in a database instance as long as we know the data directory with **du -sh**.
But it's unclear to do this for a database, or a table because the data doesn't seem organized in the file system by database or table.

Besides, we need this kind of report regularly so that we can monitor the storage size growth so to plan the capacity.

**Describe the solution you'd like**
Have a function to list out the storage size of each objects in the database instance:

- database
- table
- shard/region/partition

**Describe alternatives you've considered**
**du -sh** would do some work but it's cumbersome 

**Additional context**
NA

**Comment by Subsegment** [comment]
finish in metrics
