### ISSUE TITLE
[Feature] Schema Query Statements

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#675]
**Is your feature request related to a problem? Please describe.**
support those schema query statements

- [x] DESCRIBE DATABASE db_name; 
- [x] DESCRIBE TABLE [db_name.] table_name; 
- [x]  SHOW DATABASES; 
- [x]  SHOW TABLES [ON <db_name>]; 
- [x]  SHOW SERIES [ON <db_name>] FROM table_name [WHERE <tag_key>  <operator> [ '<tag_value>' | <expression>]] [LIMIT_clause] 
- [x] SHOW TAG VALUES [ON <db_name>] FROM table_name WITH KEY [ [<operator> "<tag_key>" | <regular_expression>] | [IN ("<key1>"]   [WHERE <tag_key> <operator> ['<tag_value>' | <expression>]] [LIMIT_clause]

**Comment by cnoshb** [comment]
added @zkkxu to assignees
