### ISSUE TITLE
[QUESTION] compile error

### ISSUE THREAD

**Issue by guoxiangCN** [cnosdb/cnosdb#691]
compile the cnosdb following the get-started page:
error reported:
type `Scalar` is not a member of trait `flatbuffers::EndianScalar`
--> common/protos/src/generated/flatbuffers_generated/models.rs:106:9
    |
106 |         type Scalar = i32;
    |         ^^^^^^^^^^^^^^^^^^ not a member of trait `flatbuffers::EndianScalar`

**Comment by Subsegment** [comment]
Using FlatBuffer version 2.0.6 may solve this problem

**Comment by guoxiangCN** [comment]
> Using FlatBuffer version 2.0.6 may solve this problem

resoved, thx~
