### ISSUE TITLE
Add feature reporttsi

### ISSUE THREAD

**Issue by GikaWong** [cnosdb/cnosdb#73]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Use case**
Why is this important (helps with prioritizing requests)?

**Comment by IvanGao01** [comment]
report-tsi

The report does the following:

Calculates the total exact series cardinality in the database.

Segments that cardinality by measurement, and emits those cardinality values.

Emits total exact cardinality for each shard in the database.

Segments for each shard the exact cardinality for each measurement in the shard.

Optionally limits the results in each shard to the “top n”.

The report-tsi command is primarily useful when there has been a change in cardinality and it’s not clear which measurement is responsible for this change, and further, when that change happened. Estimating an accurate cardinality breakdown for each measurement and for each shard will help answer those questions.

Syntax

cnosdb_inspect report-tsi --db-path <path-to-db> [ options ]


Options

Optional arguments are in brackets.

--db-path <path-to-db>

The path to the database.

[ --top <n> ]

Limits the results to the top specified number within each shard.

Performance

The report-tsi command uses simple slice/maps to store low cardinality measurements, which saves on the cost of initializing bitmaps. For high cardinality measurements the tool uses [roaring bitmaps](https://roaringbitmap.org/), which means we don’t need to store all series IDs on the heap while running the tool. Conversion from low-cardinality to high-cardinality representations is done automatically while the tool runs.
