### ISSUE TITLE
Duplicate field won't trigger an error during CREATE TABLE process

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#736]
**Describe the bug**
A duplicate field was put in the CREATE TABLE statement by accident but the engine didn't flag it as an invalid input until I am trying to pull the data from that table.

**To Reproduce**
```
CREATE DATABASE oceanic_station;
\c oceanic_station

SHOW TABLES;
CREATE TABLE air (
    visibility DOUBLE,
    temperature DOUBLE,
    presssure DOUBLE,
    presssure DOUBLE,
    TAGS(station)
);

SHOW TABLES;
SELECT * FROM air;
```

**Expected behavior**
An error message should be flagged to stop me create such table.

**Additional context**
See screenshot here.
![image](https://user-images.githubusercontent.com/93336160/199505752-15e04f42-efa4-483b-8815-786969801157.png)

**Comment by Subsegment** [comment]
#739
