### ISSUE TITLE
Duplicate tag won't trigger an error during CREATE TABLE process

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#737]
**Describe the bug**
A duplicate tag was put in the CREATE TABLE statement by accident but the engine didn't flag it as an invalid input until I am trying to pull the data from that table.

**To Reproduce**
```
CREATE DATABASE oceanic_station;
\c oceanic_station

SHOW TABLES;
CREATE TABLE air (
    visibility DOUBLE,
    temperature DOUBLE,
    presssure DOUBLE,
    TAGS(station,station)
);

SHOW TABLES;
SELECT * FROM air;
```

**Expected behavior**
An error message should be flagged to stop me create such table.

**Additional context**
See screenshot here.
![image](https://user-images.githubusercontent.com/93336160/199506607-9c2d881a-26a6-4904-b8e2-2ce9984d83b2.png)

**Comment by Subsegment** [comment]
#739
