### ISSUE TITLE
Inconsistent output and wrong ORDER BY sorting for query with LIMIT

### ISSUE THREAD

**Issue by muninshen** [cnosdb/cnosdb#772]
**Describe the bug**
A query **without** LIMIT should be the superset of that **with** LIMIT. However, it may not be the case in CnosDB V2.0.1.

**To Reproduce**

1. Download sample data via the [quickstart](https://docs.cnosdb.com/guide/query/sql.html)
2. Run the query below. Then you can see there are 13 records:
```
SELECT * FROM air ORDER BY time;
```
![image](https://user-images.githubusercontent.com/93336160/202372591-63362468-de07-4aa7-94cc-6b2b47545885.png)
3. Then limit the result within 13 records. Then you see the result is consistent:
```
SELECT * FROM air ORDER BY time LIMIT 13;
```
![image](https://user-images.githubusercontent.com/93336160/202373094-0c24d531-d12e-4527-8f0b-98fdd33e4428.png)
4. Then try 12 and it should be all consistent. However, then limit the result within 11 records. Then you see the first two are not in the right order:
```
SELECT * FROM air ORDER BY time LIMIT 11;
```
![image](https://user-images.githubusercontent.com/93336160/202373610-3bc3a0d4-96ad-423b-bb39-8f7d9cff6b2f.png)
5. Similar issue happens to when order by station as well:
 
![image](https://user-images.githubusercontent.com/93336160/202374583-f3daf18d-a25b-4a1d-af27-0237ed8c06c4.png)

**Expected behavior**
The result should be consistent across different LIMIT scope and ORDER BY should sort in the given order.

**Additional context**

**Comment by yukkit** [comment]
This is expected in a parallel computing engine

The results returned by order by and limit in this issue are not fixed.

The order by operation is divided into two stages, partial sort and merge sort. Partial sort is a parallel operation, and merge sort is a single-threaded operation. It can only guarantee the order of sorted keys, but not the order of non-sorted keys, and , this operation is executed in parallel, so the result of the merge sort operation is unstable on non-sorted keys

The limit operation is completed in two stages, one is the parallel limit, and the other is the final limit, so the result of this operation is random.

**Comment by yukkit** [comment]
@muninshen If there is no problem, I will close this issue
