### ISSUE TITLE
[Improve] The index file is too large

### ISSUE THREAD

**Issue by Subsegment** [cnosdb/cnosdb#773]
**Is your feature request related to a problem? Please describe.**
A few decades mb file will build hundreds of index file

**Describe the solution you'd like**

- Compress our write data
- Investigate the configuration of sled

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by cnoshb** [comment]
Discuss if we need create a new index engine to replace sled.

**Comment by cnoshb** [comment]
Replaced Sled and this issue solved.
