### ISSUE TITLE
[Feature] Protocol transform service

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#777]
**Is your feature request related to a problem? Please describe.**
- [x]   Transform line protocol write request / promethus write  request/ opentsdb write request /  to priavate protocol use grpc service.  
- [x]  Support MQ import data, such as MQTT and Kafka protocol.
- [x]  Support service exposed on the cnosdb cloud as a service.
- [x]  Grpc Service for write path need to support  user authentication

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cnoshb** [comment]
#593 check with #777 together. @zipper-meng

**Comment by cnoshb** [comment]
Finished function.
