### ISSUE TITLE
Add Java SDK |添加Java SDK

### ISSUE THREAD

**Issue by jcy20000106** [cnosdb/cnosdb#8]
# In English | [中文版](#chinese)
### Add Java SDK 

<h1 id="chinese">中文版</h2>

### 添加 Java SDK

**Comment by IvanGao01** [comment]
I think we should develop SDK for mainstream programming languages, not only Java, but also Golang, python, rust and so on

I'll list the SDK programming languages that need to be developed at present here. If there are new idea, I can add them

- Java
- Golang
- Rust
- Python
- C++

**Comment by IvanGao01** [comment]
Link these issue:
Java SDK #112  is Closed
Golang SDK #111 is Closed
