### ISSUE TITLE
[Feature] Add operation command

### ISSUE THREAD

**Issue by roseboy-liu** [cnosdb/cnosdb#806]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
SQL command
- [x] Move Vnode [vnode_id] to Node [node_id]
- [x] Copy Vnode [vnode_id] to Node [node_id]
- [x] Drop Vnode [vnode_id]
- [x] Compact Vnode [vnode_id1, vnode_id2...]

**Describe alternatives you've considered**

**Additional context**

**Comment by zipper-meng** [comment]
All tasks of this issue was done.
