### ISSUE TITLE
[Feature] A series of use cases on AI and other scenarios.

### ISSUE THREAD

**Issue by DjangoPeng** [cnosdb/cnosdb#834]
Generally Speaking, various use cases are really helpful for beginners to learn new a tool. 

Therefore, we should provide some practical code examples to show how to use CnosDB. 

For me, I would like to know how to use the data stored in CnosDB to train AI models, such as common forecasting problems (house sales prices, website traffic, etc.).

I am willing to contribute an example of forecasting house sales prices first.

How about making a top folder named `examples`?

**Comment by Subsegment** [comment]
It looks OK, and directory name is tensorflow_ examples or numpy_examples might be better

**Comment by Subsegment** [comment]
Good, Thanks

**Comment by DjangoPeng** [comment]
I find an interesting tutorials of TensorFlow.

> This tutorial is an introduction to time series forecasting using TensorFlow. It builds a few different styles of models including Convolutional and Recurrent Neural Networks (CNNs and RNNs).

It seems like more suitable for cnosdb which aiming to manage time series data.

I'll create a PR ASAP.

**Comment by DjangoPeng** [comment]
We have a WIP PR here https://github.com/cnosdb/cnosdb/pull/944

**Comment by Subsegment** [comment]
finish
