### ISSUE TITLE
[Feature] Support table without tags.

### ISSUE THREAD

**Issue by DjangoPeng** [cnosdb/cnosdb#843]
The design goal of `Tag` in TSDB is to achieve high-efficient querying. 

Tag allows data points to be grouped or filtered by specific characteristics, such as location, device, or sensor, making it easier to analyze and understand the data. 

In the use case of AI, this is similar to data cleaning stage work. 

However, in the scenario of model training and prediction, it is usually streamingly loading batch data or loading all data at once. Therefore, this requires cnosdb to support tables without tags.

InfluxDB supports Complete feature implementation of `Field` and `Tag`, including `key, value, set`. This makes InfluxDB to support a wide range of scenarios. From this perspective, I think CnosDB needs to pay more attention on this feature as well.

**Comment by DjangoPeng** [comment]
@Subsegment WDYT

**Comment by roseboy-liu** [comment]
#842

**Comment by Subsegment** [comment]
https://github.com/cnosdb/cnosdb/releases/tag/v2.0.2-beta
