### ISSUE TITLE
[Bug] Overflow when calculating bucket time range

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#849]
**Describe the bug**

problem code

```Rust
pub fn get_time_range(ts: i64, duration: i64) -> (i64, i64) {
    if duration <= 0 {
        (std::i64::MIN, std::i64::MAX)
    } else {
        (
            (ts / duration) * duration,
            (ts / duration) * duration + duration,
        )
    }
}
```

Rust provides the following methods to handle overflows: checked_mul, saturating_mul, wrapping_mul, overflowing_mul. 

**To Reproduce**

Insert i64's maximum value as a timestamp

**Expected behavior**

Prompt time range overflow

**Additional context**

The logic in meta needs to be careful to handle situations that may cause panic, otherwise it will cause the entire cluster to be unavailable

**Comment by cnoshb** [comment]
Fixed.
