### ISSUE TITLE
[BUG] Panic when network error

### ISSUE THREAD

**Issue by ZuoTiJia** [cnosdb/cnosdb#852]
**Describe the bug**
A network interruption was encountered during runtime. At this time, some code called unwrap and caused a panic.

**Expected behavior**
Don't panic

**Additional context**

https://github.com/cnosdb/cnosdb/blob/c905674d0639fde5b6b4ebe4a31344a858deb4ce/meta/src/meta_client.rs#L351-L367

**Comment by bartliu827** [comment]
this will not happen again  after refactor meta client.

**Comment by bartliu827** [comment]
done
