### ISSUE TITLE
[BUG] Remote Read Fail

### ISSUE THREAD

**Issue by ZuoTiJia** [cnosdb/cnosdb#866]
**Describe the bug**
There are 3 data nodes, insert a piece of data into one data node, other data nodes cannot query the data.

**To Reproduce**
at node1 
```sql
create table test(a bigint, tags(b));
insert into test(time, a, b)  values (1, '2');
```
at node2
```sql
select * from test;
```
**Expected behavior**
Each data node can find data.

**Comment by cnoshb** [comment]
Fixed.
