### ISSUE TITLE
grafana datasource missing

### ISSUE THREAD

**Issue by suconghou** [cnosdb/cnosdb#882]
document error

https://docs.cnosdb.com/zh/guide/ecology/grafana.html#_1-%E8%BF%9E%E6%8E%A5-cnosdb

can not find cnosdb in grafana , grafana version  v9.3.6 (978237e7cb)

https://github.com/cnosdb/grafana-datasource-plugin/issues/9

**Comment by zipper-meng** [comment]
Cnosdb grafana datasource plugin is now reviewing by the grafana staff.

**Comment by cnoshb** [comment]
@heroPKU 
Can you help check when we can be added to Grafana officially？Thanks.
