### ISSUE TITLE
error: failed to run custom build command for protos v2.1.0

### ISSUE THREAD

**Issue by discovol** [cnosdb/cnosdb#886]
Compiling anyerror v0.1.7
   Compiling byte-unit v4.0.18
   Compiling serde_cbor v0.11.2
   Compiling os_info v3.6.0
error: failed to run custom build command for `protos v2.1.0 (/root/cnosdb/common/protos)`

Caused by:
  process didn't exit successfully: `/root/cnosdb/target/debug/build/protos-b53c771d715dccc1/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/root/cnosdb/common/protos/proto/kv_service.proto
  cargo:rerun-if-changed=/root/cnosdb/common/protos/proto/schema_service.proto
  cargo:rerun-if-changed=/root/cnosdb/common/protos/proto

  --- stderr
  thread 'main' panicked at '
  Could not find `protoc` installation and this build crate cannot proceed without
  this knowledge. If `protoc` is installed and this crate had trouble finding
  it, you can set the `PROTOC` environment variable with the specific path to your
  installed `protoc` binary.

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.11.1/src/lib.rs:1227:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:20: build] Error 101

RUST =========================================================

Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.64-x86_64-unknown-linux-gnu

active toolchain
----------------

1.64-x86_64-unknown-linux-gnu (overridden by '/root/cnosdb/rust-toolchain')
rustc 1.64.0 (a55dd71d5 2022-09-19)

OS =========================================================

Linux andy 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by Subsegment** [comment]
try `sudo apt-get install -y protobuf-compiler` maybe work
we will update our doc soon

**Comment by zipper-meng** [comment]
Looks like `tonic-build` needs an executable `protoc` after we upgraded it to 0.8.

Can we add rust files built from `.proto` files there to cut out the dependence of `protoc`?

**Comment by roseboy-liu** [comment]
> Looks like `tonic-build` needs an executable `protoc` after we upgraded it to 0.8.
> 
> Can we add rust files built from `.proto` files there to cut out the dependence of `protoc`? @roseboy-liu

Agree with you

**Comment by zonglin-hub** [comment]
When I run `cargo check`, the line `pub use flatbuffers_generated::models::*;` is automatically removed from `common/protos/src/generated/mod.rs`.
