### ISSUE TITLE
[Bug] Syntax issue on table creation

### ISSUE THREAD

**Issue by DjangoPeng** [cnosdb/cnosdb#910]
Now we have a SQL syntax of table creation as below:

```SQL
CREATE TABLE [IF NOT EXISTS] tb_name
(field_definition [, field_definition] ...TAGS(tg_name [, tg_name] ...));

field_definition:
    column_name data_type [field_codec_type]
    
field_codec_type:
    CODEC(code_type)
```

Original link: https://docs.cnosdb.com/zh/guide/query/table.html#%E5%88%9B%E5%BB%BA%E6%99%AE%E9%80%9A%E8%A1%A8

I found that there is a typo issue on field_definition which is confusing.

Actually, I think it should be replaced as following:

```SQL
CREATE TABLE [IF NOT EXISTS] tb_name
(field_definition, [field_definition, ] ...TAGS(tg_name, [tg_name,] ...));

field_definition:
    column_name data_type [field_codec_type]
    
field_codec_type:
    CODEC(code_type)

```

It's easily to verify when you only have one field or one tag.

**Comment by Subsegment** [comment]
already fixed. When the server updates the code, it sees the changed document

**Comment by DjangoPeng** [comment]
SGTM

**Comment by DjangoPeng** [comment]
I see that this issue has been closed, but it seems that it has not been completely resolved.

![image](https://user-images.githubusercontent.com/16943353/222077740-cce151b6-51fc-4290-b2df-2c1f70d7bc4c.png)

@Subsegment @ZuoTiJia

**Comment by ZuoTiJia** [comment]
Yes, the syntax does have problems.

**Comment by ZuoTiJia** [comment]
fixed in https://github.com/cnosdb/docs/pull/52
