### ISSUE TITLE
[BUG] Cmd cnosdb help info not clear.

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#934]
**Describe the bug**
Cmd cnosdb help info not clear.

**To Reproduce**
cnosdb --help

**Expected behavior**

**Additional context**
![image](https://user-images.githubusercontent.com/40594937/220534327-e67cd1bf-d7df-49d3-99ff-f9094f5474fd.png)

**Comment by roseboy-liu** [comment]
done
