### ISSUE TITLE
[BUG] Failed to run SQL that uses full outer join with a boolean literal join condition

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#939]
**Describe the bug**
sql query return ：Build left right indices error

**To Reproduce**
DROP DATABASE IF EXISTS database4;
CREATE DATABASE database4;
CREATE TABLE IF NOT EXISTS m0(f0 BOOLEAN , f1 BIGINT , TAGS(t0));
CREATE TABLE m1(f0 BIGINT , TAGS(t0));
CREATE TABLE m2(f0 STRING , f1 BIGINT , TAGS(t0, t1, t2));
CREATE TABLE m3(f0 BOOLEAN , TAGS(t0));
CREATE TABLE m4(f0 BOOLEAN , TAGS(t0));
INSERT m0(TIME, t0, f0, f1) VALUES(CAST (6908997557699974483 AS TIMESTAMP), 'o~jufz', FALSE, -248458502), (CAST (2631597345520092861 AS TIMESTAMP), 'DIᡊV.I_', FALSE, -1426729989), (CAST (3058448006108368876 AS TIMESTAMP), 'O~JUFZ', TRUE, 6908997557699974483);
INSERT m3(TIME, t0, f0) VALUES(CAST (3774904235698227806 AS TIMESTAMP), '{?', TRUE);
INSERT m4(TIME, t0, f0) VALUES(CAST (8669563973061725999 AS TIMESTAMP), 'PfKcoV^R', FALSE);
INSERT m1(TIME, t0, f0) VALUES(CAST (6118413606255739625 AS TIMESTAMP), '', -1426729989), (CAST (6243393833183272974 AS TIMESTAMP), 'Ro', 52006175), (CAST (3852617279739691069 AS TIMESTAMP), '-248458502', -85553256);
INSERT m3(TIME, t0, f0) VALUES(CAST (6536228763869079386 AS TIMESTAMP), '', FALSE);
INSERT m0(TIME, t0, f0, f1) VALUES(CAST (3774904235698227806 AS TIMESTAMP), 'RO', FALSE, 6243393833183272974);
INSERT m0(TIME, t0, f0, f1) VALUES(CAST (4898812193193349917 AS TIMESTAMP), 'Kg', TRUE, 1655674506), (CAST (271243983344314210 AS TIMESTAMP), ')௰', TRUE, -405727158), (CAST (4182925328334083959 AS TIMESTAMP), '', TRUE, -1186492708);
INSERT m4(TIME, t0, f0) VALUES(CAST (8195145111723227816 AS TIMESTAMP), 'zF좮(hN7uk', FALSE);
INSERT m3(TIME, t0, f0) VALUES(CAST (2631597345520092861 AS TIMESTAMP), 'vA', FALSE);
INSERT m1(TIME, t0, f0) VALUES(CAST (5401514494397353760 AS TIMESTAMP), '& ', 513674224);
INSERT m0(TIME, t0, f0, f1) VALUES(CAST (5408806048668873448 AS TIMESTAMP), '', TRUE, 1397425767);
INSERT m1(TIME, t0, f0) VALUES(CAST (1365197894198523345 AS TIMESTAMP), '6908997557699974483', 1397425767);
INSERT m3(TIME, t0, f0) VALUES(CAST (6558900541430780178 AS TIMESTAMP), '', FALSE);
SELECT m0.t0, m0.f0
FROM m0
  FULL JOIN m3 ON abs(0.3460278237805576306840293909772299230098724365234375 / 0.6761938683320958265454692082130350172519683837890625) NOT IN (0.1535995757663883853894049025257118046283721923828125);

**Expected behavior**
not error

**Additional context**
details: {\"error_code\":\"010001\",\"error_message\":\"Datafusion: External error: Execution error: Build left right indices error\"}"

**Comment by yukkit** [comment]
link https://github.com/apache/arrow-datafusion/issues/5382

**Comment by yukkit** [comment]
will be closed next time datafusion is upgraded

**Comment by yukkit** [comment]
resolved,  closed by https://github.com/cnosdb/cnosdb/issues/1096

**Comment by Benxiaohai001** [comment]
Verified, problem fixed：    version：f7f653df298bdd07ae461e090a0847f44d59fae9
