### ISSUE TITLE
Refactor the implementation of desc/show to query the system table

### ISSUE THREAD

**Issue by yukkit** [cnosdb/cnosdb#989]
**Is your feature request related to a problem? Please describe.**

Currently, there are two ways to query the metadata of database objects. In order to reuse the same implementation logic, it is necessary to refactor the implementation logic of desc table/desc database/show tables/show databases to directly query system tables

- [x] desc table
- [x] desc database
- [x] show tables
- [x] show databases

**Describe the solution you'd like**

- In the create_logical_plan stage, convert ast into a logical plan for querying system tables

**Describe alternatives you've considered**

**Additional context**

**Comment by guojidan** [comment]
I want to solve this issues :)

**Comment by yukkit** [comment]
Thanks @guojidan, assigned

**Comment by yukkit** [comment]
done
